// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type APIKeyMod interface {
	Apply(context.Context, *APIKeyTemplate)
}

type APIKeyModFunc func(context.Context, *APIKeyTemplate)

func (f APIKeyModFunc) Apply(ctx context.Context, n *APIKeyTemplate) {
	f(ctx, n)
}

type APIKeyModSlice []APIKeyMod

func (mods APIKeyModSlice) Apply(ctx context.Context, n *APIKeyTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// APIKeyTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type APIKeyTemplate struct {
	ID          func() string
	Key         func() string
	Name        func() string
	UserID      func() string
	CreatedDate func() time.Time
	Active      func() bool
	Expires     func() null.Val[time.Time]

	r apiKeyR
	f *Factory

	alreadyPersisted bool
}

type apiKeyR struct {
	User *apiKeyRUserR
}

type apiKeyRUserR struct {
	o *UserTemplate
}

// Apply mods to the APIKeyTemplate
func (o *APIKeyTemplate) Apply(ctx context.Context, mods ...APIKeyMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.APIKey
// according to the relationships in the template. Nothing is inserted into the db
func (t APIKeyTemplate) setModelRels(o *models.APIKey) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.APIKeys = append(rel.R.APIKeys, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.APIKeySetter
// this does nothing with the relationship templates
func (o APIKeyTemplate) BuildSetter() *models.APIKeySetter {
	m := &models.APIKeySetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Key != nil {
		val := o.Key()
		m.Key = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.CreatedDate != nil {
		val := o.CreatedDate()
		m.CreatedDate = omit.From(val)
	}
	if o.Active != nil {
		val := o.Active()
		m.Active = omit.From(val)
	}
	if o.Expires != nil {
		val := o.Expires()
		m.Expires = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.APIKeySetter
// this does nothing with the relationship templates
func (o APIKeyTemplate) BuildManySetter(number int) []*models.APIKeySetter {
	m := make([]*models.APIKeySetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.APIKey
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use APIKeyTemplate.Create
func (o APIKeyTemplate) Build() *models.APIKey {
	m := &models.APIKey{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Key != nil {
		m.Key = o.Key()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.CreatedDate != nil {
		m.CreatedDate = o.CreatedDate()
	}
	if o.Active != nil {
		m.Active = o.Active()
	}
	if o.Expires != nil {
		m.Expires = o.Expires()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.APIKeySlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use APIKeyTemplate.CreateMany
func (o APIKeyTemplate) BuildMany(number int) models.APIKeySlice {
	m := make(models.APIKeySlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAPIKey(m *models.APIKeySetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.Key.IsValue()) {
		val := random_string(nil)
		m.Key = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.APIKey
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *APIKeyTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.APIKey) error {
	var err error

	return err
}

// Create builds a apiKey and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *APIKeyTemplate) Create(ctx context.Context, exec bob.Executor) (*models.APIKey, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAPIKey(opt)

	if o.r.User == nil {
		APIKeyMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.APIKeys.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a apiKey and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *APIKeyTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.APIKey {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a apiKey and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *APIKeyTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.APIKey {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple apiKeys and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o APIKeyTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.APIKeySlice, error) {
	var err error
	m := make(models.APIKeySlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple apiKeys and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o APIKeyTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.APIKeySlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple apiKeys and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o APIKeyTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.APIKeySlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// APIKey has methods that act as mods for the APIKeyTemplate
var APIKeyMods apiKeyMods

type apiKeyMods struct{}

func (m apiKeyMods) RandomizeAllColumns(f *faker.Faker) APIKeyMod {
	return APIKeyModSlice{
		APIKeyMods.RandomID(f),
		APIKeyMods.RandomKey(f),
		APIKeyMods.RandomName(f),
		APIKeyMods.RandomUserID(f),
		APIKeyMods.RandomCreatedDate(f),
		APIKeyMods.RandomActive(f),
		APIKeyMods.RandomExpires(f),
	}
}

// Set the model columns to this value
func (m apiKeyMods) ID(val string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) IDFunc(f func() string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetID() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomID(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) Key(val string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Key = func() string { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) KeyFunc(f func() string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Key = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetKey() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Key = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomKey(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Key = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) Name(val string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) NameFunc(f func() string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetName() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomName(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) UserID(val string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) UserIDFunc(f func() string) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetUserID() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomUserID(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.UserID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) CreatedDate(val time.Time) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.CreatedDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) CreatedDateFunc(f func() time.Time) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.CreatedDate = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetCreatedDate() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.CreatedDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomCreatedDate(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.CreatedDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) Active(val bool) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Active = func() bool { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) ActiveFunc(f func() bool) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Active = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetActive() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Active = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiKeyMods) RandomActive(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Active = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m apiKeyMods) Expires(val null.Val[time.Time]) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Expires = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m apiKeyMods) ExpiresFunc(f func() null.Val[time.Time]) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Expires = f
	})
}

// Clear any values for the column
func (m apiKeyMods) UnsetExpires() APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Expires = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m apiKeyMods) RandomExpires(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Expires = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m apiKeyMods) RandomExpiresNotNull(f *faker.Faker) APIKeyMod {
	return APIKeyModFunc(func(_ context.Context, o *APIKeyTemplate) {
		o.Expires = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m apiKeyMods) WithParentsCascading() APIKeyMod {
	return APIKeyModFunc(func(ctx context.Context, o *APIKeyTemplate) {
		if isDone, _ := apiKeyWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = apiKeyWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m apiKeyMods) WithUser(rel *UserTemplate) APIKeyMod {
	return APIKeyModFunc(func(ctx context.Context, o *APIKeyTemplate) {
		o.r.User = &apiKeyRUserR{
			o: rel,
		}
	})
}

func (m apiKeyMods) WithNewUser(mods ...UserMod) APIKeyMod {
	return APIKeyModFunc(func(ctx context.Context, o *APIKeyTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m apiKeyMods) WithExistingUser(em *models.User) APIKeyMod {
	return APIKeyModFunc(func(ctx context.Context, o *APIKeyTemplate) {
		o.r.User = &apiKeyRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m apiKeyMods) WithoutUser() APIKeyMod {
	return APIKeyModFunc(func(ctx context.Context, o *APIKeyTemplate) {
		o.r.User = nil
	})
}
