// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type GroupMod interface {
	Apply(context.Context, *GroupTemplate)
}

type GroupModFunc func(context.Context, *GroupTemplate)

func (f GroupModFunc) Apply(ctx context.Context, n *GroupTemplate) {
	f(ctx, n)
}

type GroupModSlice []GroupMod

func (mods GroupModSlice) Apply(ctx context.Context, n *GroupTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// GroupTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type GroupTemplate struct {
	ID           func() string
	Name         func() string
	CreatedDate  func() time.Time
	Public       func() bool
	Active       func() bool
	Weight       func() int64
	StatusPageID func() null.Val[string]

	r groupR
	f *Factory

	alreadyPersisted bool
}

type groupR struct {
	StatusPage    *groupRStatusPageR
	MonitorGroups []*groupRMonitorGroupsR
}

type groupRStatusPageR struct {
	o *StatusPageTemplate
}
type groupRMonitorGroupsR struct {
	number int
	o      *MonitorGroupTemplate
}

// Apply mods to the GroupTemplate
func (o *GroupTemplate) Apply(ctx context.Context, mods ...GroupMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Group
// according to the relationships in the template. Nothing is inserted into the db
func (t GroupTemplate) setModelRels(o *models.Group) {
	if t.r.StatusPage != nil {
		rel := t.r.StatusPage.o.Build()
		rel.R.Groups = append(rel.R.Groups, o)
		o.StatusPageID = null.From(rel.ID) // h2
		o.R.StatusPage = rel
	}

	if t.r.MonitorGroups != nil {
		rel := models.MonitorGroupSlice{}
		for _, r := range t.r.MonitorGroups {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.GroupID = o.ID // h2
				rel.R.Group = o
			}
			rel = append(rel, related...)
		}
		o.R.MonitorGroups = rel
	}
}

// BuildSetter returns an *models.GroupSetter
// this does nothing with the relationship templates
func (o GroupTemplate) BuildSetter() *models.GroupSetter {
	m := &models.GroupSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.CreatedDate != nil {
		val := o.CreatedDate()
		m.CreatedDate = omit.From(val)
	}
	if o.Public != nil {
		val := o.Public()
		m.Public = omit.From(val)
	}
	if o.Active != nil {
		val := o.Active()
		m.Active = omit.From(val)
	}
	if o.Weight != nil {
		val := o.Weight()
		m.Weight = omit.From(val)
	}
	if o.StatusPageID != nil {
		val := o.StatusPageID()
		m.StatusPageID = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.GroupSetter
// this does nothing with the relationship templates
func (o GroupTemplate) BuildManySetter(number int) []*models.GroupSetter {
	m := make([]*models.GroupSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Group
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use GroupTemplate.Create
func (o GroupTemplate) Build() *models.Group {
	m := &models.Group{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.CreatedDate != nil {
		m.CreatedDate = o.CreatedDate()
	}
	if o.Public != nil {
		m.Public = o.Public()
	}
	if o.Active != nil {
		m.Active = o.Active()
	}
	if o.Weight != nil {
		m.Weight = o.Weight()
	}
	if o.StatusPageID != nil {
		m.StatusPageID = o.StatusPageID()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.GroupSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use GroupTemplate.CreateMany
func (o GroupTemplate) BuildMany(number int) models.GroupSlice {
	m := make(models.GroupSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableGroup(m *models.GroupSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Group
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *GroupTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Group) error {
	var err error

	isStatusPageDone, _ := groupRelStatusPageCtx.Value(ctx)
	if !isStatusPageDone && o.r.StatusPage != nil {
		ctx = groupRelStatusPageCtx.WithValue(ctx, true)
		if o.r.StatusPage.o.alreadyPersisted {
			m.R.StatusPage = o.r.StatusPage.o.Build()
		} else {
			var rel0 *models.StatusPage
			rel0, err = o.r.StatusPage.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachStatusPage(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	isMonitorGroupsDone, _ := groupRelMonitorGroupsCtx.Value(ctx)
	if !isMonitorGroupsDone && o.r.MonitorGroups != nil {
		ctx = groupRelMonitorGroupsCtx.WithValue(ctx, true)
		for _, r := range o.r.MonitorGroups {
			if r.o.alreadyPersisted {
				m.R.MonitorGroups = append(m.R.MonitorGroups, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMonitorGroups(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a group and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *GroupTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Group, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableGroup(opt)

	m, err := models.Groups.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a group and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *GroupTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Group {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a group and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *GroupTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Group {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple groups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o GroupTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.GroupSlice, error) {
	var err error
	m := make(models.GroupSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple groups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o GroupTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.GroupSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple groups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o GroupTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.GroupSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Group has methods that act as mods for the GroupTemplate
var GroupMods groupMods

type groupMods struct{}

func (m groupMods) RandomizeAllColumns(f *faker.Faker) GroupMod {
	return GroupModSlice{
		GroupMods.RandomID(f),
		GroupMods.RandomName(f),
		GroupMods.RandomCreatedDate(f),
		GroupMods.RandomPublic(f),
		GroupMods.RandomActive(f),
		GroupMods.RandomWeight(f),
		GroupMods.RandomStatusPageID(f),
	}
}

// Set the model columns to this value
func (m groupMods) ID(val string) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m groupMods) IDFunc(f func() string) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetID() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomID(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) Name(val string) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m groupMods) NameFunc(f func() string) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetName() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomName(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) CreatedDate(val time.Time) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.CreatedDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m groupMods) CreatedDateFunc(f func() time.Time) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.CreatedDate = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetCreatedDate() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.CreatedDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomCreatedDate(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.CreatedDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) Public(val bool) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Public = func() bool { return val }
	})
}

// Set the Column from the function
func (m groupMods) PublicFunc(f func() bool) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Public = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetPublic() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Public = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomPublic(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Public = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) Active(val bool) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Active = func() bool { return val }
	})
}

// Set the Column from the function
func (m groupMods) ActiveFunc(f func() bool) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Active = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetActive() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Active = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomActive(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Active = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) Weight(val int64) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Weight = func() int64 { return val }
	})
}

// Set the Column from the function
func (m groupMods) WeightFunc(f func() int64) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Weight = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetWeight() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Weight = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m groupMods) RandomWeight(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.Weight = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m groupMods) StatusPageID(val null.Val[string]) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.StatusPageID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m groupMods) StatusPageIDFunc(f func() null.Val[string]) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.StatusPageID = f
	})
}

// Clear any values for the column
func (m groupMods) UnsetStatusPageID() GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.StatusPageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m groupMods) RandomStatusPageID(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.StatusPageID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m groupMods) RandomStatusPageIDNotNull(f *faker.Faker) GroupMod {
	return GroupModFunc(func(_ context.Context, o *GroupTemplate) {
		o.StatusPageID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m groupMods) WithParentsCascading() GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		if isDone, _ := groupWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = groupWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewStatusPageWithContext(ctx, StatusPageMods.WithParentsCascading())
			m.WithStatusPage(related).Apply(ctx, o)
		}
	})
}

func (m groupMods) WithStatusPage(rel *StatusPageTemplate) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.StatusPage = &groupRStatusPageR{
			o: rel,
		}
	})
}

func (m groupMods) WithNewStatusPage(mods ...StatusPageMod) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		related := o.f.NewStatusPageWithContext(ctx, mods...)

		m.WithStatusPage(related).Apply(ctx, o)
	})
}

func (m groupMods) WithExistingStatusPage(em *models.StatusPage) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.StatusPage = &groupRStatusPageR{
			o: o.f.FromExistingStatusPage(em),
		}
	})
}

func (m groupMods) WithoutStatusPage() GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.StatusPage = nil
	})
}

func (m groupMods) WithMonitorGroups(number int, related *MonitorGroupTemplate) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.MonitorGroups = []*groupRMonitorGroupsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m groupMods) WithNewMonitorGroups(number int, mods ...MonitorGroupMod) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		related := o.f.NewMonitorGroupWithContext(ctx, mods...)
		m.WithMonitorGroups(number, related).Apply(ctx, o)
	})
}

func (m groupMods) AddMonitorGroups(number int, related *MonitorGroupTemplate) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.MonitorGroups = append(o.r.MonitorGroups, &groupRMonitorGroupsR{
			number: number,
			o:      related,
		})
	})
}

func (m groupMods) AddNewMonitorGroups(number int, mods ...MonitorGroupMod) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		related := o.f.NewMonitorGroupWithContext(ctx, mods...)
		m.AddMonitorGroups(number, related).Apply(ctx, o)
	})
}

func (m groupMods) AddExistingMonitorGroups(existingModels ...*models.MonitorGroup) GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		for _, em := range existingModels {
			o.r.MonitorGroups = append(o.r.MonitorGroups, &groupRMonitorGroupsR{
				o: o.f.FromExistingMonitorGroup(em),
			})
		}
	})
}

func (m groupMods) WithoutMonitorGroups() GroupMod {
	return GroupModFunc(func(ctx context.Context, o *GroupTemplate) {
		o.r.MonitorGroups = nil
	})
}
