// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type MaintenanceMod interface {
	Apply(context.Context, *MaintenanceTemplate)
}

type MaintenanceModFunc func(context.Context, *MaintenanceTemplate)

func (f MaintenanceModFunc) Apply(ctx context.Context, n *MaintenanceTemplate) {
	f(ctx, n)
}

type MaintenanceModSlice []MaintenanceMod

func (mods MaintenanceModSlice) Apply(ctx context.Context, n *MaintenanceTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MaintenanceTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MaintenanceTemplate struct {
	ID          func() string
	Title       func() string
	Description func() null.Val[string]
	UserID      func() string
	Active      func() bool
	Strategy    func() string
	StartDate   func() null.Val[time.Time]
	EndDate     func() null.Val[time.Time]
	StartTime   func() null.Val[string]
	EndTime     func() null.Val[string]
	Weekdays    func() null.Val[string]
	DaysOfMonth func() null.Val[string]
	IntervalDay func() null.Val[int64]
	Cron        func() null.Val[string]
	Timezone    func() null.Val[string]
	Duration    func() null.Val[int64]

	r maintenanceR
	f *Factory

	alreadyPersisted bool
}

type maintenanceR struct {
	User                   *maintenanceRUserR
	MaintenanceStatusPages []*maintenanceRMaintenanceStatusPagesR
	MaintenanceTimeslots   []*maintenanceRMaintenanceTimeslotsR
	MonitorMaintenances    []*maintenanceRMonitorMaintenancesR
}

type maintenanceRUserR struct {
	o *UserTemplate
}
type maintenanceRMaintenanceStatusPagesR struct {
	number int
	o      *MaintenanceStatusPageTemplate
}
type maintenanceRMaintenanceTimeslotsR struct {
	number int
	o      *MaintenanceTimeslotTemplate
}
type maintenanceRMonitorMaintenancesR struct {
	number int
	o      *MonitorMaintenanceTemplate
}

// Apply mods to the MaintenanceTemplate
func (o *MaintenanceTemplate) Apply(ctx context.Context, mods ...MaintenanceMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Maintenance
// according to the relationships in the template. Nothing is inserted into the db
func (t MaintenanceTemplate) setModelRels(o *models.Maintenance) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Maintenances = append(rel.R.Maintenances, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}

	if t.r.MaintenanceStatusPages != nil {
		rel := models.MaintenanceStatusPageSlice{}
		for _, r := range t.r.MaintenanceStatusPages {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.MaintenanceID = o.ID // h2
				rel.R.Maintenance = o
			}
			rel = append(rel, related...)
		}
		o.R.MaintenanceStatusPages = rel
	}

	if t.r.MaintenanceTimeslots != nil {
		rel := models.MaintenanceTimeslotSlice{}
		for _, r := range t.r.MaintenanceTimeslots {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.MaintenanceID = o.ID // h2
				rel.R.Maintenance = o
			}
			rel = append(rel, related...)
		}
		o.R.MaintenanceTimeslots = rel
	}

	if t.r.MonitorMaintenances != nil {
		rel := models.MonitorMaintenanceSlice{}
		for _, r := range t.r.MonitorMaintenances {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.MaintenanceID = o.ID // h2
				rel.R.Maintenance = o
			}
			rel = append(rel, related...)
		}
		o.R.MonitorMaintenances = rel
	}
}

// BuildSetter returns an *models.MaintenanceSetter
// this does nothing with the relationship templates
func (o MaintenanceTemplate) BuildSetter() *models.MaintenanceSetter {
	m := &models.MaintenanceSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Active != nil {
		val := o.Active()
		m.Active = omit.From(val)
	}
	if o.Strategy != nil {
		val := o.Strategy()
		m.Strategy = omit.From(val)
	}
	if o.StartDate != nil {
		val := o.StartDate()
		m.StartDate = omitnull.FromNull(val)
	}
	if o.EndDate != nil {
		val := o.EndDate()
		m.EndDate = omitnull.FromNull(val)
	}
	if o.StartTime != nil {
		val := o.StartTime()
		m.StartTime = omitnull.FromNull(val)
	}
	if o.EndTime != nil {
		val := o.EndTime()
		m.EndTime = omitnull.FromNull(val)
	}
	if o.Weekdays != nil {
		val := o.Weekdays()
		m.Weekdays = omitnull.FromNull(val)
	}
	if o.DaysOfMonth != nil {
		val := o.DaysOfMonth()
		m.DaysOfMonth = omitnull.FromNull(val)
	}
	if o.IntervalDay != nil {
		val := o.IntervalDay()
		m.IntervalDay = omitnull.FromNull(val)
	}
	if o.Cron != nil {
		val := o.Cron()
		m.Cron = omitnull.FromNull(val)
	}
	if o.Timezone != nil {
		val := o.Timezone()
		m.Timezone = omitnull.FromNull(val)
	}
	if o.Duration != nil {
		val := o.Duration()
		m.Duration = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MaintenanceSetter
// this does nothing with the relationship templates
func (o MaintenanceTemplate) BuildManySetter(number int) []*models.MaintenanceSetter {
	m := make([]*models.MaintenanceSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Maintenance
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceTemplate.Create
func (o MaintenanceTemplate) Build() *models.Maintenance {
	m := &models.Maintenance{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Active != nil {
		m.Active = o.Active()
	}
	if o.Strategy != nil {
		m.Strategy = o.Strategy()
	}
	if o.StartDate != nil {
		m.StartDate = o.StartDate()
	}
	if o.EndDate != nil {
		m.EndDate = o.EndDate()
	}
	if o.StartTime != nil {
		m.StartTime = o.StartTime()
	}
	if o.EndTime != nil {
		m.EndTime = o.EndTime()
	}
	if o.Weekdays != nil {
		m.Weekdays = o.Weekdays()
	}
	if o.DaysOfMonth != nil {
		m.DaysOfMonth = o.DaysOfMonth()
	}
	if o.IntervalDay != nil {
		m.IntervalDay = o.IntervalDay()
	}
	if o.Cron != nil {
		m.Cron = o.Cron()
	}
	if o.Timezone != nil {
		m.Timezone = o.Timezone()
	}
	if o.Duration != nil {
		m.Duration = o.Duration()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MaintenanceSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceTemplate.CreateMany
func (o MaintenanceTemplate) BuildMany(number int) models.MaintenanceSlice {
	m := make(models.MaintenanceSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMaintenance(m *models.MaintenanceSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.Title.IsValue()) {
		val := random_string(nil)
		m.Title = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Maintenance
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MaintenanceTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Maintenance) error {
	var err error

	isMaintenanceStatusPagesDone, _ := maintenanceRelMaintenanceStatusPagesCtx.Value(ctx)
	if !isMaintenanceStatusPagesDone && o.r.MaintenanceStatusPages != nil {
		ctx = maintenanceRelMaintenanceStatusPagesCtx.WithValue(ctx, true)
		for _, r := range o.r.MaintenanceStatusPages {
			if r.o.alreadyPersisted {
				m.R.MaintenanceStatusPages = append(m.R.MaintenanceStatusPages, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMaintenanceStatusPages(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isMaintenanceTimeslotsDone, _ := maintenanceRelMaintenanceTimeslotsCtx.Value(ctx)
	if !isMaintenanceTimeslotsDone && o.r.MaintenanceTimeslots != nil {
		ctx = maintenanceRelMaintenanceTimeslotsCtx.WithValue(ctx, true)
		for _, r := range o.r.MaintenanceTimeslots {
			if r.o.alreadyPersisted {
				m.R.MaintenanceTimeslots = append(m.R.MaintenanceTimeslots, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMaintenanceTimeslots(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isMonitorMaintenancesDone, _ := maintenanceRelMonitorMaintenancesCtx.Value(ctx)
	if !isMonitorMaintenancesDone && o.r.MonitorMaintenances != nil {
		ctx = maintenanceRelMonitorMaintenancesCtx.WithValue(ctx, true)
		for _, r := range o.r.MonitorMaintenances {
			if r.o.alreadyPersisted {
				m.R.MonitorMaintenances = append(m.R.MonitorMaintenances, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMonitorMaintenances(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a maintenance and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MaintenanceTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Maintenance, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMaintenance(opt)

	if o.r.User == nil {
		MaintenanceMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Maintenances.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a maintenance and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MaintenanceTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Maintenance {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a maintenance and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MaintenanceTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Maintenance {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple maintenances and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MaintenanceTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MaintenanceSlice, error) {
	var err error
	m := make(models.MaintenanceSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple maintenances and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MaintenanceTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MaintenanceSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple maintenances and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MaintenanceTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MaintenanceSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Maintenance has methods that act as mods for the MaintenanceTemplate
var MaintenanceMods maintenanceMods

type maintenanceMods struct{}

func (m maintenanceMods) RandomizeAllColumns(f *faker.Faker) MaintenanceMod {
	return MaintenanceModSlice{
		MaintenanceMods.RandomID(f),
		MaintenanceMods.RandomTitle(f),
		MaintenanceMods.RandomDescription(f),
		MaintenanceMods.RandomUserID(f),
		MaintenanceMods.RandomActive(f),
		MaintenanceMods.RandomStrategy(f),
		MaintenanceMods.RandomStartDate(f),
		MaintenanceMods.RandomEndDate(f),
		MaintenanceMods.RandomStartTime(f),
		MaintenanceMods.RandomEndTime(f),
		MaintenanceMods.RandomWeekdays(f),
		MaintenanceMods.RandomDaysOfMonth(f),
		MaintenanceMods.RandomIntervalDay(f),
		MaintenanceMods.RandomCron(f),
		MaintenanceMods.RandomTimezone(f),
		MaintenanceMods.RandomDuration(f),
	}
}

// Set the model columns to this value
func (m maintenanceMods) ID(val string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) IDFunc(f func() string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetID() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceMods) RandomID(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Title(val string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) TitleFunc(f func() string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetTitle() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceMods) RandomTitle(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Title = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Description(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) DescriptionFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetDescription() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomDescription(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomDescriptionNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) UserID(val string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) UserIDFunc(f func() string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetUserID() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceMods) RandomUserID(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.UserID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Active(val bool) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Active = func() bool { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) ActiveFunc(f func() bool) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Active = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetActive() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Active = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceMods) RandomActive(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Active = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Strategy(val string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Strategy = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) StrategyFunc(f func() string) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Strategy = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetStrategy() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Strategy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceMods) RandomStrategy(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Strategy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) StartDate(val null.Val[time.Time]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartDate = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) StartDateFunc(f func() null.Val[time.Time]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartDate = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetStartDate() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomStartDate(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomStartDateNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) EndDate(val null.Val[time.Time]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndDate = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) EndDateFunc(f func() null.Val[time.Time]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndDate = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetEndDate() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomEndDate(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomEndDateNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) StartTime(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartTime = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) StartTimeFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartTime = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetStartTime() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartTime = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomStartTime(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartTime = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomStartTimeNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.StartTime = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) EndTime(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndTime = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) EndTimeFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndTime = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetEndTime() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndTime = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomEndTime(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndTime = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomEndTimeNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.EndTime = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Weekdays(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Weekdays = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) WeekdaysFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Weekdays = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetWeekdays() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Weekdays = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomWeekdays(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Weekdays = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomWeekdaysNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Weekdays = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) DaysOfMonth(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.DaysOfMonth = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) DaysOfMonthFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.DaysOfMonth = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetDaysOfMonth() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.DaysOfMonth = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomDaysOfMonth(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.DaysOfMonth = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomDaysOfMonthNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.DaysOfMonth = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) IntervalDay(val null.Val[int64]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.IntervalDay = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) IntervalDayFunc(f func() null.Val[int64]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.IntervalDay = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetIntervalDay() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.IntervalDay = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomIntervalDay(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.IntervalDay = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomIntervalDayNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.IntervalDay = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Cron(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Cron = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) CronFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Cron = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetCron() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Cron = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomCron(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Cron = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomCronNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Cron = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Timezone(val null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Timezone = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) TimezoneFunc(f func() null.Val[string]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Timezone = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetTimezone() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Timezone = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomTimezone(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Timezone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomTimezoneNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Timezone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceMods) Duration(val null.Val[int64]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Duration = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m maintenanceMods) DurationFunc(f func() null.Val[int64]) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Duration = f
	})
}

// Clear any values for the column
func (m maintenanceMods) UnsetDuration() MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Duration = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceMods) RandomDuration(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Duration = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceMods) RandomDurationNotNull(f *faker.Faker) MaintenanceMod {
	return MaintenanceModFunc(func(_ context.Context, o *MaintenanceTemplate) {
		o.Duration = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

func (m maintenanceMods) WithParentsCascading() MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		if isDone, _ := maintenanceWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = maintenanceWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m maintenanceMods) WithUser(rel *UserTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.User = &maintenanceRUserR{
			o: rel,
		}
	})
}

func (m maintenanceMods) WithNewUser(mods ...UserMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m maintenanceMods) WithExistingUser(em *models.User) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.User = &maintenanceRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m maintenanceMods) WithoutUser() MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.User = nil
	})
}

func (m maintenanceMods) WithMaintenanceStatusPages(number int, related *MaintenanceStatusPageTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceStatusPages = []*maintenanceRMaintenanceStatusPagesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m maintenanceMods) WithNewMaintenanceStatusPages(number int, mods ...MaintenanceStatusPageMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMaintenanceStatusPageWithContext(ctx, mods...)
		m.WithMaintenanceStatusPages(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddMaintenanceStatusPages(number int, related *MaintenanceStatusPageTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceStatusPages = append(o.r.MaintenanceStatusPages, &maintenanceRMaintenanceStatusPagesR{
			number: number,
			o:      related,
		})
	})
}

func (m maintenanceMods) AddNewMaintenanceStatusPages(number int, mods ...MaintenanceStatusPageMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMaintenanceStatusPageWithContext(ctx, mods...)
		m.AddMaintenanceStatusPages(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddExistingMaintenanceStatusPages(existingModels ...*models.MaintenanceStatusPage) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		for _, em := range existingModels {
			o.r.MaintenanceStatusPages = append(o.r.MaintenanceStatusPages, &maintenanceRMaintenanceStatusPagesR{
				o: o.f.FromExistingMaintenanceStatusPage(em),
			})
		}
	})
}

func (m maintenanceMods) WithoutMaintenanceStatusPages() MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceStatusPages = nil
	})
}

func (m maintenanceMods) WithMaintenanceTimeslots(number int, related *MaintenanceTimeslotTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceTimeslots = []*maintenanceRMaintenanceTimeslotsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m maintenanceMods) WithNewMaintenanceTimeslots(number int, mods ...MaintenanceTimeslotMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMaintenanceTimeslotWithContext(ctx, mods...)
		m.WithMaintenanceTimeslots(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddMaintenanceTimeslots(number int, related *MaintenanceTimeslotTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceTimeslots = append(o.r.MaintenanceTimeslots, &maintenanceRMaintenanceTimeslotsR{
			number: number,
			o:      related,
		})
	})
}

func (m maintenanceMods) AddNewMaintenanceTimeslots(number int, mods ...MaintenanceTimeslotMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMaintenanceTimeslotWithContext(ctx, mods...)
		m.AddMaintenanceTimeslots(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddExistingMaintenanceTimeslots(existingModels ...*models.MaintenanceTimeslot) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		for _, em := range existingModels {
			o.r.MaintenanceTimeslots = append(o.r.MaintenanceTimeslots, &maintenanceRMaintenanceTimeslotsR{
				o: o.f.FromExistingMaintenanceTimeslot(em),
			})
		}
	})
}

func (m maintenanceMods) WithoutMaintenanceTimeslots() MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MaintenanceTimeslots = nil
	})
}

func (m maintenanceMods) WithMonitorMaintenances(number int, related *MonitorMaintenanceTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MonitorMaintenances = []*maintenanceRMonitorMaintenancesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m maintenanceMods) WithNewMonitorMaintenances(number int, mods ...MonitorMaintenanceMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMonitorMaintenanceWithContext(ctx, mods...)
		m.WithMonitorMaintenances(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddMonitorMaintenances(number int, related *MonitorMaintenanceTemplate) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MonitorMaintenances = append(o.r.MonitorMaintenances, &maintenanceRMonitorMaintenancesR{
			number: number,
			o:      related,
		})
	})
}

func (m maintenanceMods) AddNewMonitorMaintenances(number int, mods ...MonitorMaintenanceMod) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		related := o.f.NewMonitorMaintenanceWithContext(ctx, mods...)
		m.AddMonitorMaintenances(number, related).Apply(ctx, o)
	})
}

func (m maintenanceMods) AddExistingMonitorMaintenances(existingModels ...*models.MonitorMaintenance) MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		for _, em := range existingModels {
			o.r.MonitorMaintenances = append(o.r.MonitorMaintenances, &maintenanceRMonitorMaintenancesR{
				o: o.f.FromExistingMonitorMaintenance(em),
			})
		}
	})
}

func (m maintenanceMods) WithoutMonitorMaintenances() MaintenanceMod {
	return MaintenanceModFunc(func(ctx context.Context, o *MaintenanceTemplate) {
		o.r.MonitorMaintenances = nil
	})
}
