// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type MaintenanceStatusPageMod interface {
	Apply(context.Context, *MaintenanceStatusPageTemplate)
}

type MaintenanceStatusPageModFunc func(context.Context, *MaintenanceStatusPageTemplate)

func (f MaintenanceStatusPageModFunc) Apply(ctx context.Context, n *MaintenanceStatusPageTemplate) {
	f(ctx, n)
}

type MaintenanceStatusPageModSlice []MaintenanceStatusPageMod

func (mods MaintenanceStatusPageModSlice) Apply(ctx context.Context, n *MaintenanceStatusPageTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MaintenanceStatusPageTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MaintenanceStatusPageTemplate struct {
	ID            func() string
	StatusPageID  func() string
	MaintenanceID func() string

	r maintenanceStatusPageR
	f *Factory

	alreadyPersisted bool
}

type maintenanceStatusPageR struct {
	Maintenance *maintenanceStatusPageRMaintenanceR
	StatusPage  *maintenanceStatusPageRStatusPageR
}

type maintenanceStatusPageRMaintenanceR struct {
	o *MaintenanceTemplate
}
type maintenanceStatusPageRStatusPageR struct {
	o *StatusPageTemplate
}

// Apply mods to the MaintenanceStatusPageTemplate
func (o *MaintenanceStatusPageTemplate) Apply(ctx context.Context, mods ...MaintenanceStatusPageMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MaintenanceStatusPage
// according to the relationships in the template. Nothing is inserted into the db
func (t MaintenanceStatusPageTemplate) setModelRels(o *models.MaintenanceStatusPage) {
	if t.r.Maintenance != nil {
		rel := t.r.Maintenance.o.Build()
		rel.R.MaintenanceStatusPages = append(rel.R.MaintenanceStatusPages, o)
		o.MaintenanceID = rel.ID // h2
		o.R.Maintenance = rel
	}

	if t.r.StatusPage != nil {
		rel := t.r.StatusPage.o.Build()
		rel.R.MaintenanceStatusPages = append(rel.R.MaintenanceStatusPages, o)
		o.StatusPageID = rel.ID // h2
		o.R.StatusPage = rel
	}
}

// BuildSetter returns an *models.MaintenanceStatusPageSetter
// this does nothing with the relationship templates
func (o MaintenanceStatusPageTemplate) BuildSetter() *models.MaintenanceStatusPageSetter {
	m := &models.MaintenanceStatusPageSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.StatusPageID != nil {
		val := o.StatusPageID()
		m.StatusPageID = omit.From(val)
	}
	if o.MaintenanceID != nil {
		val := o.MaintenanceID()
		m.MaintenanceID = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.MaintenanceStatusPageSetter
// this does nothing with the relationship templates
func (o MaintenanceStatusPageTemplate) BuildManySetter(number int) []*models.MaintenanceStatusPageSetter {
	m := make([]*models.MaintenanceStatusPageSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MaintenanceStatusPage
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceStatusPageTemplate.Create
func (o MaintenanceStatusPageTemplate) Build() *models.MaintenanceStatusPage {
	m := &models.MaintenanceStatusPage{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.StatusPageID != nil {
		m.StatusPageID = o.StatusPageID()
	}
	if o.MaintenanceID != nil {
		m.MaintenanceID = o.MaintenanceID()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MaintenanceStatusPageSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceStatusPageTemplate.CreateMany
func (o MaintenanceStatusPageTemplate) BuildMany(number int) models.MaintenanceStatusPageSlice {
	m := make(models.MaintenanceStatusPageSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMaintenanceStatusPage(m *models.MaintenanceStatusPageSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.StatusPageID.IsValue()) {
		val := random_string(nil)
		m.StatusPageID = omit.From(val)
	}
	if !(m.MaintenanceID.IsValue()) {
		val := random_string(nil)
		m.MaintenanceID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MaintenanceStatusPage
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MaintenanceStatusPageTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MaintenanceStatusPage) error {
	var err error

	return err
}

// Create builds a maintenanceStatusPage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MaintenanceStatusPageTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MaintenanceStatusPage, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMaintenanceStatusPage(opt)

	if o.r.Maintenance == nil {
		MaintenanceStatusPageMods.WithNewMaintenance().Apply(ctx, o)
	}

	var rel0 *models.Maintenance

	if o.r.Maintenance.o.alreadyPersisted {
		rel0 = o.r.Maintenance.o.Build()
	} else {
		rel0, err = o.r.Maintenance.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.MaintenanceID = omit.From(rel0.ID)

	if o.r.StatusPage == nil {
		MaintenanceStatusPageMods.WithNewStatusPage().Apply(ctx, o)
	}

	var rel1 *models.StatusPage

	if o.r.StatusPage.o.alreadyPersisted {
		rel1 = o.r.StatusPage.o.Build()
	} else {
		rel1, err = o.r.StatusPage.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.StatusPageID = omit.From(rel1.ID)

	m, err := models.MaintenanceStatusPages.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Maintenance = rel0
	m.R.StatusPage = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a maintenanceStatusPage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MaintenanceStatusPageTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MaintenanceStatusPage {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a maintenanceStatusPage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MaintenanceStatusPageTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MaintenanceStatusPage {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple maintenanceStatusPages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MaintenanceStatusPageTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MaintenanceStatusPageSlice, error) {
	var err error
	m := make(models.MaintenanceStatusPageSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple maintenanceStatusPages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MaintenanceStatusPageTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MaintenanceStatusPageSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple maintenanceStatusPages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MaintenanceStatusPageTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MaintenanceStatusPageSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MaintenanceStatusPage has methods that act as mods for the MaintenanceStatusPageTemplate
var MaintenanceStatusPageMods maintenanceStatusPageMods

type maintenanceStatusPageMods struct{}

func (m maintenanceStatusPageMods) RandomizeAllColumns(f *faker.Faker) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModSlice{
		MaintenanceStatusPageMods.RandomID(f),
		MaintenanceStatusPageMods.RandomStatusPageID(f),
		MaintenanceStatusPageMods.RandomMaintenanceID(f),
	}
}

// Set the model columns to this value
func (m maintenanceStatusPageMods) ID(val string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceStatusPageMods) IDFunc(f func() string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m maintenanceStatusPageMods) UnsetID() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceStatusPageMods) RandomID(f *faker.Faker) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceStatusPageMods) StatusPageID(val string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.StatusPageID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceStatusPageMods) StatusPageIDFunc(f func() string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.StatusPageID = f
	})
}

// Clear any values for the column
func (m maintenanceStatusPageMods) UnsetStatusPageID() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.StatusPageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceStatusPageMods) RandomStatusPageID(f *faker.Faker) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.StatusPageID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceStatusPageMods) MaintenanceID(val string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.MaintenanceID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceStatusPageMods) MaintenanceIDFunc(f func() string) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.MaintenanceID = f
	})
}

// Clear any values for the column
func (m maintenanceStatusPageMods) UnsetMaintenanceID() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.MaintenanceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceStatusPageMods) RandomMaintenanceID(f *faker.Faker) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(_ context.Context, o *MaintenanceStatusPageTemplate) {
		o.MaintenanceID = func() string {
			return random_string(f)
		}
	})
}

func (m maintenanceStatusPageMods) WithParentsCascading() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		if isDone, _ := maintenanceStatusPageWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = maintenanceStatusPageWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewMaintenanceWithContext(ctx, MaintenanceMods.WithParentsCascading())
			m.WithMaintenance(related).Apply(ctx, o)
		}
		{

			related := o.f.NewStatusPageWithContext(ctx, StatusPageMods.WithParentsCascading())
			m.WithStatusPage(related).Apply(ctx, o)
		}
	})
}

func (m maintenanceStatusPageMods) WithMaintenance(rel *MaintenanceTemplate) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.Maintenance = &maintenanceStatusPageRMaintenanceR{
			o: rel,
		}
	})
}

func (m maintenanceStatusPageMods) WithNewMaintenance(mods ...MaintenanceMod) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		related := o.f.NewMaintenanceWithContext(ctx, mods...)

		m.WithMaintenance(related).Apply(ctx, o)
	})
}

func (m maintenanceStatusPageMods) WithExistingMaintenance(em *models.Maintenance) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.Maintenance = &maintenanceStatusPageRMaintenanceR{
			o: o.f.FromExistingMaintenance(em),
		}
	})
}

func (m maintenanceStatusPageMods) WithoutMaintenance() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.Maintenance = nil
	})
}

func (m maintenanceStatusPageMods) WithStatusPage(rel *StatusPageTemplate) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.StatusPage = &maintenanceStatusPageRStatusPageR{
			o: rel,
		}
	})
}

func (m maintenanceStatusPageMods) WithNewStatusPage(mods ...StatusPageMod) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		related := o.f.NewStatusPageWithContext(ctx, mods...)

		m.WithStatusPage(related).Apply(ctx, o)
	})
}

func (m maintenanceStatusPageMods) WithExistingStatusPage(em *models.StatusPage) MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.StatusPage = &maintenanceStatusPageRStatusPageR{
			o: o.f.FromExistingStatusPage(em),
		}
	})
}

func (m maintenanceStatusPageMods) WithoutStatusPage() MaintenanceStatusPageMod {
	return MaintenanceStatusPageModFunc(func(ctx context.Context, o *MaintenanceStatusPageTemplate) {
		o.r.StatusPage = nil
	})
}
