// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type MaintenanceTimeslotMod interface {
	Apply(context.Context, *MaintenanceTimeslotTemplate)
}

type MaintenanceTimeslotModFunc func(context.Context, *MaintenanceTimeslotTemplate)

func (f MaintenanceTimeslotModFunc) Apply(ctx context.Context, n *MaintenanceTimeslotTemplate) {
	f(ctx, n)
}

type MaintenanceTimeslotModSlice []MaintenanceTimeslotMod

func (mods MaintenanceTimeslotModSlice) Apply(ctx context.Context, n *MaintenanceTimeslotTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MaintenanceTimeslotTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MaintenanceTimeslotTemplate struct {
	ID            func() string
	MaintenanceID func() string
	StartDate     func() time.Time
	EndDate       func() null.Val[time.Time]
	GeneratedNext func() bool

	r maintenanceTimeslotR
	f *Factory

	alreadyPersisted bool
}

type maintenanceTimeslotR struct {
	Maintenance *maintenanceTimeslotRMaintenanceR
}

type maintenanceTimeslotRMaintenanceR struct {
	o *MaintenanceTemplate
}

// Apply mods to the MaintenanceTimeslotTemplate
func (o *MaintenanceTimeslotTemplate) Apply(ctx context.Context, mods ...MaintenanceTimeslotMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MaintenanceTimeslot
// according to the relationships in the template. Nothing is inserted into the db
func (t MaintenanceTimeslotTemplate) setModelRels(o *models.MaintenanceTimeslot) {
	if t.r.Maintenance != nil {
		rel := t.r.Maintenance.o.Build()
		rel.R.MaintenanceTimeslots = append(rel.R.MaintenanceTimeslots, o)
		o.MaintenanceID = rel.ID // h2
		o.R.Maintenance = rel
	}
}

// BuildSetter returns an *models.MaintenanceTimeslotSetter
// this does nothing with the relationship templates
func (o MaintenanceTimeslotTemplate) BuildSetter() *models.MaintenanceTimeslotSetter {
	m := &models.MaintenanceTimeslotSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.MaintenanceID != nil {
		val := o.MaintenanceID()
		m.MaintenanceID = omit.From(val)
	}
	if o.StartDate != nil {
		val := o.StartDate()
		m.StartDate = omit.From(val)
	}
	if o.EndDate != nil {
		val := o.EndDate()
		m.EndDate = omitnull.FromNull(val)
	}
	if o.GeneratedNext != nil {
		val := o.GeneratedNext()
		m.GeneratedNext = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.MaintenanceTimeslotSetter
// this does nothing with the relationship templates
func (o MaintenanceTimeslotTemplate) BuildManySetter(number int) []*models.MaintenanceTimeslotSetter {
	m := make([]*models.MaintenanceTimeslotSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MaintenanceTimeslot
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceTimeslotTemplate.Create
func (o MaintenanceTimeslotTemplate) Build() *models.MaintenanceTimeslot {
	m := &models.MaintenanceTimeslot{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MaintenanceID != nil {
		m.MaintenanceID = o.MaintenanceID()
	}
	if o.StartDate != nil {
		m.StartDate = o.StartDate()
	}
	if o.EndDate != nil {
		m.EndDate = o.EndDate()
	}
	if o.GeneratedNext != nil {
		m.GeneratedNext = o.GeneratedNext()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MaintenanceTimeslotSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MaintenanceTimeslotTemplate.CreateMany
func (o MaintenanceTimeslotTemplate) BuildMany(number int) models.MaintenanceTimeslotSlice {
	m := make(models.MaintenanceTimeslotSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMaintenanceTimeslot(m *models.MaintenanceTimeslotSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.MaintenanceID.IsValue()) {
		val := random_string(nil)
		m.MaintenanceID = omit.From(val)
	}
	if !(m.StartDate.IsValue()) {
		val := random_time_Time(nil)
		m.StartDate = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MaintenanceTimeslot
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MaintenanceTimeslotTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MaintenanceTimeslot) error {
	var err error

	return err
}

// Create builds a maintenanceTimeslot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MaintenanceTimeslotTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MaintenanceTimeslot, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMaintenanceTimeslot(opt)

	if o.r.Maintenance == nil {
		MaintenanceTimeslotMods.WithNewMaintenance().Apply(ctx, o)
	}

	var rel0 *models.Maintenance

	if o.r.Maintenance.o.alreadyPersisted {
		rel0 = o.r.Maintenance.o.Build()
	} else {
		rel0, err = o.r.Maintenance.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.MaintenanceID = omit.From(rel0.ID)

	m, err := models.MaintenanceTimeslots.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Maintenance = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a maintenanceTimeslot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MaintenanceTimeslotTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MaintenanceTimeslot {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a maintenanceTimeslot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MaintenanceTimeslotTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MaintenanceTimeslot {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple maintenanceTimeslots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MaintenanceTimeslotTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MaintenanceTimeslotSlice, error) {
	var err error
	m := make(models.MaintenanceTimeslotSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple maintenanceTimeslots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MaintenanceTimeslotTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MaintenanceTimeslotSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple maintenanceTimeslots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MaintenanceTimeslotTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MaintenanceTimeslotSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MaintenanceTimeslot has methods that act as mods for the MaintenanceTimeslotTemplate
var MaintenanceTimeslotMods maintenanceTimeslotMods

type maintenanceTimeslotMods struct{}

func (m maintenanceTimeslotMods) RandomizeAllColumns(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModSlice{
		MaintenanceTimeslotMods.RandomID(f),
		MaintenanceTimeslotMods.RandomMaintenanceID(f),
		MaintenanceTimeslotMods.RandomStartDate(f),
		MaintenanceTimeslotMods.RandomEndDate(f),
		MaintenanceTimeslotMods.RandomGeneratedNext(f),
	}
}

// Set the model columns to this value
func (m maintenanceTimeslotMods) ID(val string) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceTimeslotMods) IDFunc(f func() string) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m maintenanceTimeslotMods) UnsetID() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceTimeslotMods) RandomID(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceTimeslotMods) MaintenanceID(val string) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.MaintenanceID = func() string { return val }
	})
}

// Set the Column from the function
func (m maintenanceTimeslotMods) MaintenanceIDFunc(f func() string) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.MaintenanceID = f
	})
}

// Clear any values for the column
func (m maintenanceTimeslotMods) UnsetMaintenanceID() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.MaintenanceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceTimeslotMods) RandomMaintenanceID(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.MaintenanceID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceTimeslotMods) StartDate(val time.Time) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.StartDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m maintenanceTimeslotMods) StartDateFunc(f func() time.Time) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.StartDate = f
	})
}

// Clear any values for the column
func (m maintenanceTimeslotMods) UnsetStartDate() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.StartDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceTimeslotMods) RandomStartDate(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.StartDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m maintenanceTimeslotMods) EndDate(val null.Val[time.Time]) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.EndDate = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m maintenanceTimeslotMods) EndDateFunc(f func() null.Val[time.Time]) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.EndDate = f
	})
}

// Clear any values for the column
func (m maintenanceTimeslotMods) UnsetEndDate() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.EndDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m maintenanceTimeslotMods) RandomEndDate(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m maintenanceTimeslotMods) RandomEndDateNotNull(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.EndDate = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m maintenanceTimeslotMods) GeneratedNext(val bool) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.GeneratedNext = func() bool { return val }
	})
}

// Set the Column from the function
func (m maintenanceTimeslotMods) GeneratedNextFunc(f func() bool) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.GeneratedNext = f
	})
}

// Clear any values for the column
func (m maintenanceTimeslotMods) UnsetGeneratedNext() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.GeneratedNext = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m maintenanceTimeslotMods) RandomGeneratedNext(f *faker.Faker) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(_ context.Context, o *MaintenanceTimeslotTemplate) {
		o.GeneratedNext = func() bool {
			return random_bool(f)
		}
	})
}

func (m maintenanceTimeslotMods) WithParentsCascading() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(ctx context.Context, o *MaintenanceTimeslotTemplate) {
		if isDone, _ := maintenanceTimeslotWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = maintenanceTimeslotWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewMaintenanceWithContext(ctx, MaintenanceMods.WithParentsCascading())
			m.WithMaintenance(related).Apply(ctx, o)
		}
	})
}

func (m maintenanceTimeslotMods) WithMaintenance(rel *MaintenanceTemplate) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(ctx context.Context, o *MaintenanceTimeslotTemplate) {
		o.r.Maintenance = &maintenanceTimeslotRMaintenanceR{
			o: rel,
		}
	})
}

func (m maintenanceTimeslotMods) WithNewMaintenance(mods ...MaintenanceMod) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(ctx context.Context, o *MaintenanceTimeslotTemplate) {
		related := o.f.NewMaintenanceWithContext(ctx, mods...)

		m.WithMaintenance(related).Apply(ctx, o)
	})
}

func (m maintenanceTimeslotMods) WithExistingMaintenance(em *models.Maintenance) MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(ctx context.Context, o *MaintenanceTimeslotTemplate) {
		o.r.Maintenance = &maintenanceTimeslotRMaintenanceR{
			o: o.f.FromExistingMaintenance(em),
		}
	})
}

func (m maintenanceTimeslotMods) WithoutMaintenance() MaintenanceTimeslotMod {
	return MaintenanceTimeslotModFunc(func(ctx context.Context, o *MaintenanceTimeslotTemplate) {
		o.r.Maintenance = nil
	})
}
