// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type MonitorGroupMod interface {
	Apply(context.Context, *MonitorGroupTemplate)
}

type MonitorGroupModFunc func(context.Context, *MonitorGroupTemplate)

func (f MonitorGroupModFunc) Apply(ctx context.Context, n *MonitorGroupTemplate) {
	f(ctx, n)
}

type MonitorGroupModSlice []MonitorGroupMod

func (mods MonitorGroupModSlice) Apply(ctx context.Context, n *MonitorGroupTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MonitorGroupTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MonitorGroupTemplate struct {
	ID        func() string
	MonitorID func() string
	GroupID   func() string
	Weight    func() int64
	SendURL   func() bool

	r monitorGroupR
	f *Factory

	alreadyPersisted bool
}

type monitorGroupR struct {
	Group   *monitorGroupRGroupR
	Monitor *monitorGroupRMonitorR
}

type monitorGroupRGroupR struct {
	o *GroupTemplate
}
type monitorGroupRMonitorR struct {
	o *MonitorTemplate
}

// Apply mods to the MonitorGroupTemplate
func (o *MonitorGroupTemplate) Apply(ctx context.Context, mods ...MonitorGroupMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MonitorGroup
// according to the relationships in the template. Nothing is inserted into the db
func (t MonitorGroupTemplate) setModelRels(o *models.MonitorGroup) {
	if t.r.Group != nil {
		rel := t.r.Group.o.Build()
		rel.R.MonitorGroups = append(rel.R.MonitorGroups, o)
		o.GroupID = rel.ID // h2
		o.R.Group = rel
	}

	if t.r.Monitor != nil {
		rel := t.r.Monitor.o.Build()
		rel.R.MonitorGroups = append(rel.R.MonitorGroups, o)
		o.MonitorID = rel.ID // h2
		o.R.Monitor = rel
	}
}

// BuildSetter returns an *models.MonitorGroupSetter
// this does nothing with the relationship templates
func (o MonitorGroupTemplate) BuildSetter() *models.MonitorGroupSetter {
	m := &models.MonitorGroupSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.MonitorID != nil {
		val := o.MonitorID()
		m.MonitorID = omit.From(val)
	}
	if o.GroupID != nil {
		val := o.GroupID()
		m.GroupID = omit.From(val)
	}
	if o.Weight != nil {
		val := o.Weight()
		m.Weight = omit.From(val)
	}
	if o.SendURL != nil {
		val := o.SendURL()
		m.SendURL = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.MonitorGroupSetter
// this does nothing with the relationship templates
func (o MonitorGroupTemplate) BuildManySetter(number int) []*models.MonitorGroupSetter {
	m := make([]*models.MonitorGroupSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MonitorGroup
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MonitorGroupTemplate.Create
func (o MonitorGroupTemplate) Build() *models.MonitorGroup {
	m := &models.MonitorGroup{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MonitorID != nil {
		m.MonitorID = o.MonitorID()
	}
	if o.GroupID != nil {
		m.GroupID = o.GroupID()
	}
	if o.Weight != nil {
		m.Weight = o.Weight()
	}
	if o.SendURL != nil {
		m.SendURL = o.SendURL()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MonitorGroupSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MonitorGroupTemplate.CreateMany
func (o MonitorGroupTemplate) BuildMany(number int) models.MonitorGroupSlice {
	m := make(models.MonitorGroupSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMonitorGroup(m *models.MonitorGroupSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.MonitorID.IsValue()) {
		val := random_string(nil)
		m.MonitorID = omit.From(val)
	}
	if !(m.GroupID.IsValue()) {
		val := random_string(nil)
		m.GroupID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MonitorGroup
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MonitorGroupTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MonitorGroup) error {
	var err error

	return err
}

// Create builds a monitorGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MonitorGroupTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MonitorGroup, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMonitorGroup(opt)

	if o.r.Group == nil {
		MonitorGroupMods.WithNewGroup().Apply(ctx, o)
	}

	var rel0 *models.Group

	if o.r.Group.o.alreadyPersisted {
		rel0 = o.r.Group.o.Build()
	} else {
		rel0, err = o.r.Group.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.GroupID = omit.From(rel0.ID)

	if o.r.Monitor == nil {
		MonitorGroupMods.WithNewMonitor().Apply(ctx, o)
	}

	var rel1 *models.Monitor

	if o.r.Monitor.o.alreadyPersisted {
		rel1 = o.r.Monitor.o.Build()
	} else {
		rel1, err = o.r.Monitor.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.MonitorID = omit.From(rel1.ID)

	m, err := models.MonitorGroups.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Group = rel0
	m.R.Monitor = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a monitorGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MonitorGroupTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MonitorGroup {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a monitorGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MonitorGroupTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MonitorGroup {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple monitorGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MonitorGroupTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MonitorGroupSlice, error) {
	var err error
	m := make(models.MonitorGroupSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple monitorGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MonitorGroupTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MonitorGroupSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple monitorGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MonitorGroupTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MonitorGroupSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MonitorGroup has methods that act as mods for the MonitorGroupTemplate
var MonitorGroupMods monitorGroupMods

type monitorGroupMods struct{}

func (m monitorGroupMods) RandomizeAllColumns(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModSlice{
		MonitorGroupMods.RandomID(f),
		MonitorGroupMods.RandomMonitorID(f),
		MonitorGroupMods.RandomGroupID(f),
		MonitorGroupMods.RandomWeight(f),
		MonitorGroupMods.RandomSendURL(f),
	}
}

// Set the model columns to this value
func (m monitorGroupMods) ID(val string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorGroupMods) IDFunc(f func() string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m monitorGroupMods) UnsetID() MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorGroupMods) RandomID(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorGroupMods) MonitorID(val string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.MonitorID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorGroupMods) MonitorIDFunc(f func() string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.MonitorID = f
	})
}

// Clear any values for the column
func (m monitorGroupMods) UnsetMonitorID() MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.MonitorID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorGroupMods) RandomMonitorID(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.MonitorID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorGroupMods) GroupID(val string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.GroupID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorGroupMods) GroupIDFunc(f func() string) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.GroupID = f
	})
}

// Clear any values for the column
func (m monitorGroupMods) UnsetGroupID() MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.GroupID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorGroupMods) RandomGroupID(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.GroupID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorGroupMods) Weight(val int64) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.Weight = func() int64 { return val }
	})
}

// Set the Column from the function
func (m monitorGroupMods) WeightFunc(f func() int64) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.Weight = f
	})
}

// Clear any values for the column
func (m monitorGroupMods) UnsetWeight() MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.Weight = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorGroupMods) RandomWeight(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.Weight = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m monitorGroupMods) SendURL(val bool) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.SendURL = func() bool { return val }
	})
}

// Set the Column from the function
func (m monitorGroupMods) SendURLFunc(f func() bool) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.SendURL = f
	})
}

// Clear any values for the column
func (m monitorGroupMods) UnsetSendURL() MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.SendURL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorGroupMods) RandomSendURL(f *faker.Faker) MonitorGroupMod {
	return MonitorGroupModFunc(func(_ context.Context, o *MonitorGroupTemplate) {
		o.SendURL = func() bool {
			return random_bool(f)
		}
	})
}

func (m monitorGroupMods) WithParentsCascading() MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		if isDone, _ := monitorGroupWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = monitorGroupWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewGroupWithContext(ctx, GroupMods.WithParentsCascading())
			m.WithGroup(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMonitorWithContext(ctx, MonitorMods.WithParentsCascading())
			m.WithMonitor(related).Apply(ctx, o)
		}
	})
}

func (m monitorGroupMods) WithGroup(rel *GroupTemplate) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Group = &monitorGroupRGroupR{
			o: rel,
		}
	})
}

func (m monitorGroupMods) WithNewGroup(mods ...GroupMod) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		related := o.f.NewGroupWithContext(ctx, mods...)

		m.WithGroup(related).Apply(ctx, o)
	})
}

func (m monitorGroupMods) WithExistingGroup(em *models.Group) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Group = &monitorGroupRGroupR{
			o: o.f.FromExistingGroup(em),
		}
	})
}

func (m monitorGroupMods) WithoutGroup() MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Group = nil
	})
}

func (m monitorGroupMods) WithMonitor(rel *MonitorTemplate) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Monitor = &monitorGroupRMonitorR{
			o: rel,
		}
	})
}

func (m monitorGroupMods) WithNewMonitor(mods ...MonitorMod) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		related := o.f.NewMonitorWithContext(ctx, mods...)

		m.WithMonitor(related).Apply(ctx, o)
	})
}

func (m monitorGroupMods) WithExistingMonitor(em *models.Monitor) MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Monitor = &monitorGroupRMonitorR{
			o: o.f.FromExistingMonitor(em),
		}
	})
}

func (m monitorGroupMods) WithoutMonitor() MonitorGroupMod {
	return MonitorGroupModFunc(func(ctx context.Context, o *MonitorGroupTemplate) {
		o.r.Monitor = nil
	})
}
