// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type MonitorTagMod interface {
	Apply(context.Context, *MonitorTagTemplate)
}

type MonitorTagModFunc func(context.Context, *MonitorTagTemplate)

func (f MonitorTagModFunc) Apply(ctx context.Context, n *MonitorTagTemplate) {
	f(ctx, n)
}

type MonitorTagModSlice []MonitorTagMod

func (mods MonitorTagModSlice) Apply(ctx context.Context, n *MonitorTagTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MonitorTagTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MonitorTagTemplate struct {
	ID        func() string
	MonitorID func() string
	TagID     func() string
	Value     func() null.Val[string]

	r monitorTagR
	f *Factory

	alreadyPersisted bool
}

type monitorTagR struct {
	Tag     *monitorTagRTagR
	Monitor *monitorTagRMonitorR
}

type monitorTagRTagR struct {
	o *TagTemplate
}
type monitorTagRMonitorR struct {
	o *MonitorTemplate
}

// Apply mods to the MonitorTagTemplate
func (o *MonitorTagTemplate) Apply(ctx context.Context, mods ...MonitorTagMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MonitorTag
// according to the relationships in the template. Nothing is inserted into the db
func (t MonitorTagTemplate) setModelRels(o *models.MonitorTag) {
	if t.r.Tag != nil {
		rel := t.r.Tag.o.Build()
		rel.R.MonitorTags = append(rel.R.MonitorTags, o)
		o.TagID = rel.ID // h2
		o.R.Tag = rel
	}

	if t.r.Monitor != nil {
		rel := t.r.Monitor.o.Build()
		rel.R.MonitorTags = append(rel.R.MonitorTags, o)
		o.MonitorID = rel.ID // h2
		o.R.Monitor = rel
	}
}

// BuildSetter returns an *models.MonitorTagSetter
// this does nothing with the relationship templates
func (o MonitorTagTemplate) BuildSetter() *models.MonitorTagSetter {
	m := &models.MonitorTagSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.MonitorID != nil {
		val := o.MonitorID()
		m.MonitorID = omit.From(val)
	}
	if o.TagID != nil {
		val := o.TagID()
		m.TagID = omit.From(val)
	}
	if o.Value != nil {
		val := o.Value()
		m.Value = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MonitorTagSetter
// this does nothing with the relationship templates
func (o MonitorTagTemplate) BuildManySetter(number int) []*models.MonitorTagSetter {
	m := make([]*models.MonitorTagSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MonitorTag
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MonitorTagTemplate.Create
func (o MonitorTagTemplate) Build() *models.MonitorTag {
	m := &models.MonitorTag{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MonitorID != nil {
		m.MonitorID = o.MonitorID()
	}
	if o.TagID != nil {
		m.TagID = o.TagID()
	}
	if o.Value != nil {
		m.Value = o.Value()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MonitorTagSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MonitorTagTemplate.CreateMany
func (o MonitorTagTemplate) BuildMany(number int) models.MonitorTagSlice {
	m := make(models.MonitorTagSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMonitorTag(m *models.MonitorTagSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.MonitorID.IsValue()) {
		val := random_string(nil)
		m.MonitorID = omit.From(val)
	}
	if !(m.TagID.IsValue()) {
		val := random_string(nil)
		m.TagID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MonitorTag
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MonitorTagTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MonitorTag) error {
	var err error

	return err
}

// Create builds a monitorTag and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MonitorTagTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MonitorTag, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMonitorTag(opt)

	if o.r.Tag == nil {
		MonitorTagMods.WithNewTag().Apply(ctx, o)
	}

	var rel0 *models.Tag

	if o.r.Tag.o.alreadyPersisted {
		rel0 = o.r.Tag.o.Build()
	} else {
		rel0, err = o.r.Tag.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.TagID = omit.From(rel0.ID)

	if o.r.Monitor == nil {
		MonitorTagMods.WithNewMonitor().Apply(ctx, o)
	}

	var rel1 *models.Monitor

	if o.r.Monitor.o.alreadyPersisted {
		rel1 = o.r.Monitor.o.Build()
	} else {
		rel1, err = o.r.Monitor.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.MonitorID = omit.From(rel1.ID)

	m, err := models.MonitorTags.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Tag = rel0
	m.R.Monitor = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a monitorTag and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MonitorTagTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MonitorTag {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a monitorTag and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MonitorTagTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MonitorTag {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple monitorTags and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MonitorTagTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MonitorTagSlice, error) {
	var err error
	m := make(models.MonitorTagSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple monitorTags and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MonitorTagTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MonitorTagSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple monitorTags and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MonitorTagTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MonitorTagSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MonitorTag has methods that act as mods for the MonitorTagTemplate
var MonitorTagMods monitorTagMods

type monitorTagMods struct{}

func (m monitorTagMods) RandomizeAllColumns(f *faker.Faker) MonitorTagMod {
	return MonitorTagModSlice{
		MonitorTagMods.RandomID(f),
		MonitorTagMods.RandomMonitorID(f),
		MonitorTagMods.RandomTagID(f),
		MonitorTagMods.RandomValue(f),
	}
}

// Set the model columns to this value
func (m monitorTagMods) ID(val string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorTagMods) IDFunc(f func() string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m monitorTagMods) UnsetID() MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorTagMods) RandomID(f *faker.Faker) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorTagMods) MonitorID(val string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.MonitorID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorTagMods) MonitorIDFunc(f func() string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.MonitorID = f
	})
}

// Clear any values for the column
func (m monitorTagMods) UnsetMonitorID() MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.MonitorID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorTagMods) RandomMonitorID(f *faker.Faker) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.MonitorID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorTagMods) TagID(val string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.TagID = func() string { return val }
	})
}

// Set the Column from the function
func (m monitorTagMods) TagIDFunc(f func() string) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.TagID = f
	})
}

// Clear any values for the column
func (m monitorTagMods) UnsetTagID() MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.TagID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m monitorTagMods) RandomTagID(f *faker.Faker) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.TagID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m monitorTagMods) Value(val null.Val[string]) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.Value = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m monitorTagMods) ValueFunc(f func() null.Val[string]) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.Value = f
	})
}

// Clear any values for the column
func (m monitorTagMods) UnsetValue() MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.Value = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m monitorTagMods) RandomValue(f *faker.Faker) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.Value = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m monitorTagMods) RandomValueNotNull(f *faker.Faker) MonitorTagMod {
	return MonitorTagModFunc(func(_ context.Context, o *MonitorTagTemplate) {
		o.Value = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m monitorTagMods) WithParentsCascading() MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		if isDone, _ := monitorTagWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = monitorTagWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewTagWithContext(ctx, TagMods.WithParentsCascading())
			m.WithTag(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMonitorWithContext(ctx, MonitorMods.WithParentsCascading())
			m.WithMonitor(related).Apply(ctx, o)
		}
	})
}

func (m monitorTagMods) WithTag(rel *TagTemplate) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Tag = &monitorTagRTagR{
			o: rel,
		}
	})
}

func (m monitorTagMods) WithNewTag(mods ...TagMod) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		related := o.f.NewTagWithContext(ctx, mods...)

		m.WithTag(related).Apply(ctx, o)
	})
}

func (m monitorTagMods) WithExistingTag(em *models.Tag) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Tag = &monitorTagRTagR{
			o: o.f.FromExistingTag(em),
		}
	})
}

func (m monitorTagMods) WithoutTag() MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Tag = nil
	})
}

func (m monitorTagMods) WithMonitor(rel *MonitorTemplate) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Monitor = &monitorTagRMonitorR{
			o: rel,
		}
	})
}

func (m monitorTagMods) WithNewMonitor(mods ...MonitorMod) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		related := o.f.NewMonitorWithContext(ctx, mods...)

		m.WithMonitor(related).Apply(ctx, o)
	})
}

func (m monitorTagMods) WithExistingMonitor(em *models.Monitor) MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Monitor = &monitorTagRMonitorR{
			o: o.f.FromExistingMonitor(em),
		}
	})
}

func (m monitorTagMods) WithoutMonitor() MonitorTagMod {
	return MonitorTagModFunc(func(ctx context.Context, o *MonitorTagTemplate) {
		o.r.Monitor = nil
	})
}
