// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type SettingMod interface {
	Apply(context.Context, *SettingTemplate)
}

type SettingModFunc func(context.Context, *SettingTemplate)

func (f SettingModFunc) Apply(ctx context.Context, n *SettingTemplate) {
	f(ctx, n)
}

type SettingModSlice []SettingMod

func (mods SettingModSlice) Apply(ctx context.Context, n *SettingTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SettingTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SettingTemplate struct {
	ID    func() string
	Key   func() string
	Value func() null.Val[string]
	Type  func() null.Val[string]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the SettingTemplate
func (o *SettingTemplate) Apply(ctx context.Context, mods ...SettingMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Setting
// according to the relationships in the template. Nothing is inserted into the db
func (t SettingTemplate) setModelRels(o *models.Setting) {}

// BuildSetter returns an *models.SettingSetter
// this does nothing with the relationship templates
func (o SettingTemplate) BuildSetter() *models.SettingSetter {
	m := &models.SettingSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Key != nil {
		val := o.Key()
		m.Key = omit.From(val)
	}
	if o.Value != nil {
		val := o.Value()
		m.Value = omitnull.FromNull(val)
	}
	if o.Type != nil {
		val := o.Type()
		m.Type = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.SettingSetter
// this does nothing with the relationship templates
func (o SettingTemplate) BuildManySetter(number int) []*models.SettingSetter {
	m := make([]*models.SettingSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Setting
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SettingTemplate.Create
func (o SettingTemplate) Build() *models.Setting {
	m := &models.Setting{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Key != nil {
		m.Key = o.Key()
	}
	if o.Value != nil {
		m.Value = o.Value()
	}
	if o.Type != nil {
		m.Type = o.Type()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SettingSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SettingTemplate.CreateMany
func (o SettingTemplate) BuildMany(number int) models.SettingSlice {
	m := make(models.SettingSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSetting(m *models.SettingSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.Key.IsValue()) {
		val := random_string(nil)
		m.Key = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Setting
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SettingTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Setting) error {
	var err error

	return err
}

// Create builds a setting and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SettingTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Setting, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSetting(opt)

	m, err := models.Settings.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a setting and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SettingTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Setting {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a setting and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SettingTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Setting {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple settings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SettingTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SettingSlice, error) {
	var err error
	m := make(models.SettingSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple settings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SettingTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SettingSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple settings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SettingTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SettingSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Setting has methods that act as mods for the SettingTemplate
var SettingMods settingMods

type settingMods struct{}

func (m settingMods) RandomizeAllColumns(f *faker.Faker) SettingMod {
	return SettingModSlice{
		SettingMods.RandomID(f),
		SettingMods.RandomKey(f),
		SettingMods.RandomValue(f),
		SettingMods.RandomType(f),
	}
}

// Set the model columns to this value
func (m settingMods) ID(val string) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m settingMods) IDFunc(f func() string) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m settingMods) UnsetID() SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m settingMods) RandomID(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m settingMods) Key(val string) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Key = func() string { return val }
	})
}

// Set the Column from the function
func (m settingMods) KeyFunc(f func() string) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Key = f
	})
}

// Clear any values for the column
func (m settingMods) UnsetKey() SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Key = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m settingMods) RandomKey(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Key = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m settingMods) Value(val null.Val[string]) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Value = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m settingMods) ValueFunc(f func() null.Val[string]) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Value = f
	})
}

// Clear any values for the column
func (m settingMods) UnsetValue() SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Value = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m settingMods) RandomValue(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Value = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m settingMods) RandomValueNotNull(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Value = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m settingMods) Type(val null.Val[string]) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Type = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m settingMods) TypeFunc(f func() null.Val[string]) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Type = f
	})
}

// Clear any values for the column
func (m settingMods) UnsetType() SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Type = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m settingMods) RandomType(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Type = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m settingMods) RandomTypeNotNull(f *faker.Faker) SettingMod {
	return SettingModFunc(func(_ context.Context, o *SettingTemplate) {
		o.Type = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m settingMods) WithParentsCascading() SettingMod {
	return SettingModFunc(func(ctx context.Context, o *SettingTemplate) {
		if isDone, _ := settingWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = settingWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
