// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/koblas/besops/models"
	"github.com/stephenafamo/bob"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID             func() string
	Username       func() string
	Password       func() string
	Active         func() bool
	Timezone       func() null.Val[string]
	TwofaSecret    func() null.Val[string]
	TwofaStatus    func() bool
	TwofaLastToken func() null.Val[string]
	CreatedDate    func() time.Time

	r userR
	f *Factory

	alreadyPersisted bool
}

type userR struct {
	APIKeys        []*userRAPIKeysR
	Maintenances   []*userRMaintenancesR
	Monitors       []*userRMonitorsR
	Notifications  []*userRNotificationsR
	Proxies        []*userRProxiesR
	RemoteBrowsers []*userRRemoteBrowsersR
}

type userRAPIKeysR struct {
	number int
	o      *APIKeyTemplate
}
type userRMaintenancesR struct {
	number int
	o      *MaintenanceTemplate
}
type userRMonitorsR struct {
	number int
	o      *MonitorTemplate
}
type userRNotificationsR struct {
	number int
	o      *NotificationTemplate
}
type userRProxiesR struct {
	number int
	o      *ProxyTemplate
}
type userRRemoteBrowsersR struct {
	number int
	o      *RemoteBrowserTemplate
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {
	if t.r.APIKeys != nil {
		rel := models.APIKeySlice{}
		for _, r := range t.r.APIKeys {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.APIKeys = rel
	}

	if t.r.Maintenances != nil {
		rel := models.MaintenanceSlice{}
		for _, r := range t.r.Maintenances {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Maintenances = rel
	}

	if t.r.Monitors != nil {
		rel := models.MonitorSlice{}
		for _, r := range t.r.Monitors {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Monitors = rel
	}

	if t.r.Notifications != nil {
		rel := models.NotificationSlice{}
		for _, r := range t.r.Notifications {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Notifications = rel
	}

	if t.r.Proxies != nil {
		rel := models.ProxySlice{}
		for _, r := range t.r.Proxies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Proxies = rel
	}

	if t.r.RemoteBrowsers != nil {
		rel := models.RemoteBrowserSlice{}
		for _, r := range t.r.RemoteBrowsers {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.RemoteBrowsers = rel
	}
}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Username != nil {
		val := o.Username()
		m.Username = omit.From(val)
	}
	if o.Password != nil {
		val := o.Password()
		m.Password = omit.From(val)
	}
	if o.Active != nil {
		val := o.Active()
		m.Active = omit.From(val)
	}
	if o.Timezone != nil {
		val := o.Timezone()
		m.Timezone = omitnull.FromNull(val)
	}
	if o.TwofaSecret != nil {
		val := o.TwofaSecret()
		m.TwofaSecret = omitnull.FromNull(val)
	}
	if o.TwofaStatus != nil {
		val := o.TwofaStatus()
		m.TwofaStatus = omit.From(val)
	}
	if o.TwofaLastToken != nil {
		val := o.TwofaLastToken()
		m.TwofaLastToken = omitnull.FromNull(val)
	}
	if o.CreatedDate != nil {
		val := o.CreatedDate()
		m.CreatedDate = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Username != nil {
		m.Username = o.Username()
	}
	if o.Password != nil {
		m.Password = o.Password()
	}
	if o.Active != nil {
		m.Active = o.Active()
	}
	if o.Timezone != nil {
		m.Timezone = o.Timezone()
	}
	if o.TwofaSecret != nil {
		m.TwofaSecret = o.TwofaSecret()
	}
	if o.TwofaStatus != nil {
		m.TwofaStatus = o.TwofaStatus()
	}
	if o.TwofaLastToken != nil {
		m.TwofaLastToken = o.TwofaLastToken()
	}
	if o.CreatedDate != nil {
		m.CreatedDate = o.CreatedDate()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil)
		m.ID = omit.From(val)
	}
	if !(m.Username.IsValue()) {
		val := random_string(nil)
		m.Username = omit.From(val)
	}
	if !(m.Password.IsValue()) {
		val := random_string(nil)
		m.Password = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	isAPIKeysDone, _ := userRelAPIKeysCtx.Value(ctx)
	if !isAPIKeysDone && o.r.APIKeys != nil {
		ctx = userRelAPIKeysCtx.WithValue(ctx, true)
		for _, r := range o.r.APIKeys {
			if r.o.alreadyPersisted {
				m.R.APIKeys = append(m.R.APIKeys, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachAPIKeys(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isMaintenancesDone, _ := userRelMaintenancesCtx.Value(ctx)
	if !isMaintenancesDone && o.r.Maintenances != nil {
		ctx = userRelMaintenancesCtx.WithValue(ctx, true)
		for _, r := range o.r.Maintenances {
			if r.o.alreadyPersisted {
				m.R.Maintenances = append(m.R.Maintenances, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMaintenances(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isMonitorsDone, _ := userRelMonitorsCtx.Value(ctx)
	if !isMonitorsDone && o.r.Monitors != nil {
		ctx = userRelMonitorsCtx.WithValue(ctx, true)
		for _, r := range o.r.Monitors {
			if r.o.alreadyPersisted {
				m.R.Monitors = append(m.R.Monitors, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMonitors(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isNotificationsDone, _ := userRelNotificationsCtx.Value(ctx)
	if !isNotificationsDone && o.r.Notifications != nil {
		ctx = userRelNotificationsCtx.WithValue(ctx, true)
		for _, r := range o.r.Notifications {
			if r.o.alreadyPersisted {
				m.R.Notifications = append(m.R.Notifications, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachNotifications(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isProxiesDone, _ := userRelProxiesCtx.Value(ctx)
	if !isProxiesDone && o.r.Proxies != nil {
		ctx = userRelProxiesCtx.WithValue(ctx, true)
		for _, r := range o.r.Proxies {
			if r.o.alreadyPersisted {
				m.R.Proxies = append(m.R.Proxies, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachProxies(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	isRemoteBrowsersDone, _ := userRelRemoteBrowsersCtx.Value(ctx)
	if !isRemoteBrowsersDone && o.r.RemoteBrowsers != nil {
		ctx = userRelRemoteBrowsersCtx.WithValue(ctx, true)
		for _, r := range o.r.RemoteBrowsers {
			if r.o.alreadyPersisted {
				m.R.RemoteBrowsers = append(m.R.RemoteBrowsers, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachRemoteBrowsers(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomUsername(f),
		UserMods.RandomPassword(f),
		UserMods.RandomActive(f),
		UserMods.RandomTimezone(f),
		UserMods.RandomTwofaSecret(f),
		UserMods.RandomTwofaStatus(f),
		UserMods.RandomTwofaLastToken(f),
		UserMods.RandomCreatedDate(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Username(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) UsernameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUsername() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUsername(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Password(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) PasswordFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPassword() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomPassword(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Active(val bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Active = func() bool { return val }
	})
}

// Set the Column from the function
func (m userMods) ActiveFunc(f func() bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Active = f
	})
}

// Clear any values for the column
func (m userMods) UnsetActive() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Active = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomActive(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Active = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Timezone(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Timezone = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) TimezoneFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Timezone = f
	})
}

// Clear any values for the column
func (m userMods) UnsetTimezone() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Timezone = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomTimezone(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Timezone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomTimezoneNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Timezone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) TwofaSecret(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaSecret = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) TwofaSecretFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaSecret = f
	})
}

// Clear any values for the column
func (m userMods) UnsetTwofaSecret() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaSecret = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomTwofaSecret(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaSecret = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomTwofaSecretNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaSecret = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) TwofaStatus(val bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaStatus = func() bool { return val }
	})
}

// Set the Column from the function
func (m userMods) TwofaStatusFunc(f func() bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaStatus = f
	})
}

// Clear any values for the column
func (m userMods) UnsetTwofaStatus() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaStatus = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomTwofaStatus(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaStatus = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) TwofaLastToken(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaLastToken = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) TwofaLastTokenFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaLastToken = f
	})
}

// Clear any values for the column
func (m userMods) UnsetTwofaLastToken() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaLastToken = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomTwofaLastToken(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaLastToken = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomTwofaLastTokenNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.TwofaLastToken = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedDate(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedDateFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedDate = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedDate() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedDate(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m userMods) WithAPIKeys(number int, related *APIKeyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.APIKeys = []*userRAPIKeysR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewAPIKeys(number int, mods ...APIKeyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAPIKeyWithContext(ctx, mods...)
		m.WithAPIKeys(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddAPIKeys(number int, related *APIKeyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.APIKeys = append(o.r.APIKeys, &userRAPIKeysR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewAPIKeys(number int, mods ...APIKeyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAPIKeyWithContext(ctx, mods...)
		m.AddAPIKeys(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingAPIKeys(existingModels ...*models.APIKey) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.APIKeys = append(o.r.APIKeys, &userRAPIKeysR{
				o: o.f.FromExistingAPIKey(em),
			})
		}
	})
}

func (m userMods) WithoutAPIKeys() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.APIKeys = nil
	})
}

func (m userMods) WithMaintenances(number int, related *MaintenanceTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Maintenances = []*userRMaintenancesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewMaintenances(number int, mods ...MaintenanceMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewMaintenanceWithContext(ctx, mods...)
		m.WithMaintenances(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddMaintenances(number int, related *MaintenanceTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Maintenances = append(o.r.Maintenances, &userRMaintenancesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewMaintenances(number int, mods ...MaintenanceMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewMaintenanceWithContext(ctx, mods...)
		m.AddMaintenances(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingMaintenances(existingModels ...*models.Maintenance) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Maintenances = append(o.r.Maintenances, &userRMaintenancesR{
				o: o.f.FromExistingMaintenance(em),
			})
		}
	})
}

func (m userMods) WithoutMaintenances() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Maintenances = nil
	})
}

func (m userMods) WithMonitors(number int, related *MonitorTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Monitors = []*userRMonitorsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewMonitors(number int, mods ...MonitorMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewMonitorWithContext(ctx, mods...)
		m.WithMonitors(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddMonitors(number int, related *MonitorTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Monitors = append(o.r.Monitors, &userRMonitorsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewMonitors(number int, mods ...MonitorMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewMonitorWithContext(ctx, mods...)
		m.AddMonitors(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingMonitors(existingModels ...*models.Monitor) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Monitors = append(o.r.Monitors, &userRMonitorsR{
				o: o.f.FromExistingMonitor(em),
			})
		}
	})
}

func (m userMods) WithoutMonitors() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Monitors = nil
	})
}

func (m userMods) WithNotifications(number int, related *NotificationTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Notifications = []*userRNotificationsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewNotifications(number int, mods ...NotificationMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewNotificationWithContext(ctx, mods...)
		m.WithNotifications(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddNotifications(number int, related *NotificationTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Notifications = append(o.r.Notifications, &userRNotificationsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewNotifications(number int, mods ...NotificationMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewNotificationWithContext(ctx, mods...)
		m.AddNotifications(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingNotifications(existingModels ...*models.Notification) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Notifications = append(o.r.Notifications, &userRNotificationsR{
				o: o.f.FromExistingNotification(em),
			})
		}
	})
}

func (m userMods) WithoutNotifications() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Notifications = nil
	})
}

func (m userMods) WithProxies(number int, related *ProxyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Proxies = []*userRProxiesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewProxies(number int, mods ...ProxyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewProxyWithContext(ctx, mods...)
		m.WithProxies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddProxies(number int, related *ProxyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Proxies = append(o.r.Proxies, &userRProxiesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewProxies(number int, mods ...ProxyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewProxyWithContext(ctx, mods...)
		m.AddProxies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingProxies(existingModels ...*models.Proxy) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Proxies = append(o.r.Proxies, &userRProxiesR{
				o: o.f.FromExistingProxy(em),
			})
		}
	})
}

func (m userMods) WithoutProxies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Proxies = nil
	})
}

func (m userMods) WithRemoteBrowsers(number int, related *RemoteBrowserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RemoteBrowsers = []*userRRemoteBrowsersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewRemoteBrowsers(number int, mods ...RemoteBrowserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewRemoteBrowserWithContext(ctx, mods...)
		m.WithRemoteBrowsers(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddRemoteBrowsers(number int, related *RemoteBrowserTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RemoteBrowsers = append(o.r.RemoteBrowsers, &userRRemoteBrowsersR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewRemoteBrowsers(number int, mods ...RemoteBrowserMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewRemoteBrowserWithContext(ctx, mods...)
		m.AddRemoteBrowsers(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingRemoteBrowsers(existingModels ...*models.RemoteBrowser) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.RemoteBrowsers = append(o.r.RemoteBrowsers, &userRRemoteBrowsersR{
				o: o.f.FromExistingRemoteBrowser(em),
			})
		}
	})
}

func (m userMods) WithoutRemoteBrowsers() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RemoteBrowsers = nil
	})
}
