// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MaintenanceTimeslotErrors = &maintenanceTimeslotErrors{
	ErrUniquePkMainMaintenanceTimeslot: &UniqueConstraintError{
		schema:  "",
		table:   "maintenance_timeslot",
		columns: []string{"id"},
		s:       "pk_main_maintenance_timeslot",
	},
}

type maintenanceTimeslotErrors struct {
	ErrUniquePkMainMaintenanceTimeslot *UniqueConstraintError
}
