// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MonitorMaintenanceErrors = &monitorMaintenanceErrors{
	ErrUniquePkMainMonitorMaintenance: &UniqueConstraintError{
		schema:  "",
		table:   "monitor_maintenance",
		columns: []string{"id"},
		s:       "pk_main_monitor_maintenance",
	},
}

type monitorMaintenanceErrors struct {
	ErrUniquePkMainMonitorMaintenance *UniqueConstraintError
}
