// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MonitorGroupErrors = &monitorGroupErrors{
	ErrUniquePkMainMonitorGroup: &UniqueConstraintError{
		schema:  "",
		table:   "monitor_group",
		columns: []string{"id"},
		s:       "pk_main_monitor_group",
	},
}

type monitorGroupErrors struct {
	ErrUniquePkMainMonitorGroup *UniqueConstraintError
}
