// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var StatDailyErrors = &statDailyErrors{
	ErrUniquePkMainStatDaily: &UniqueConstraintError{
		schema:  "",
		table:   "stat_daily",
		columns: []string{"id"},
		s:       "pk_main_stat_daily",
	},
}

type statDailyErrors struct {
	ErrUniquePkMainStatDaily *UniqueConstraintError
}
