// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type APIKey runs hooks after queries
var _ bob.HookableType = &APIKey{}

// Make sure the type DockerHost runs hooks after queries
var _ bob.HookableType = &DockerHost{}

// Make sure the type DomainExpiry runs hooks after queries
var _ bob.HookableType = &DomainExpiry{}

// Make sure the type Group runs hooks after queries
var _ bob.HookableType = &Group{}

// Make sure the type Heartbeat runs hooks after queries
var _ bob.HookableType = &Heartbeat{}

// Make sure the type Incident runs hooks after queries
var _ bob.HookableType = &Incident{}

// Make sure the type Maintenance runs hooks after queries
var _ bob.HookableType = &Maintenance{}

// Make sure the type MaintenanceStatusPage runs hooks after queries
var _ bob.HookableType = &MaintenanceStatusPage{}

// Make sure the type MaintenanceTimeslot runs hooks after queries
var _ bob.HookableType = &MaintenanceTimeslot{}

// Make sure the type Monitor runs hooks after queries
var _ bob.HookableType = &Monitor{}

// Make sure the type MonitorGroup runs hooks after queries
var _ bob.HookableType = &MonitorGroup{}

// Make sure the type MonitorMaintenance runs hooks after queries
var _ bob.HookableType = &MonitorMaintenance{}

// Make sure the type MonitorNotification runs hooks after queries
var _ bob.HookableType = &MonitorNotification{}

// Make sure the type MonitorTag runs hooks after queries
var _ bob.HookableType = &MonitorTag{}

// Make sure the type MonitorTLSInfo runs hooks after queries
var _ bob.HookableType = &MonitorTLSInfo{}

// Make sure the type Notification runs hooks after queries
var _ bob.HookableType = &Notification{}

// Make sure the type NotificationSentHistory runs hooks after queries
var _ bob.HookableType = &NotificationSentHistory{}

// Make sure the type Proxy runs hooks after queries
var _ bob.HookableType = &Proxy{}

// Make sure the type RemoteBrowser runs hooks after queries
var _ bob.HookableType = &RemoteBrowser{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type Setting runs hooks after queries
var _ bob.HookableType = &Setting{}

// Make sure the type StatDaily runs hooks after queries
var _ bob.HookableType = &StatDaily{}

// Make sure the type StatHourly runs hooks after queries
var _ bob.HookableType = &StatHourly{}

// Make sure the type StatMinutely runs hooks after queries
var _ bob.HookableType = &StatMinutely{}

// Make sure the type StatusPage runs hooks after queries
var _ bob.HookableType = &StatusPage{}

// Make sure the type StatusPageCname runs hooks after queries
var _ bob.HookableType = &StatusPageCname{}

// Make sure the type Tag runs hooks after queries
var _ bob.HookableType = &Tag{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
