// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/orm"
)

var Preload = getPreloaders()

type preloaders struct {
	APIKey                  apiKeyPreloader
	Group                   groupPreloader
	Heartbeat               heartbeatPreloader
	Incident                incidentPreloader
	Maintenance             maintenancePreloader
	MaintenanceStatusPage   maintenanceStatusPagePreloader
	MaintenanceTimeslot     maintenanceTimeslotPreloader
	Monitor                 monitorPreloader
	MonitorGroup            monitorGroupPreloader
	MonitorMaintenance      monitorMaintenancePreloader
	MonitorNotification     monitorNotificationPreloader
	MonitorTag              monitorTagPreloader
	MonitorTLSInfo          monitorTLSInfoPreloader
	Notification            notificationPreloader
	NotificationSentHistory notificationSentHistoryPreloader
	Proxy                   proxyPreloader
	RemoteBrowser           remoteBrowserPreloader
	StatDaily               statDailyPreloader
	StatHourly              statHourlyPreloader
	StatMinutely            statMinutelyPreloader
	StatusPage              statusPagePreloader
	StatusPageCname         statusPageCnamePreloader
	Tag                     tagPreloader
	User                    userPreloader
}

func getPreloaders() preloaders {
	return preloaders{
		APIKey:                  buildAPIKeyPreloader(),
		Group:                   buildGroupPreloader(),
		Heartbeat:               buildHeartbeatPreloader(),
		Incident:                buildIncidentPreloader(),
		Maintenance:             buildMaintenancePreloader(),
		MaintenanceStatusPage:   buildMaintenanceStatusPagePreloader(),
		MaintenanceTimeslot:     buildMaintenanceTimeslotPreloader(),
		Monitor:                 buildMonitorPreloader(),
		MonitorGroup:            buildMonitorGroupPreloader(),
		MonitorMaintenance:      buildMonitorMaintenancePreloader(),
		MonitorNotification:     buildMonitorNotificationPreloader(),
		MonitorTag:              buildMonitorTagPreloader(),
		MonitorTLSInfo:          buildMonitorTLSInfoPreloader(),
		Notification:            buildNotificationPreloader(),
		NotificationSentHistory: buildNotificationSentHistoryPreloader(),
		Proxy:                   buildProxyPreloader(),
		RemoteBrowser:           buildRemoteBrowserPreloader(),
		StatDaily:               buildStatDailyPreloader(),
		StatHourly:              buildStatHourlyPreloader(),
		StatMinutely:            buildStatMinutelyPreloader(),
		StatusPage:              buildStatusPagePreloader(),
		StatusPageCname:         buildStatusPageCnamePreloader(),
		Tag:                     buildTagPreloader(),
		User:                    buildUserPreloader(),
	}
}

var (
	SelectThenLoad = getThenLoaders[*dialect.SelectQuery]()
	InsertThenLoad = getThenLoaders[*dialect.InsertQuery]()
	UpdateThenLoad = getThenLoaders[*dialect.UpdateQuery]()
)

type thenLoaders[Q orm.Loadable] struct {
	APIKey                  apiKeyThenLoader[Q]
	Group                   groupThenLoader[Q]
	Heartbeat               heartbeatThenLoader[Q]
	Incident                incidentThenLoader[Q]
	Maintenance             maintenanceThenLoader[Q]
	MaintenanceStatusPage   maintenanceStatusPageThenLoader[Q]
	MaintenanceTimeslot     maintenanceTimeslotThenLoader[Q]
	Monitor                 monitorThenLoader[Q]
	MonitorGroup            monitorGroupThenLoader[Q]
	MonitorMaintenance      monitorMaintenanceThenLoader[Q]
	MonitorNotification     monitorNotificationThenLoader[Q]
	MonitorTag              monitorTagThenLoader[Q]
	MonitorTLSInfo          monitorTLSInfoThenLoader[Q]
	Notification            notificationThenLoader[Q]
	NotificationSentHistory notificationSentHistoryThenLoader[Q]
	Proxy                   proxyThenLoader[Q]
	RemoteBrowser           remoteBrowserThenLoader[Q]
	StatDaily               statDailyThenLoader[Q]
	StatHourly              statHourlyThenLoader[Q]
	StatMinutely            statMinutelyThenLoader[Q]
	StatusPage              statusPageThenLoader[Q]
	StatusPageCname         statusPageCnameThenLoader[Q]
	Tag                     tagThenLoader[Q]
	User                    userThenLoader[Q]
}

func getThenLoaders[Q orm.Loadable]() thenLoaders[Q] {
	return thenLoaders[Q]{
		APIKey:                  buildAPIKeyThenLoader[Q](),
		Group:                   buildGroupThenLoader[Q](),
		Heartbeat:               buildHeartbeatThenLoader[Q](),
		Incident:                buildIncidentThenLoader[Q](),
		Maintenance:             buildMaintenanceThenLoader[Q](),
		MaintenanceStatusPage:   buildMaintenanceStatusPageThenLoader[Q](),
		MaintenanceTimeslot:     buildMaintenanceTimeslotThenLoader[Q](),
		Monitor:                 buildMonitorThenLoader[Q](),
		MonitorGroup:            buildMonitorGroupThenLoader[Q](),
		MonitorMaintenance:      buildMonitorMaintenanceThenLoader[Q](),
		MonitorNotification:     buildMonitorNotificationThenLoader[Q](),
		MonitorTag:              buildMonitorTagThenLoader[Q](),
		MonitorTLSInfo:          buildMonitorTLSInfoThenLoader[Q](),
		Notification:            buildNotificationThenLoader[Q](),
		NotificationSentHistory: buildNotificationSentHistoryThenLoader[Q](),
		Proxy:                   buildProxyThenLoader[Q](),
		RemoteBrowser:           buildRemoteBrowserThenLoader[Q](),
		StatDaily:               buildStatDailyThenLoader[Q](),
		StatHourly:              buildStatHourlyThenLoader[Q](),
		StatMinutely:            buildStatMinutelyThenLoader[Q](),
		StatusPage:              buildStatusPageThenLoader[Q](),
		StatusPageCname:         buildStatusPageCnameThenLoader[Q](),
		Tag:                     buildTagThenLoader[Q](),
		User:                    buildUserThenLoader[Q](),
	}
}

func thenLoadBuilder[Q orm.Loadable, T any](name string, f func(context.Context, bob.Executor, T, ...bob.Mod[*dialect.SelectQuery]) error) func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
	return func(queryMods ...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
		return func(ctx context.Context, exec bob.Executor, retrieved any) error {
			loader, isLoader := retrieved.(T)
			if !isLoader {
				return fmt.Errorf("object %T cannot load %q", retrieved, name)
			}

			err := f(ctx, exec, loader, queryMods...)

			// Don't cause an issue due to missing relationships
			if errors.Is(err, sql.ErrNoRows) {
				return nil
			}

			return err
		}
	}
}
