// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"hash/maphash"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectJoins = getJoins[*dialect.SelectQuery]
	UpdateJoins = getJoins[*dialect.UpdateQuery]
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	APIKeys                   joinSet[apiKeyJoins[Q]]
	DockerHosts               joinSet[dockerHostJoins[Q]]
	Groups                    joinSet[groupJoins[Q]]
	Heartbeats                joinSet[heartbeatJoins[Q]]
	Incidents                 joinSet[incidentJoins[Q]]
	Maintenances              joinSet[maintenanceJoins[Q]]
	MaintenanceStatusPages    joinSet[maintenanceStatusPageJoins[Q]]
	MaintenanceTimeslots      joinSet[maintenanceTimeslotJoins[Q]]
	Monitors                  joinSet[monitorJoins[Q]]
	MonitorGroups             joinSet[monitorGroupJoins[Q]]
	MonitorMaintenances       joinSet[monitorMaintenanceJoins[Q]]
	MonitorNotifications      joinSet[monitorNotificationJoins[Q]]
	MonitorTags               joinSet[monitorTagJoins[Q]]
	MonitorTLSInfos           joinSet[monitorTLSInfoJoins[Q]]
	Notifications             joinSet[notificationJoins[Q]]
	NotificationSentHistories joinSet[notificationSentHistoryJoins[Q]]
	Proxies                   joinSet[proxyJoins[Q]]
	RemoteBrowsers            joinSet[remoteBrowserJoins[Q]]
	StatDailies               joinSet[statDailyJoins[Q]]
	StatHourlies              joinSet[statHourlyJoins[Q]]
	StatMinutelies            joinSet[statMinutelyJoins[Q]]
	StatusPages               joinSet[statusPageJoins[Q]]
	StatusPageCnames          joinSet[statusPageCnameJoins[Q]]
	Tags                      joinSet[tagJoins[Q]]
	Users                     joinSet[userJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		APIKeys:                   buildJoinSet[apiKeyJoins[Q]](APIKeys.Columns, buildAPIKeyJoins),
		DockerHosts:               buildJoinSet[dockerHostJoins[Q]](DockerHosts.Columns, buildDockerHostJoins),
		Groups:                    buildJoinSet[groupJoins[Q]](Groups.Columns, buildGroupJoins),
		Heartbeats:                buildJoinSet[heartbeatJoins[Q]](Heartbeats.Columns, buildHeartbeatJoins),
		Incidents:                 buildJoinSet[incidentJoins[Q]](Incidents.Columns, buildIncidentJoins),
		Maintenances:              buildJoinSet[maintenanceJoins[Q]](Maintenances.Columns, buildMaintenanceJoins),
		MaintenanceStatusPages:    buildJoinSet[maintenanceStatusPageJoins[Q]](MaintenanceStatusPages.Columns, buildMaintenanceStatusPageJoins),
		MaintenanceTimeslots:      buildJoinSet[maintenanceTimeslotJoins[Q]](MaintenanceTimeslots.Columns, buildMaintenanceTimeslotJoins),
		Monitors:                  buildJoinSet[monitorJoins[Q]](Monitors.Columns, buildMonitorJoins),
		MonitorGroups:             buildJoinSet[monitorGroupJoins[Q]](MonitorGroups.Columns, buildMonitorGroupJoins),
		MonitorMaintenances:       buildJoinSet[monitorMaintenanceJoins[Q]](MonitorMaintenances.Columns, buildMonitorMaintenanceJoins),
		MonitorNotifications:      buildJoinSet[monitorNotificationJoins[Q]](MonitorNotifications.Columns, buildMonitorNotificationJoins),
		MonitorTags:               buildJoinSet[monitorTagJoins[Q]](MonitorTags.Columns, buildMonitorTagJoins),
		MonitorTLSInfos:           buildJoinSet[monitorTLSInfoJoins[Q]](MonitorTLSInfos.Columns, buildMonitorTLSInfoJoins),
		Notifications:             buildJoinSet[notificationJoins[Q]](Notifications.Columns, buildNotificationJoins),
		NotificationSentHistories: buildJoinSet[notificationSentHistoryJoins[Q]](NotificationSentHistories.Columns, buildNotificationSentHistoryJoins),
		Proxies:                   buildJoinSet[proxyJoins[Q]](Proxies.Columns, buildProxyJoins),
		RemoteBrowsers:            buildJoinSet[remoteBrowserJoins[Q]](RemoteBrowsers.Columns, buildRemoteBrowserJoins),
		StatDailies:               buildJoinSet[statDailyJoins[Q]](StatDailies.Columns, buildStatDailyJoins),
		StatHourlies:              buildJoinSet[statHourlyJoins[Q]](StatHourlies.Columns, buildStatHourlyJoins),
		StatMinutelies:            buildJoinSet[statMinutelyJoins[Q]](StatMinutelies.Columns, buildStatMinutelyJoins),
		StatusPages:               buildJoinSet[statusPageJoins[Q]](StatusPages.Columns, buildStatusPageJoins),
		StatusPageCnames:          buildJoinSet[statusPageCnameJoins[Q]](StatusPageCnames.Columns, buildStatusPageCnameJoins),
		Tags:                      buildJoinSet[tagJoins[Q]](Tags.Columns, buildTagJoins),
		Users:                     buildJoinSet[userJoins[Q]](Users.Columns, buildUserJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}
