// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

// Maintenance is an object representing the database table.
type Maintenance struct {
	ID          string              `db:"id,pk" `
	Title       string              `db:"title" `
	Description null.Val[string]    `db:"description" `
	UserID      string              `db:"user_id" `
	Active      bool                `db:"active" `
	Strategy    string              `db:"strategy" `
	StartDate   null.Val[time.Time] `db:"start_date" `
	EndDate     null.Val[time.Time] `db:"end_date" `
	StartTime   null.Val[string]    `db:"start_time" `
	EndTime     null.Val[string]    `db:"end_time" `
	Weekdays    null.Val[string]    `db:"weekdays" `
	DaysOfMonth null.Val[string]    `db:"days_of_month" `
	IntervalDay null.Val[int64]     `db:"interval_day" `
	Cron        null.Val[string]    `db:"cron" `
	Timezone    null.Val[string]    `db:"timezone" `
	Duration    null.Val[int64]     `db:"duration" `

	R maintenanceR `db:"-" `

	C maintenanceC `db:"-" `
}

// MaintenanceSlice is an alias for a slice of pointers to Maintenance.
// This should almost always be used instead of []*Maintenance.
type MaintenanceSlice []*Maintenance

// Maintenances contains methods to work with the maintenance table
var Maintenances = sqlite.NewTablex[*Maintenance, MaintenanceSlice, *MaintenanceSetter]("", "maintenance", buildMaintenanceColumns("maintenance"))

// MaintenancesQuery is a query on the maintenance table
type MaintenancesQuery = *sqlite.ViewQuery[*Maintenance, MaintenanceSlice]

// maintenanceR is where relationships are stored.
type maintenanceR struct {
	User                   *User                      // fk_maintenance_0
	MaintenanceStatusPages MaintenanceStatusPageSlice // fk_maintenance_status_page_0
	MaintenanceTimeslots   MaintenanceTimeslotSlice   // fk_maintenance_timeslot_0
	MonitorMaintenances    MonitorMaintenanceSlice    // fk_monitor_maintenance_0
}

func buildMaintenanceColumns(tableName string) maintenanceColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "title", "description", "user_id", "active", "strategy", "start_date", "end_date", "start_time", "end_time", "weekdays", "days_of_month", "interval_day", "cron", "timezone", "duration",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return maintenanceColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          sqlite.Quote(tableName, "id"),
		Title:       sqlite.Quote(tableName, "title"),
		Description: sqlite.Quote(tableName, "description"),
		UserID:      sqlite.Quote(tableName, "user_id"),
		Active:      sqlite.Quote(tableName, "active"),
		Strategy:    sqlite.Quote(tableName, "strategy"),
		StartDate:   sqlite.Quote(tableName, "start_date"),
		EndDate:     sqlite.Quote(tableName, "end_date"),
		StartTime:   sqlite.Quote(tableName, "start_time"),
		EndTime:     sqlite.Quote(tableName, "end_time"),
		Weekdays:    sqlite.Quote(tableName, "weekdays"),
		DaysOfMonth: sqlite.Quote(tableName, "days_of_month"),
		IntervalDay: sqlite.Quote(tableName, "interval_day"),
		Cron:        sqlite.Quote(tableName, "cron"),
		Timezone:    sqlite.Quote(tableName, "timezone"),
		Duration:    sqlite.Quote(tableName, "duration"),
	}
}

type maintenanceColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          sqlite.Expression
	Title       sqlite.Expression
	Description sqlite.Expression
	UserID      sqlite.Expression
	Active      sqlite.Expression
	Strategy    sqlite.Expression
	StartDate   sqlite.Expression
	EndDate     sqlite.Expression
	StartTime   sqlite.Expression
	EndTime     sqlite.Expression
	Weekdays    sqlite.Expression
	DaysOfMonth sqlite.Expression
	IntervalDay sqlite.Expression
	Cron        sqlite.Expression
	Timezone    sqlite.Expression
	Duration    sqlite.Expression
}

func (c maintenanceColumns) Alias() string {
	return c.tableAlias
}

func (maintenanceColumns) AliasedAs(tableName string) maintenanceColumns {
	return buildMaintenanceColumns(tableName)
}

func (c maintenanceColumns) Unqualified() maintenanceColumns {
	return buildMaintenanceColumns("")
}

// MaintenanceSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type MaintenanceSetter struct {
	ID          omit.Val[string]        `db:"id,pk" `
	Title       omit.Val[string]        `db:"title" `
	Description omitnull.Val[string]    `db:"description" `
	UserID      omit.Val[string]        `db:"user_id" `
	Active      omit.Val[bool]          `db:"active" `
	Strategy    omit.Val[string]        `db:"strategy" `
	StartDate   omitnull.Val[time.Time] `db:"start_date" `
	EndDate     omitnull.Val[time.Time] `db:"end_date" `
	StartTime   omitnull.Val[string]    `db:"start_time" `
	EndTime     omitnull.Val[string]    `db:"end_time" `
	Weekdays    omitnull.Val[string]    `db:"weekdays" `
	DaysOfMonth omitnull.Val[string]    `db:"days_of_month" `
	IntervalDay omitnull.Val[int64]     `db:"interval_day" `
	Cron        omitnull.Val[string]    `db:"cron" `
	Timezone    omitnull.Val[string]    `db:"timezone" `
	Duration    omitnull.Val[int64]     `db:"duration" `
}

func (s MaintenanceSetter) SetColumns() []string {
	vals := make([]string, 0, 16)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Active.IsValue() {
		vals = append(vals, "active")
	}
	if s.Strategy.IsValue() {
		vals = append(vals, "strategy")
	}
	if !s.StartDate.IsUnset() {
		vals = append(vals, "start_date")
	}
	if !s.EndDate.IsUnset() {
		vals = append(vals, "end_date")
	}
	if !s.StartTime.IsUnset() {
		vals = append(vals, "start_time")
	}
	if !s.EndTime.IsUnset() {
		vals = append(vals, "end_time")
	}
	if !s.Weekdays.IsUnset() {
		vals = append(vals, "weekdays")
	}
	if !s.DaysOfMonth.IsUnset() {
		vals = append(vals, "days_of_month")
	}
	if !s.IntervalDay.IsUnset() {
		vals = append(vals, "interval_day")
	}
	if !s.Cron.IsUnset() {
		vals = append(vals, "cron")
	}
	if !s.Timezone.IsUnset() {
		vals = append(vals, "timezone")
	}
	if !s.Duration.IsUnset() {
		vals = append(vals, "duration")
	}
	return vals
}

func (s MaintenanceSetter) Overwrite(t *Maintenance) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Active.IsValue() {
		t.Active = s.Active.MustGet()
	}
	if s.Strategy.IsValue() {
		t.Strategy = s.Strategy.MustGet()
	}
	if !s.StartDate.IsUnset() {
		t.StartDate = s.StartDate.MustGetNull()
	}
	if !s.EndDate.IsUnset() {
		t.EndDate = s.EndDate.MustGetNull()
	}
	if !s.StartTime.IsUnset() {
		t.StartTime = s.StartTime.MustGetNull()
	}
	if !s.EndTime.IsUnset() {
		t.EndTime = s.EndTime.MustGetNull()
	}
	if !s.Weekdays.IsUnset() {
		t.Weekdays = s.Weekdays.MustGetNull()
	}
	if !s.DaysOfMonth.IsUnset() {
		t.DaysOfMonth = s.DaysOfMonth.MustGetNull()
	}
	if !s.IntervalDay.IsUnset() {
		t.IntervalDay = s.IntervalDay.MustGetNull()
	}
	if !s.Cron.IsUnset() {
		t.Cron = s.Cron.MustGetNull()
	}
	if !s.Timezone.IsUnset() {
		t.Timezone = s.Timezone.MustGetNull()
	}
	if !s.Duration.IsUnset() {
		t.Duration = s.Duration.MustGetNull()
	}
}

func (s *MaintenanceSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Maintenances.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 16)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Title.IsValue() {
			vals = append(vals, sqlite.Arg(s.Title.MustGet()))
		}

		if !s.Description.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Description.MustGetNull()))
		}

		if s.UserID.IsValue() {
			vals = append(vals, sqlite.Arg(s.UserID.MustGet()))
		}

		if s.Active.IsValue() {
			vals = append(vals, sqlite.Arg(s.Active.MustGet()))
		}

		if s.Strategy.IsValue() {
			vals = append(vals, sqlite.Arg(s.Strategy.MustGet()))
		}

		if !s.StartDate.IsUnset() {
			vals = append(vals, sqlite.Arg(s.StartDate.MustGetNull()))
		}

		if !s.EndDate.IsUnset() {
			vals = append(vals, sqlite.Arg(s.EndDate.MustGetNull()))
		}

		if !s.StartTime.IsUnset() {
			vals = append(vals, sqlite.Arg(s.StartTime.MustGetNull()))
		}

		if !s.EndTime.IsUnset() {
			vals = append(vals, sqlite.Arg(s.EndTime.MustGetNull()))
		}

		if !s.Weekdays.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Weekdays.MustGetNull()))
		}

		if !s.DaysOfMonth.IsUnset() {
			vals = append(vals, sqlite.Arg(s.DaysOfMonth.MustGetNull()))
		}

		if !s.IntervalDay.IsUnset() {
			vals = append(vals, sqlite.Arg(s.IntervalDay.MustGetNull()))
		}

		if !s.Cron.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Cron.MustGetNull()))
		}

		if !s.Timezone.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Timezone.MustGetNull()))
		}

		if !s.Duration.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Duration.MustGetNull()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s MaintenanceSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s MaintenanceSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 16)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "title")...),
			sqlite.Arg(s.Title),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "description")...),
			sqlite.Arg(s.Description),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "user_id")...),
			sqlite.Arg(s.UserID),
		}})
	}

	if s.Active.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "active")...),
			sqlite.Arg(s.Active),
		}})
	}

	if s.Strategy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "strategy")...),
			sqlite.Arg(s.Strategy),
		}})
	}

	if !s.StartDate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "start_date")...),
			sqlite.Arg(s.StartDate),
		}})
	}

	if !s.EndDate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "end_date")...),
			sqlite.Arg(s.EndDate),
		}})
	}

	if !s.StartTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "start_time")...),
			sqlite.Arg(s.StartTime),
		}})
	}

	if !s.EndTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "end_time")...),
			sqlite.Arg(s.EndTime),
		}})
	}

	if !s.Weekdays.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "weekdays")...),
			sqlite.Arg(s.Weekdays),
		}})
	}

	if !s.DaysOfMonth.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "days_of_month")...),
			sqlite.Arg(s.DaysOfMonth),
		}})
	}

	if !s.IntervalDay.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "interval_day")...),
			sqlite.Arg(s.IntervalDay),
		}})
	}

	if !s.Cron.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "cron")...),
			sqlite.Arg(s.Cron),
		}})
	}

	if !s.Timezone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "timezone")...),
			sqlite.Arg(s.Timezone),
		}})
	}

	if !s.Duration.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "duration")...),
			sqlite.Arg(s.Duration),
		}})
	}

	return exprs
}

// FindMaintenance retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindMaintenance(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Maintenance, error) {
	if len(cols) == 0 {
		return Maintenances.Query(
			sm.Where(Maintenances.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Maintenances.Query(
		sm.Where(Maintenances.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Maintenances.Columns.Only(cols...)),
	).One(ctx, exec)
}

// MaintenanceExists checks the presence of a single record by primary key
func MaintenanceExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Maintenances.Query(
		sm.Where(Maintenances.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Maintenance is retrieved from the database
func (o *Maintenance) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Maintenances.AfterSelectHooks.RunHooks(ctx, exec, MaintenanceSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Maintenances.AfterInsertHooks.RunHooks(ctx, exec, MaintenanceSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Maintenances.AfterUpdateHooks.RunHooks(ctx, exec, MaintenanceSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Maintenances.AfterDeleteHooks.RunHooks(ctx, exec, MaintenanceSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Maintenance
func (o *Maintenance) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Maintenance) pkEQ() dialect.Expression {
	return sqlite.Quote("maintenance", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Maintenance
func (o *Maintenance) Update(ctx context.Context, exec bob.Executor, s *MaintenanceSetter) error {
	v, err := Maintenances.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Maintenance record with an executor
func (o *Maintenance) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Maintenances.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Maintenance using the executor
func (o *Maintenance) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Maintenances.Query(
		sm.Where(Maintenances.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after MaintenanceSlice is retrieved from the database
func (o MaintenanceSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Maintenances.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Maintenances.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Maintenances.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Maintenances.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o MaintenanceSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("maintenance", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o MaintenanceSlice) copyMatchingRows(from ...*Maintenance) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o MaintenanceSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Maintenances.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Maintenance:
				o.copyMatchingRows(retrieved)
			case []*Maintenance:
				o.copyMatchingRows(retrieved...)
			case MaintenanceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Maintenance or a slice of Maintenance
				// then run the AfterUpdateHooks on the slice
				_, err = Maintenances.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o MaintenanceSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Maintenances.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Maintenance:
				o.copyMatchingRows(retrieved)
			case []*Maintenance:
				o.copyMatchingRows(retrieved...)
			case MaintenanceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Maintenance or a slice of Maintenance
				// then run the AfterDeleteHooks on the slice
				_, err = Maintenances.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o MaintenanceSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals MaintenanceSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Maintenances.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o MaintenanceSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Maintenances.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o MaintenanceSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Maintenances.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on user
func (o *Maintenance) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os MaintenanceSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.UserID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// MaintenanceStatusPages starts a query for related objects on maintenance_status_page
func (o *Maintenance) MaintenanceStatusPages(mods ...bob.Mod[*dialect.SelectQuery]) MaintenanceStatusPagesQuery {
	return MaintenanceStatusPages.Query(append(mods,
		sm.Where(MaintenanceStatusPages.Columns.MaintenanceID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os MaintenanceSlice) MaintenanceStatusPages(mods ...bob.Mod[*dialect.SelectQuery]) MaintenanceStatusPagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return MaintenanceStatusPages.Query(append(mods,
		sm.Where(sqlite.Group(MaintenanceStatusPages.Columns.MaintenanceID).OP("IN", PKArgExpr)),
	)...)
}

// MaintenanceTimeslots starts a query for related objects on maintenance_timeslot
func (o *Maintenance) MaintenanceTimeslots(mods ...bob.Mod[*dialect.SelectQuery]) MaintenanceTimeslotsQuery {
	return MaintenanceTimeslots.Query(append(mods,
		sm.Where(MaintenanceTimeslots.Columns.MaintenanceID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os MaintenanceSlice) MaintenanceTimeslots(mods ...bob.Mod[*dialect.SelectQuery]) MaintenanceTimeslotsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return MaintenanceTimeslots.Query(append(mods,
		sm.Where(sqlite.Group(MaintenanceTimeslots.Columns.MaintenanceID).OP("IN", PKArgExpr)),
	)...)
}

// MonitorMaintenances starts a query for related objects on monitor_maintenance
func (o *Maintenance) MonitorMaintenances(mods ...bob.Mod[*dialect.SelectQuery]) MonitorMaintenancesQuery {
	return MonitorMaintenances.Query(append(mods,
		sm.Where(MonitorMaintenances.Columns.MaintenanceID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os MaintenanceSlice) MonitorMaintenances(mods ...bob.Mod[*dialect.SelectQuery]) MonitorMaintenancesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return MonitorMaintenances.Query(append(mods,
		sm.Where(sqlite.Group(MonitorMaintenances.Columns.MaintenanceID).OP("IN", PKArgExpr)),
	)...)
}

func attachMaintenanceUser0(ctx context.Context, exec bob.Executor, count int, maintenance0 *Maintenance, user1 *User) (*Maintenance, error) {
	setter := &MaintenanceSetter{
		UserID: omit.From(user1.ID),
	}

	err := maintenance0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachMaintenanceUser0: %w", err)
	}

	return maintenance0, nil
}

func (maintenance0 *Maintenance) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachMaintenanceUser0(ctx, exec, 1, maintenance0, user1)
	if err != nil {
		return err
	}

	maintenance0.R.User = user1

	user1.R.Maintenances = append(user1.R.Maintenances, maintenance0)

	return nil
}

func (maintenance0 *Maintenance) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachMaintenanceUser0(ctx, exec, 1, maintenance0, user1)
	if err != nil {
		return err
	}

	maintenance0.R.User = user1

	user1.R.Maintenances = append(user1.R.Maintenances, maintenance0)

	return nil
}

func insertMaintenanceMaintenanceStatusPages0(ctx context.Context, exec bob.Executor, maintenanceStatusPages1 []*MaintenanceStatusPageSetter, maintenance0 *Maintenance) (MaintenanceStatusPageSlice, error) {
	for i := range maintenanceStatusPages1 {
		maintenanceStatusPages1[i].MaintenanceID = omit.From(maintenance0.ID)
	}

	ret, err := MaintenanceStatusPages.Insert(bob.ToMods(maintenanceStatusPages1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMaintenanceMaintenanceStatusPages0: %w", err)
	}

	return ret, nil
}

func attachMaintenanceMaintenanceStatusPages0(ctx context.Context, exec bob.Executor, count int, maintenanceStatusPages1 MaintenanceStatusPageSlice, maintenance0 *Maintenance) (MaintenanceStatusPageSlice, error) {
	setter := &MaintenanceStatusPageSetter{
		MaintenanceID: omit.From(maintenance0.ID),
	}

	err := maintenanceStatusPages1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMaintenanceMaintenanceStatusPages0: %w", err)
	}

	return maintenanceStatusPages1, nil
}

func (maintenance0 *Maintenance) InsertMaintenanceStatusPages(ctx context.Context, exec bob.Executor, related ...*MaintenanceStatusPageSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	maintenanceStatusPages1, err := insertMaintenanceMaintenanceStatusPages0(ctx, exec, related, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MaintenanceStatusPages = append(maintenance0.R.MaintenanceStatusPages, maintenanceStatusPages1...)

	for _, rel := range maintenanceStatusPages1 {
		rel.R.Maintenance = maintenance0
	}
	return nil
}

func (maintenance0 *Maintenance) AttachMaintenanceStatusPages(ctx context.Context, exec bob.Executor, related ...*MaintenanceStatusPage) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	maintenanceStatusPages1 := MaintenanceStatusPageSlice(related)

	_, err = attachMaintenanceMaintenanceStatusPages0(ctx, exec, len(related), maintenanceStatusPages1, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MaintenanceStatusPages = append(maintenance0.R.MaintenanceStatusPages, maintenanceStatusPages1...)

	for _, rel := range related {
		rel.R.Maintenance = maintenance0
	}

	return nil
}

func insertMaintenanceMaintenanceTimeslots0(ctx context.Context, exec bob.Executor, maintenanceTimeslots1 []*MaintenanceTimeslotSetter, maintenance0 *Maintenance) (MaintenanceTimeslotSlice, error) {
	for i := range maintenanceTimeslots1 {
		maintenanceTimeslots1[i].MaintenanceID = omit.From(maintenance0.ID)
	}

	ret, err := MaintenanceTimeslots.Insert(bob.ToMods(maintenanceTimeslots1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMaintenanceMaintenanceTimeslots0: %w", err)
	}

	return ret, nil
}

func attachMaintenanceMaintenanceTimeslots0(ctx context.Context, exec bob.Executor, count int, maintenanceTimeslots1 MaintenanceTimeslotSlice, maintenance0 *Maintenance) (MaintenanceTimeslotSlice, error) {
	setter := &MaintenanceTimeslotSetter{
		MaintenanceID: omit.From(maintenance0.ID),
	}

	err := maintenanceTimeslots1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMaintenanceMaintenanceTimeslots0: %w", err)
	}

	return maintenanceTimeslots1, nil
}

func (maintenance0 *Maintenance) InsertMaintenanceTimeslots(ctx context.Context, exec bob.Executor, related ...*MaintenanceTimeslotSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	maintenanceTimeslots1, err := insertMaintenanceMaintenanceTimeslots0(ctx, exec, related, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MaintenanceTimeslots = append(maintenance0.R.MaintenanceTimeslots, maintenanceTimeslots1...)

	for _, rel := range maintenanceTimeslots1 {
		rel.R.Maintenance = maintenance0
	}
	return nil
}

func (maintenance0 *Maintenance) AttachMaintenanceTimeslots(ctx context.Context, exec bob.Executor, related ...*MaintenanceTimeslot) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	maintenanceTimeslots1 := MaintenanceTimeslotSlice(related)

	_, err = attachMaintenanceMaintenanceTimeslots0(ctx, exec, len(related), maintenanceTimeslots1, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MaintenanceTimeslots = append(maintenance0.R.MaintenanceTimeslots, maintenanceTimeslots1...)

	for _, rel := range related {
		rel.R.Maintenance = maintenance0
	}

	return nil
}

func insertMaintenanceMonitorMaintenances0(ctx context.Context, exec bob.Executor, monitorMaintenances1 []*MonitorMaintenanceSetter, maintenance0 *Maintenance) (MonitorMaintenanceSlice, error) {
	for i := range monitorMaintenances1 {
		monitorMaintenances1[i].MaintenanceID = omit.From(maintenance0.ID)
	}

	ret, err := MonitorMaintenances.Insert(bob.ToMods(monitorMaintenances1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMaintenanceMonitorMaintenances0: %w", err)
	}

	return ret, nil
}

func attachMaintenanceMonitorMaintenances0(ctx context.Context, exec bob.Executor, count int, monitorMaintenances1 MonitorMaintenanceSlice, maintenance0 *Maintenance) (MonitorMaintenanceSlice, error) {
	setter := &MonitorMaintenanceSetter{
		MaintenanceID: omit.From(maintenance0.ID),
	}

	err := monitorMaintenances1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMaintenanceMonitorMaintenances0: %w", err)
	}

	return monitorMaintenances1, nil
}

func (maintenance0 *Maintenance) InsertMonitorMaintenances(ctx context.Context, exec bob.Executor, related ...*MonitorMaintenanceSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	monitorMaintenances1, err := insertMaintenanceMonitorMaintenances0(ctx, exec, related, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MonitorMaintenances = append(maintenance0.R.MonitorMaintenances, monitorMaintenances1...)

	for _, rel := range monitorMaintenances1 {
		rel.R.Maintenance = maintenance0
	}
	return nil
}

func (maintenance0 *Maintenance) AttachMonitorMaintenances(ctx context.Context, exec bob.Executor, related ...*MonitorMaintenance) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	monitorMaintenances1 := MonitorMaintenanceSlice(related)

	_, err = attachMaintenanceMonitorMaintenances0(ctx, exec, len(related), monitorMaintenances1, maintenance0)
	if err != nil {
		return err
	}

	maintenance0.R.MonitorMaintenances = append(maintenance0.R.MonitorMaintenances, monitorMaintenances1...)

	for _, rel := range related {
		rel.R.Maintenance = maintenance0
	}

	return nil
}

type maintenanceWhere[Q sqlite.Filterable] struct {
	ID          sqlite.WhereMod[Q, string]
	Title       sqlite.WhereMod[Q, string]
	Description sqlite.WhereNullMod[Q, string]
	UserID      sqlite.WhereMod[Q, string]
	Active      sqlite.WhereMod[Q, bool]
	Strategy    sqlite.WhereMod[Q, string]
	StartDate   sqlite.WhereNullMod[Q, time.Time]
	EndDate     sqlite.WhereNullMod[Q, time.Time]
	StartTime   sqlite.WhereNullMod[Q, string]
	EndTime     sqlite.WhereNullMod[Q, string]
	Weekdays    sqlite.WhereNullMod[Q, string]
	DaysOfMonth sqlite.WhereNullMod[Q, string]
	IntervalDay sqlite.WhereNullMod[Q, int64]
	Cron        sqlite.WhereNullMod[Q, string]
	Timezone    sqlite.WhereNullMod[Q, string]
	Duration    sqlite.WhereNullMod[Q, int64]
}

func (maintenanceWhere[Q]) AliasedAs(alias string) maintenanceWhere[Q] {
	return buildMaintenanceWhere[Q](buildMaintenanceColumns(alias))
}

func buildMaintenanceWhere[Q sqlite.Filterable](cols maintenanceColumns) maintenanceWhere[Q] {
	return maintenanceWhere[Q]{
		ID:          sqlite.Where[Q, string](cols.ID),
		Title:       sqlite.Where[Q, string](cols.Title),
		Description: sqlite.WhereNull[Q, string](cols.Description),
		UserID:      sqlite.Where[Q, string](cols.UserID),
		Active:      sqlite.Where[Q, bool](cols.Active),
		Strategy:    sqlite.Where[Q, string](cols.Strategy),
		StartDate:   sqlite.WhereNull[Q, time.Time](cols.StartDate),
		EndDate:     sqlite.WhereNull[Q, time.Time](cols.EndDate),
		StartTime:   sqlite.WhereNull[Q, string](cols.StartTime),
		EndTime:     sqlite.WhereNull[Q, string](cols.EndTime),
		Weekdays:    sqlite.WhereNull[Q, string](cols.Weekdays),
		DaysOfMonth: sqlite.WhereNull[Q, string](cols.DaysOfMonth),
		IntervalDay: sqlite.WhereNull[Q, int64](cols.IntervalDay),
		Cron:        sqlite.WhereNull[Q, string](cols.Cron),
		Timezone:    sqlite.WhereNull[Q, string](cols.Timezone),
		Duration:    sqlite.WhereNull[Q, int64](cols.Duration),
	}
}

func (o *Maintenance) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("maintenance cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Maintenances = MaintenanceSlice{o}
		}
		return nil
	case "MaintenanceStatusPages":
		rels, ok := retrieved.(MaintenanceStatusPageSlice)
		if !ok {
			return fmt.Errorf("maintenance cannot load %T as %q", retrieved, name)
		}

		o.R.MaintenanceStatusPages = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Maintenance = o
			}
		}
		return nil
	case "MaintenanceTimeslots":
		rels, ok := retrieved.(MaintenanceTimeslotSlice)
		if !ok {
			return fmt.Errorf("maintenance cannot load %T as %q", retrieved, name)
		}

		o.R.MaintenanceTimeslots = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Maintenance = o
			}
		}
		return nil
	case "MonitorMaintenances":
		rels, ok := retrieved.(MonitorMaintenanceSlice)
		if !ok {
			return fmt.Errorf("maintenance cannot load %T as %q", retrieved, name)
		}

		o.R.MonitorMaintenances = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Maintenance = o
			}
		}
		return nil
	default:
		return fmt.Errorf("maintenance has no relationship %q", name)
	}
}

type maintenancePreloader struct {
	User func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildMaintenancePreloader() maintenancePreloader {
	return maintenancePreloader{
		User: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "User",
				Sides: []sqlite.PreloadSide{
					{
						From:        Maintenances,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type maintenanceThenLoader[Q orm.Loadable] struct {
	User                   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MaintenanceStatusPages func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MaintenanceTimeslots   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MonitorMaintenances    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMaintenanceThenLoader[Q orm.Loadable]() maintenanceThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MaintenanceStatusPagesLoadInterface interface {
		LoadMaintenanceStatusPages(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MaintenanceTimeslotsLoadInterface interface {
		LoadMaintenanceTimeslots(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MonitorMaintenancesLoadInterface interface {
		LoadMonitorMaintenances(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return maintenanceThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
		MaintenanceStatusPages: thenLoadBuilder[Q](
			"MaintenanceStatusPages",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenanceStatusPagesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMaintenanceStatusPages(ctx, exec, mods...)
			},
		),
		MaintenanceTimeslots: thenLoadBuilder[Q](
			"MaintenanceTimeslots",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenanceTimeslotsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMaintenanceTimeslots(ctx, exec, mods...)
			},
		),
		MonitorMaintenances: thenLoadBuilder[Q](
			"MonitorMaintenances",
			func(ctx context.Context, exec bob.Executor, retrieved MonitorMaintenancesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMonitorMaintenances(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the maintenance's User into the .R struct
func (o *Maintenance) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Maintenances = MaintenanceSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the maintenance's User into the .R struct
func (os MaintenanceSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Maintenances = append(rel.R.Maintenances, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

// LoadMaintenanceStatusPages loads the maintenance's MaintenanceStatusPages into the .R struct
func (o *Maintenance) LoadMaintenanceStatusPages(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MaintenanceStatusPages = nil

	related, err := o.MaintenanceStatusPages(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Maintenance = o
	}

	o.R.MaintenanceStatusPages = related
	return nil
}

// LoadMaintenanceStatusPages loads the maintenance's MaintenanceStatusPages into the .R struct
func (os MaintenanceSlice) LoadMaintenanceStatusPages(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	maintenanceStatusPages, err := os.MaintenanceStatusPages(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MaintenanceStatusPages = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range maintenanceStatusPages {

			if !(o.ID == rel.MaintenanceID) {
				continue
			}

			rel.R.Maintenance = o

			o.R.MaintenanceStatusPages = append(o.R.MaintenanceStatusPages, rel)
		}
	}

	return nil
}

// LoadMaintenanceTimeslots loads the maintenance's MaintenanceTimeslots into the .R struct
func (o *Maintenance) LoadMaintenanceTimeslots(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MaintenanceTimeslots = nil

	related, err := o.MaintenanceTimeslots(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Maintenance = o
	}

	o.R.MaintenanceTimeslots = related
	return nil
}

// LoadMaintenanceTimeslots loads the maintenance's MaintenanceTimeslots into the .R struct
func (os MaintenanceSlice) LoadMaintenanceTimeslots(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	maintenanceTimeslots, err := os.MaintenanceTimeslots(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MaintenanceTimeslots = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range maintenanceTimeslots {

			if !(o.ID == rel.MaintenanceID) {
				continue
			}

			rel.R.Maintenance = o

			o.R.MaintenanceTimeslots = append(o.R.MaintenanceTimeslots, rel)
		}
	}

	return nil
}

// LoadMonitorMaintenances loads the maintenance's MonitorMaintenances into the .R struct
func (o *Maintenance) LoadMonitorMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MonitorMaintenances = nil

	related, err := o.MonitorMaintenances(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Maintenance = o
	}

	o.R.MonitorMaintenances = related
	return nil
}

// LoadMonitorMaintenances loads the maintenance's MonitorMaintenances into the .R struct
func (os MaintenanceSlice) LoadMonitorMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	monitorMaintenances, err := os.MonitorMaintenances(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MonitorMaintenances = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range monitorMaintenances {

			if !(o.ID == rel.MaintenanceID) {
				continue
			}

			rel.R.Maintenance = o

			o.R.MonitorMaintenances = append(o.R.MonitorMaintenances, rel)
		}
	}

	return nil
}

// maintenanceC is where relationship counts are stored.
type maintenanceC struct {
	MaintenanceStatusPages *int64
	MaintenanceTimeslots   *int64
	MonitorMaintenances    *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Maintenance) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "MaintenanceStatusPages":
		o.C.MaintenanceStatusPages = &count
	case "MaintenanceTimeslots":
		o.C.MaintenanceTimeslots = &count
	case "MonitorMaintenances":
		o.C.MonitorMaintenances = &count
	}
	return nil
}

type maintenanceCountPreloader struct {
	MaintenanceStatusPages func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	MaintenanceTimeslots   func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	MonitorMaintenances    func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
}

func buildMaintenanceCountPreloader() maintenanceCountPreloader {
	return maintenanceCountPreloader{
		MaintenanceStatusPages: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*Maintenance]("MaintenanceStatusPages", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Maintenances.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(MaintenanceStatusPages.Name()),
					sm.Where(sqlite.Quote(MaintenanceStatusPages.Alias(), "maintenance_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		MaintenanceTimeslots: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*Maintenance]("MaintenanceTimeslots", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Maintenances.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(MaintenanceTimeslots.Name()),
					sm.Where(sqlite.Quote(MaintenanceTimeslots.Alias(), "maintenance_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		MonitorMaintenances: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*Maintenance]("MonitorMaintenances", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Maintenances.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(MonitorMaintenances.Name()),
					sm.Where(sqlite.Quote(MonitorMaintenances.Alias(), "maintenance_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
	}
}

type maintenanceCountThenLoader[Q orm.Loadable] struct {
	MaintenanceStatusPages func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MaintenanceTimeslots   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MonitorMaintenances    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMaintenanceCountThenLoader[Q orm.Loadable]() maintenanceCountThenLoader[Q] {
	type MaintenanceStatusPagesCountInterface interface {
		LoadCountMaintenanceStatusPages(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MaintenanceTimeslotsCountInterface interface {
		LoadCountMaintenanceTimeslots(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MonitorMaintenancesCountInterface interface {
		LoadCountMonitorMaintenances(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return maintenanceCountThenLoader[Q]{
		MaintenanceStatusPages: countThenLoadBuilder[Q](
			"MaintenanceStatusPages",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenanceStatusPagesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMaintenanceStatusPages(ctx, exec, mods...)
			},
		),
		MaintenanceTimeslots: countThenLoadBuilder[Q](
			"MaintenanceTimeslots",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenanceTimeslotsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMaintenanceTimeslots(ctx, exec, mods...)
			},
		),
		MonitorMaintenances: countThenLoadBuilder[Q](
			"MonitorMaintenances",
			func(ctx context.Context, exec bob.Executor, retrieved MonitorMaintenancesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMonitorMaintenances(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountMaintenanceStatusPages loads the count of MaintenanceStatusPages into the C struct
func (o *Maintenance) LoadCountMaintenanceStatusPages(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.MaintenanceStatusPages(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.MaintenanceStatusPages = &count
	return nil
}

// LoadCountMaintenanceStatusPages loads the count of MaintenanceStatusPages for a slice in a single batch query
func (os MaintenanceSlice) LoadCountMaintenanceStatusPages(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MaintenanceStatusPages.Columns.MaintenanceID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MaintenanceStatusPages.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MaintenanceStatusPages.Columns.MaintenanceID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MaintenanceStatusPages.Columns.MaintenanceID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.MaintenanceStatusPages = &count
	}

	return nil
}

// LoadCountMaintenanceTimeslots loads the count of MaintenanceTimeslots into the C struct
func (o *Maintenance) LoadCountMaintenanceTimeslots(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.MaintenanceTimeslots(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.MaintenanceTimeslots = &count
	return nil
}

// LoadCountMaintenanceTimeslots loads the count of MaintenanceTimeslots for a slice in a single batch query
func (os MaintenanceSlice) LoadCountMaintenanceTimeslots(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MaintenanceTimeslots.Columns.MaintenanceID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MaintenanceTimeslots.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MaintenanceTimeslots.Columns.MaintenanceID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MaintenanceTimeslots.Columns.MaintenanceID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.MaintenanceTimeslots = &count
	}

	return nil
}

// LoadCountMonitorMaintenances loads the count of MonitorMaintenances into the C struct
func (o *Maintenance) LoadCountMonitorMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.MonitorMaintenances(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.MonitorMaintenances = &count
	return nil
}

// LoadCountMonitorMaintenances loads the count of MonitorMaintenances for a slice in a single batch query
func (os MaintenanceSlice) LoadCountMonitorMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MonitorMaintenances.Columns.MaintenanceID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MonitorMaintenances.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MonitorMaintenances.Columns.MaintenanceID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MonitorMaintenances.Columns.MaintenanceID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.MonitorMaintenances = &count
	}

	return nil
}

type maintenanceJoins[Q dialect.Joinable] struct {
	typ                    string
	User                   modAs[Q, userColumns]
	MaintenanceStatusPages modAs[Q, maintenanceStatusPageColumns]
	MaintenanceTimeslots   modAs[Q, maintenanceTimeslotColumns]
	MonitorMaintenances    modAs[Q, monitorMaintenanceColumns]
}

func (j maintenanceJoins[Q]) aliasedAs(alias string) maintenanceJoins[Q] {
	return buildMaintenanceJoins[Q](buildMaintenanceColumns(alias), j.typ)
}

func buildMaintenanceJoins[Q dialect.Joinable](cols maintenanceColumns, typ string) maintenanceJoins[Q] {
	return maintenanceJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
		MaintenanceStatusPages: modAs[Q, maintenanceStatusPageColumns]{
			c: MaintenanceStatusPages.Columns,
			f: func(to maintenanceStatusPageColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MaintenanceStatusPages.Name().As(to.Alias())).On(
						to.MaintenanceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		MaintenanceTimeslots: modAs[Q, maintenanceTimeslotColumns]{
			c: MaintenanceTimeslots.Columns,
			f: func(to maintenanceTimeslotColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MaintenanceTimeslots.Name().As(to.Alias())).On(
						to.MaintenanceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		MonitorMaintenances: modAs[Q, monitorMaintenanceColumns]{
			c: MonitorMaintenances.Columns,
			f: func(to monitorMaintenanceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MonitorMaintenances.Name().As(to.Alias())).On(
						to.MaintenanceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
