// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// StatDaily is an object representing the database table.
type StatDaily struct {
	ID        string            `db:"id,pk" `
	MonitorID string            `db:"monitor_id" `
	Timestamp int64             `db:"timestamp" `
	Ping      null.Val[float64] `db:"ping" `
	PingMin   null.Val[int64]   `db:"ping_min" `
	PingMax   null.Val[int64]   `db:"ping_max" `
	Up        int64             `db:"up" `
	Down      int64             `db:"down" `

	R statDailyR `db:"-" `
}

// StatDailySlice is an alias for a slice of pointers to StatDaily.
// This should almost always be used instead of []*StatDaily.
type StatDailySlice []*StatDaily

// StatDailies contains methods to work with the stat_daily table
var StatDailies = sqlite.NewTablex[*StatDaily, StatDailySlice, *StatDailySetter]("", "stat_daily", buildStatDailyColumns("stat_daily"))

// StatDailiesQuery is a query on the stat_daily table
type StatDailiesQuery = *sqlite.ViewQuery[*StatDaily, StatDailySlice]

// statDailyR is where relationships are stored.
type statDailyR struct {
	Monitor *Monitor // fk_stat_daily_0
}

func buildStatDailyColumns(tableName string) statDailyColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "monitor_id", "timestamp", "ping", "ping_min", "ping_max", "up", "down",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return statDailyColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          sqlite.Quote(tableName, "id"),
		MonitorID:   sqlite.Quote(tableName, "monitor_id"),
		Timestamp:   sqlite.Quote(tableName, "timestamp"),
		Ping:        sqlite.Quote(tableName, "ping"),
		PingMin:     sqlite.Quote(tableName, "ping_min"),
		PingMax:     sqlite.Quote(tableName, "ping_max"),
		Up:          sqlite.Quote(tableName, "up"),
		Down:        sqlite.Quote(tableName, "down"),
	}
}

type statDailyColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	MonitorID  sqlite.Expression
	Timestamp  sqlite.Expression
	Ping       sqlite.Expression
	PingMin    sqlite.Expression
	PingMax    sqlite.Expression
	Up         sqlite.Expression
	Down       sqlite.Expression
}

func (c statDailyColumns) Alias() string {
	return c.tableAlias
}

func (statDailyColumns) AliasedAs(tableName string) statDailyColumns {
	return buildStatDailyColumns(tableName)
}

func (c statDailyColumns) Unqualified() statDailyColumns {
	return buildStatDailyColumns("")
}

// StatDailySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StatDailySetter struct {
	ID        omit.Val[string]      `db:"id,pk" `
	MonitorID omit.Val[string]      `db:"monitor_id" `
	Timestamp omit.Val[int64]       `db:"timestamp" `
	Ping      omitnull.Val[float64] `db:"ping" `
	PingMin   omitnull.Val[int64]   `db:"ping_min" `
	PingMax   omitnull.Val[int64]   `db:"ping_max" `
	Up        omit.Val[int64]       `db:"up" `
	Down      omit.Val[int64]       `db:"down" `
}

func (s StatDailySetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.MonitorID.IsValue() {
		vals = append(vals, "monitor_id")
	}
	if s.Timestamp.IsValue() {
		vals = append(vals, "timestamp")
	}
	if !s.Ping.IsUnset() {
		vals = append(vals, "ping")
	}
	if !s.PingMin.IsUnset() {
		vals = append(vals, "ping_min")
	}
	if !s.PingMax.IsUnset() {
		vals = append(vals, "ping_max")
	}
	if s.Up.IsValue() {
		vals = append(vals, "up")
	}
	if s.Down.IsValue() {
		vals = append(vals, "down")
	}
	return vals
}

func (s StatDailySetter) Overwrite(t *StatDaily) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.MonitorID.IsValue() {
		t.MonitorID = s.MonitorID.MustGet()
	}
	if s.Timestamp.IsValue() {
		t.Timestamp = s.Timestamp.MustGet()
	}
	if !s.Ping.IsUnset() {
		t.Ping = s.Ping.MustGetNull()
	}
	if !s.PingMin.IsUnset() {
		t.PingMin = s.PingMin.MustGetNull()
	}
	if !s.PingMax.IsUnset() {
		t.PingMax = s.PingMax.MustGetNull()
	}
	if s.Up.IsValue() {
		t.Up = s.Up.MustGet()
	}
	if s.Down.IsValue() {
		t.Down = s.Down.MustGet()
	}
}

func (s *StatDailySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return StatDailies.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 8)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.MonitorID.IsValue() {
			vals = append(vals, sqlite.Arg(s.MonitorID.MustGet()))
		}

		if s.Timestamp.IsValue() {
			vals = append(vals, sqlite.Arg(s.Timestamp.MustGet()))
		}

		if !s.Ping.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Ping.MustGetNull()))
		}

		if !s.PingMin.IsUnset() {
			vals = append(vals, sqlite.Arg(s.PingMin.MustGetNull()))
		}

		if !s.PingMax.IsUnset() {
			vals = append(vals, sqlite.Arg(s.PingMax.MustGetNull()))
		}

		if s.Up.IsValue() {
			vals = append(vals, sqlite.Arg(s.Up.MustGet()))
		}

		if s.Down.IsValue() {
			vals = append(vals, sqlite.Arg(s.Down.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s StatDailySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s StatDailySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.MonitorID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "monitor_id")...),
			sqlite.Arg(s.MonitorID),
		}})
	}

	if s.Timestamp.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "timestamp")...),
			sqlite.Arg(s.Timestamp),
		}})
	}

	if !s.Ping.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "ping")...),
			sqlite.Arg(s.Ping),
		}})
	}

	if !s.PingMin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "ping_min")...),
			sqlite.Arg(s.PingMin),
		}})
	}

	if !s.PingMax.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "ping_max")...),
			sqlite.Arg(s.PingMax),
		}})
	}

	if s.Up.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "up")...),
			sqlite.Arg(s.Up),
		}})
	}

	if s.Down.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "down")...),
			sqlite.Arg(s.Down),
		}})
	}

	return exprs
}

// FindStatDaily retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStatDaily(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*StatDaily, error) {
	if len(cols) == 0 {
		return StatDailies.Query(
			sm.Where(StatDailies.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return StatDailies.Query(
		sm.Where(StatDailies.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(StatDailies.Columns.Only(cols...)),
	).One(ctx, exec)
}

// StatDailyExists checks the presence of a single record by primary key
func StatDailyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return StatDailies.Query(
		sm.Where(StatDailies.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after StatDaily is retrieved from the database
func (o *StatDaily) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StatDailies.AfterSelectHooks.RunHooks(ctx, exec, StatDailySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = StatDailies.AfterInsertHooks.RunHooks(ctx, exec, StatDailySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = StatDailies.AfterUpdateHooks.RunHooks(ctx, exec, StatDailySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = StatDailies.AfterDeleteHooks.RunHooks(ctx, exec, StatDailySlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the StatDaily
func (o *StatDaily) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *StatDaily) pkEQ() dialect.Expression {
	return sqlite.Quote("stat_daily", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the StatDaily
func (o *StatDaily) Update(ctx context.Context, exec bob.Executor, s *StatDailySetter) error {
	v, err := StatDailies.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single StatDaily record with an executor
func (o *StatDaily) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := StatDailies.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the StatDaily using the executor
func (o *StatDaily) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := StatDailies.Query(
		sm.Where(StatDailies.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after StatDailySlice is retrieved from the database
func (o StatDailySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StatDailies.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = StatDailies.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = StatDailies.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = StatDailies.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o StatDailySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("stat_daily", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o StatDailySlice) copyMatchingRows(from ...*StatDaily) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o StatDailySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StatDailies.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StatDaily:
				o.copyMatchingRows(retrieved)
			case []*StatDaily:
				o.copyMatchingRows(retrieved...)
			case StatDailySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StatDaily or a slice of StatDaily
				// then run the AfterUpdateHooks on the slice
				_, err = StatDailies.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o StatDailySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StatDailies.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StatDaily:
				o.copyMatchingRows(retrieved)
			case []*StatDaily:
				o.copyMatchingRows(retrieved...)
			case StatDailySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StatDaily or a slice of StatDaily
				// then run the AfterDeleteHooks on the slice
				_, err = StatDailies.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o StatDailySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StatDailySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StatDailies.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o StatDailySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StatDailies.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o StatDailySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := StatDailies.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Monitor starts a query for related objects on monitor
func (o *StatDaily) Monitor(mods ...bob.Mod[*dialect.SelectQuery]) MonitorsQuery {
	return Monitors.Query(append(mods,
		sm.Where(Monitors.Columns.ID.EQ(sqlite.Arg(o.MonitorID))),
	)...)
}

func (os StatDailySlice) Monitor(mods ...bob.Mod[*dialect.SelectQuery]) MonitorsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.MonitorID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Monitors.Query(append(mods,
		sm.Where(sqlite.Group(Monitors.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachStatDailyMonitor0(ctx context.Context, exec bob.Executor, count int, statDaily0 *StatDaily, monitor1 *Monitor) (*StatDaily, error) {
	setter := &StatDailySetter{
		MonitorID: omit.From(monitor1.ID),
	}

	err := statDaily0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachStatDailyMonitor0: %w", err)
	}

	return statDaily0, nil
}

func (statDaily0 *StatDaily) InsertMonitor(ctx context.Context, exec bob.Executor, related *MonitorSetter) error {
	var err error

	monitor1, err := Monitors.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachStatDailyMonitor0(ctx, exec, 1, statDaily0, monitor1)
	if err != nil {
		return err
	}

	statDaily0.R.Monitor = monitor1

	monitor1.R.StatDailies = append(monitor1.R.StatDailies, statDaily0)

	return nil
}

func (statDaily0 *StatDaily) AttachMonitor(ctx context.Context, exec bob.Executor, monitor1 *Monitor) error {
	var err error

	_, err = attachStatDailyMonitor0(ctx, exec, 1, statDaily0, monitor1)
	if err != nil {
		return err
	}

	statDaily0.R.Monitor = monitor1

	monitor1.R.StatDailies = append(monitor1.R.StatDailies, statDaily0)

	return nil
}

type statDailyWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereMod[Q, string]
	MonitorID sqlite.WhereMod[Q, string]
	Timestamp sqlite.WhereMod[Q, int64]
	Ping      sqlite.WhereNullMod[Q, float64]
	PingMin   sqlite.WhereNullMod[Q, int64]
	PingMax   sqlite.WhereNullMod[Q, int64]
	Up        sqlite.WhereMod[Q, int64]
	Down      sqlite.WhereMod[Q, int64]
}

func (statDailyWhere[Q]) AliasedAs(alias string) statDailyWhere[Q] {
	return buildStatDailyWhere[Q](buildStatDailyColumns(alias))
}

func buildStatDailyWhere[Q sqlite.Filterable](cols statDailyColumns) statDailyWhere[Q] {
	return statDailyWhere[Q]{
		ID:        sqlite.Where[Q, string](cols.ID),
		MonitorID: sqlite.Where[Q, string](cols.MonitorID),
		Timestamp: sqlite.Where[Q, int64](cols.Timestamp),
		Ping:      sqlite.WhereNull[Q, float64](cols.Ping),
		PingMin:   sqlite.WhereNull[Q, int64](cols.PingMin),
		PingMax:   sqlite.WhereNull[Q, int64](cols.PingMax),
		Up:        sqlite.Where[Q, int64](cols.Up),
		Down:      sqlite.Where[Q, int64](cols.Down),
	}
}

func (o *StatDaily) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Monitor":
		rel, ok := retrieved.(*Monitor)
		if !ok {
			return fmt.Errorf("statDaily cannot load %T as %q", retrieved, name)
		}

		o.R.Monitor = rel

		if rel != nil {
			rel.R.StatDailies = StatDailySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("statDaily has no relationship %q", name)
	}
}

type statDailyPreloader struct {
	Monitor func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildStatDailyPreloader() statDailyPreloader {
	return statDailyPreloader{
		Monitor: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Monitor, MonitorSlice](sqlite.PreloadRel{
				Name: "Monitor",
				Sides: []sqlite.PreloadSide{
					{
						From:        StatDailies,
						To:          Monitors,
						FromColumns: []string{"monitor_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Monitors.Columns.Names(), opts...)
		},
	}
}

type statDailyThenLoader[Q orm.Loadable] struct {
	Monitor func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildStatDailyThenLoader[Q orm.Loadable]() statDailyThenLoader[Q] {
	type MonitorLoadInterface interface {
		LoadMonitor(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return statDailyThenLoader[Q]{
		Monitor: thenLoadBuilder[Q](
			"Monitor",
			func(ctx context.Context, exec bob.Executor, retrieved MonitorLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMonitor(ctx, exec, mods...)
			},
		),
	}
}

// LoadMonitor loads the statDaily's Monitor into the .R struct
func (o *StatDaily) LoadMonitor(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Monitor = nil

	related, err := o.Monitor(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.StatDailies = StatDailySlice{o}

	o.R.Monitor = related
	return nil
}

// LoadMonitor loads the statDaily's Monitor into the .R struct
func (os StatDailySlice) LoadMonitor(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	monitors, err := os.Monitor(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range monitors {

			if !(o.MonitorID == rel.ID) {
				continue
			}

			rel.R.StatDailies = append(rel.R.StatDailies, o)

			o.R.Monitor = rel
			break
		}
	}

	return nil
}

type statDailyJoins[Q dialect.Joinable] struct {
	typ     string
	Monitor modAs[Q, monitorColumns]
}

func (j statDailyJoins[Q]) aliasedAs(alias string) statDailyJoins[Q] {
	return buildStatDailyJoins[Q](buildStatDailyColumns(alias), j.typ)
}

func buildStatDailyJoins[Q dialect.Joinable](cols statDailyColumns, typ string) statDailyJoins[Q] {
	return statDailyJoins[Q]{
		typ: typ,
		Monitor: modAs[Q, monitorColumns]{
			c: Monitors.Columns,
			f: func(to monitorColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Monitors.Name().As(to.Alias())).On(
						to.ID.EQ(cols.MonitorID),
					))
				}

				return mods
			},
		},
	}
}
