// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

// User is an object representing the database table.
type User struct {
	ID             string           `db:"id,pk" `
	Username       string           `db:"username" `
	Password       string           `db:"password" `
	Active         bool             `db:"active" `
	Timezone       null.Val[string] `db:"timezone" `
	TwofaSecret    null.Val[string] `db:"twofa_secret" `
	TwofaStatus    bool             `db:"twofa_status" `
	TwofaLastToken null.Val[string] `db:"twofa_last_token" `
	CreatedDate    time.Time        `db:"created_date" `

	R userR `db:"-" `

	C userC `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the user table
var Users = sqlite.NewTablex[*User, UserSlice, *UserSetter]("", "user", buildUserColumns("user"))

// UsersQuery is a query on the user table
type UsersQuery = *sqlite.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	APIKeys        APIKeySlice        // fk_api_key_0
	DockerHosts    DockerHostSlice    // fk_docker_host_0
	Maintenances   MaintenanceSlice   // fk_maintenance_0
	Monitors       MonitorSlice       // fk_monitor_1
	Notifications  NotificationSlice  // fk_notification_0
	Proxies        ProxySlice         // fk_proxy_0
	RemoteBrowsers RemoteBrowserSlice // fk_remote_browser_0
}

func buildUserColumns(tableName string) userColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "username", "password", "active", "timezone", "twofa_secret", "twofa_status", "twofa_last_token", "created_date",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return userColumns{
		ColumnsExpr:    columnsExpr,
		tableAlias:     tableName,
		ID:             sqlite.Quote(tableName, "id"),
		Username:       sqlite.Quote(tableName, "username"),
		Password:       sqlite.Quote(tableName, "password"),
		Active:         sqlite.Quote(tableName, "active"),
		Timezone:       sqlite.Quote(tableName, "timezone"),
		TwofaSecret:    sqlite.Quote(tableName, "twofa_secret"),
		TwofaStatus:    sqlite.Quote(tableName, "twofa_status"),
		TwofaLastToken: sqlite.Quote(tableName, "twofa_last_token"),
		CreatedDate:    sqlite.Quote(tableName, "created_date"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             sqlite.Expression
	Username       sqlite.Expression
	Password       sqlite.Expression
	Active         sqlite.Expression
	Timezone       sqlite.Expression
	TwofaSecret    sqlite.Expression
	TwofaStatus    sqlite.Expression
	TwofaLastToken sqlite.Expression
	CreatedDate    sqlite.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(tableName string) userColumns {
	return buildUserColumns(tableName)
}

func (c userColumns) Unqualified() userColumns {
	return buildUserColumns("")
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID             omit.Val[string]     `db:"id,pk" `
	Username       omit.Val[string]     `db:"username" `
	Password       omit.Val[string]     `db:"password" `
	Active         omit.Val[bool]       `db:"active" `
	Timezone       omitnull.Val[string] `db:"timezone" `
	TwofaSecret    omitnull.Val[string] `db:"twofa_secret" `
	TwofaStatus    omit.Val[bool]       `db:"twofa_status" `
	TwofaLastToken omitnull.Val[string] `db:"twofa_last_token" `
	CreatedDate    omit.Val[time.Time]  `db:"created_date" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Username.IsValue() {
		vals = append(vals, "username")
	}
	if s.Password.IsValue() {
		vals = append(vals, "password")
	}
	if s.Active.IsValue() {
		vals = append(vals, "active")
	}
	if !s.Timezone.IsUnset() {
		vals = append(vals, "timezone")
	}
	if !s.TwofaSecret.IsUnset() {
		vals = append(vals, "twofa_secret")
	}
	if s.TwofaStatus.IsValue() {
		vals = append(vals, "twofa_status")
	}
	if !s.TwofaLastToken.IsUnset() {
		vals = append(vals, "twofa_last_token")
	}
	if s.CreatedDate.IsValue() {
		vals = append(vals, "created_date")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Username.IsValue() {
		t.Username = s.Username.MustGet()
	}
	if s.Password.IsValue() {
		t.Password = s.Password.MustGet()
	}
	if s.Active.IsValue() {
		t.Active = s.Active.MustGet()
	}
	if !s.Timezone.IsUnset() {
		t.Timezone = s.Timezone.MustGetNull()
	}
	if !s.TwofaSecret.IsUnset() {
		t.TwofaSecret = s.TwofaSecret.MustGetNull()
	}
	if s.TwofaStatus.IsValue() {
		t.TwofaStatus = s.TwofaStatus.MustGet()
	}
	if !s.TwofaLastToken.IsUnset() {
		t.TwofaLastToken = s.TwofaLastToken.MustGetNull()
	}
	if s.CreatedDate.IsValue() {
		t.CreatedDate = s.CreatedDate.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 9)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Username.IsValue() {
			vals = append(vals, sqlite.Arg(s.Username.MustGet()))
		}

		if s.Password.IsValue() {
			vals = append(vals, sqlite.Arg(s.Password.MustGet()))
		}

		if s.Active.IsValue() {
			vals = append(vals, sqlite.Arg(s.Active.MustGet()))
		}

		if !s.Timezone.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Timezone.MustGetNull()))
		}

		if !s.TwofaSecret.IsUnset() {
			vals = append(vals, sqlite.Arg(s.TwofaSecret.MustGetNull()))
		}

		if s.TwofaStatus.IsValue() {
			vals = append(vals, sqlite.Arg(s.TwofaStatus.MustGet()))
		}

		if !s.TwofaLastToken.IsUnset() {
			vals = append(vals, sqlite.Arg(s.TwofaLastToken.MustGetNull()))
		}

		if s.CreatedDate.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedDate.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Username.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "username")...),
			sqlite.Arg(s.Username),
		}})
	}

	if s.Password.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "password")...),
			sqlite.Arg(s.Password),
		}})
	}

	if s.Active.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "active")...),
			sqlite.Arg(s.Active),
		}})
	}

	if !s.Timezone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "timezone")...),
			sqlite.Arg(s.Timezone),
		}})
	}

	if !s.TwofaSecret.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "twofa_secret")...),
			sqlite.Arg(s.TwofaSecret),
		}})
	}

	if s.TwofaStatus.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "twofa_status")...),
			sqlite.Arg(s.TwofaStatus),
		}})
	}

	if !s.TwofaLastToken.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "twofa_last_token")...),
			sqlite.Arg(s.TwofaLastToken),
		}})
	}

	if s.CreatedDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_date")...),
			sqlite.Arg(s.CreatedDate),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return sqlite.Quote("user", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("user", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// APIKeys starts a query for related objects on api_key
func (o *User) APIKeys(mods ...bob.Mod[*dialect.SelectQuery]) APIKeysQuery {
	return APIKeys.Query(append(mods,
		sm.Where(APIKeys.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) APIKeys(mods ...bob.Mod[*dialect.SelectQuery]) APIKeysQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return APIKeys.Query(append(mods,
		sm.Where(sqlite.Group(APIKeys.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// DockerHosts starts a query for related objects on docker_host
func (o *User) DockerHosts(mods ...bob.Mod[*dialect.SelectQuery]) DockerHostsQuery {
	return DockerHosts.Query(append(mods,
		sm.Where(DockerHosts.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) DockerHosts(mods ...bob.Mod[*dialect.SelectQuery]) DockerHostsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return DockerHosts.Query(append(mods,
		sm.Where(sqlite.Group(DockerHosts.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Maintenances starts a query for related objects on maintenance
func (o *User) Maintenances(mods ...bob.Mod[*dialect.SelectQuery]) MaintenancesQuery {
	return Maintenances.Query(append(mods,
		sm.Where(Maintenances.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) Maintenances(mods ...bob.Mod[*dialect.SelectQuery]) MaintenancesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Maintenances.Query(append(mods,
		sm.Where(sqlite.Group(Maintenances.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Monitors starts a query for related objects on monitor
func (o *User) Monitors(mods ...bob.Mod[*dialect.SelectQuery]) MonitorsQuery {
	return Monitors.Query(append(mods,
		sm.Where(Monitors.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) Monitors(mods ...bob.Mod[*dialect.SelectQuery]) MonitorsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Monitors.Query(append(mods,
		sm.Where(sqlite.Group(Monitors.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Notifications starts a query for related objects on notification
func (o *User) Notifications(mods ...bob.Mod[*dialect.SelectQuery]) NotificationsQuery {
	return Notifications.Query(append(mods,
		sm.Where(Notifications.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) Notifications(mods ...bob.Mod[*dialect.SelectQuery]) NotificationsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Notifications.Query(append(mods,
		sm.Where(sqlite.Group(Notifications.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Proxies starts a query for related objects on proxy
func (o *User) Proxies(mods ...bob.Mod[*dialect.SelectQuery]) ProxiesQuery {
	return Proxies.Query(append(mods,
		sm.Where(Proxies.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) Proxies(mods ...bob.Mod[*dialect.SelectQuery]) ProxiesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Proxies.Query(append(mods,
		sm.Where(sqlite.Group(Proxies.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// RemoteBrowsers starts a query for related objects on remote_browser
func (o *User) RemoteBrowsers(mods ...bob.Mod[*dialect.SelectQuery]) RemoteBrowsersQuery {
	return RemoteBrowsers.Query(append(mods,
		sm.Where(RemoteBrowsers.Columns.UserID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os UserSlice) RemoteBrowsers(mods ...bob.Mod[*dialect.SelectQuery]) RemoteBrowsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RemoteBrowsers.Query(append(mods,
		sm.Where(sqlite.Group(RemoteBrowsers.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserAPIKeys0(ctx context.Context, exec bob.Executor, apiKeys1 []*APIKeySetter, user0 *User) (APIKeySlice, error) {
	for i := range apiKeys1 {
		apiKeys1[i].UserID = omit.From(user0.ID)
	}

	ret, err := APIKeys.Insert(bob.ToMods(apiKeys1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserAPIKeys0: %w", err)
	}

	return ret, nil
}

func attachUserAPIKeys0(ctx context.Context, exec bob.Executor, count int, apiKeys1 APIKeySlice, user0 *User) (APIKeySlice, error) {
	setter := &APIKeySetter{
		UserID: omit.From(user0.ID),
	}

	err := apiKeys1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserAPIKeys0: %w", err)
	}

	return apiKeys1, nil
}

func (user0 *User) InsertAPIKeys(ctx context.Context, exec bob.Executor, related ...*APIKeySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	apiKeys1, err := insertUserAPIKeys0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.APIKeys = append(user0.R.APIKeys, apiKeys1...)

	for _, rel := range apiKeys1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachAPIKeys(ctx context.Context, exec bob.Executor, related ...*APIKey) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	apiKeys1 := APIKeySlice(related)

	_, err = attachUserAPIKeys0(ctx, exec, len(related), apiKeys1, user0)
	if err != nil {
		return err
	}

	user0.R.APIKeys = append(user0.R.APIKeys, apiKeys1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserDockerHosts0(ctx context.Context, exec bob.Executor, dockerHosts1 []*DockerHostSetter, user0 *User) (DockerHostSlice, error) {
	for i := range dockerHosts1 {
		dockerHosts1[i].UserID = omit.From(user0.ID)
	}

	ret, err := DockerHosts.Insert(bob.ToMods(dockerHosts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserDockerHosts0: %w", err)
	}

	return ret, nil
}

func attachUserDockerHosts0(ctx context.Context, exec bob.Executor, count int, dockerHosts1 DockerHostSlice, user0 *User) (DockerHostSlice, error) {
	setter := &DockerHostSetter{
		UserID: omit.From(user0.ID),
	}

	err := dockerHosts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserDockerHosts0: %w", err)
	}

	return dockerHosts1, nil
}

func (user0 *User) InsertDockerHosts(ctx context.Context, exec bob.Executor, related ...*DockerHostSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	dockerHosts1, err := insertUserDockerHosts0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.DockerHosts = append(user0.R.DockerHosts, dockerHosts1...)

	for _, rel := range dockerHosts1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachDockerHosts(ctx context.Context, exec bob.Executor, related ...*DockerHost) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	dockerHosts1 := DockerHostSlice(related)

	_, err = attachUserDockerHosts0(ctx, exec, len(related), dockerHosts1, user0)
	if err != nil {
		return err
	}

	user0.R.DockerHosts = append(user0.R.DockerHosts, dockerHosts1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserMaintenances0(ctx context.Context, exec bob.Executor, maintenances1 []*MaintenanceSetter, user0 *User) (MaintenanceSlice, error) {
	for i := range maintenances1 {
		maintenances1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Maintenances.Insert(bob.ToMods(maintenances1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserMaintenances0: %w", err)
	}

	return ret, nil
}

func attachUserMaintenances0(ctx context.Context, exec bob.Executor, count int, maintenances1 MaintenanceSlice, user0 *User) (MaintenanceSlice, error) {
	setter := &MaintenanceSetter{
		UserID: omit.From(user0.ID),
	}

	err := maintenances1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserMaintenances0: %w", err)
	}

	return maintenances1, nil
}

func (user0 *User) InsertMaintenances(ctx context.Context, exec bob.Executor, related ...*MaintenanceSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	maintenances1, err := insertUserMaintenances0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Maintenances = append(user0.R.Maintenances, maintenances1...)

	for _, rel := range maintenances1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachMaintenances(ctx context.Context, exec bob.Executor, related ...*Maintenance) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	maintenances1 := MaintenanceSlice(related)

	_, err = attachUserMaintenances0(ctx, exec, len(related), maintenances1, user0)
	if err != nil {
		return err
	}

	user0.R.Maintenances = append(user0.R.Maintenances, maintenances1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserMonitors0(ctx context.Context, exec bob.Executor, monitors1 []*MonitorSetter, user0 *User) (MonitorSlice, error) {
	for i := range monitors1 {
		monitors1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Monitors.Insert(bob.ToMods(monitors1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserMonitors0: %w", err)
	}

	return ret, nil
}

func attachUserMonitors0(ctx context.Context, exec bob.Executor, count int, monitors1 MonitorSlice, user0 *User) (MonitorSlice, error) {
	setter := &MonitorSetter{
		UserID: omit.From(user0.ID),
	}

	err := monitors1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserMonitors0: %w", err)
	}

	return monitors1, nil
}

func (user0 *User) InsertMonitors(ctx context.Context, exec bob.Executor, related ...*MonitorSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	monitors1, err := insertUserMonitors0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Monitors = append(user0.R.Monitors, monitors1...)

	for _, rel := range monitors1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachMonitors(ctx context.Context, exec bob.Executor, related ...*Monitor) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	monitors1 := MonitorSlice(related)

	_, err = attachUserMonitors0(ctx, exec, len(related), monitors1, user0)
	if err != nil {
		return err
	}

	user0.R.Monitors = append(user0.R.Monitors, monitors1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserNotifications0(ctx context.Context, exec bob.Executor, notifications1 []*NotificationSetter, user0 *User) (NotificationSlice, error) {
	for i := range notifications1 {
		notifications1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Notifications.Insert(bob.ToMods(notifications1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserNotifications0: %w", err)
	}

	return ret, nil
}

func attachUserNotifications0(ctx context.Context, exec bob.Executor, count int, notifications1 NotificationSlice, user0 *User) (NotificationSlice, error) {
	setter := &NotificationSetter{
		UserID: omit.From(user0.ID),
	}

	err := notifications1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserNotifications0: %w", err)
	}

	return notifications1, nil
}

func (user0 *User) InsertNotifications(ctx context.Context, exec bob.Executor, related ...*NotificationSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	notifications1, err := insertUserNotifications0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Notifications = append(user0.R.Notifications, notifications1...)

	for _, rel := range notifications1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachNotifications(ctx context.Context, exec bob.Executor, related ...*Notification) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	notifications1 := NotificationSlice(related)

	_, err = attachUserNotifications0(ctx, exec, len(related), notifications1, user0)
	if err != nil {
		return err
	}

	user0.R.Notifications = append(user0.R.Notifications, notifications1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserProxies0(ctx context.Context, exec bob.Executor, proxies1 []*ProxySetter, user0 *User) (ProxySlice, error) {
	for i := range proxies1 {
		proxies1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Proxies.Insert(bob.ToMods(proxies1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProxies0: %w", err)
	}

	return ret, nil
}

func attachUserProxies0(ctx context.Context, exec bob.Executor, count int, proxies1 ProxySlice, user0 *User) (ProxySlice, error) {
	setter := &ProxySetter{
		UserID: omit.From(user0.ID),
	}

	err := proxies1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProxies0: %w", err)
	}

	return proxies1, nil
}

func (user0 *User) InsertProxies(ctx context.Context, exec bob.Executor, related ...*ProxySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	proxies1, err := insertUserProxies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Proxies = append(user0.R.Proxies, proxies1...)

	for _, rel := range proxies1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachProxies(ctx context.Context, exec bob.Executor, related ...*Proxy) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	proxies1 := ProxySlice(related)

	_, err = attachUserProxies0(ctx, exec, len(related), proxies1, user0)
	if err != nil {
		return err
	}

	user0.R.Proxies = append(user0.R.Proxies, proxies1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserRemoteBrowsers0(ctx context.Context, exec bob.Executor, remoteBrowsers1 []*RemoteBrowserSetter, user0 *User) (RemoteBrowserSlice, error) {
	for i := range remoteBrowsers1 {
		remoteBrowsers1[i].UserID = omit.From(user0.ID)
	}

	ret, err := RemoteBrowsers.Insert(bob.ToMods(remoteBrowsers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserRemoteBrowsers0: %w", err)
	}

	return ret, nil
}

func attachUserRemoteBrowsers0(ctx context.Context, exec bob.Executor, count int, remoteBrowsers1 RemoteBrowserSlice, user0 *User) (RemoteBrowserSlice, error) {
	setter := &RemoteBrowserSetter{
		UserID: omit.From(user0.ID),
	}

	err := remoteBrowsers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserRemoteBrowsers0: %w", err)
	}

	return remoteBrowsers1, nil
}

func (user0 *User) InsertRemoteBrowsers(ctx context.Context, exec bob.Executor, related ...*RemoteBrowserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	remoteBrowsers1, err := insertUserRemoteBrowsers0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.RemoteBrowsers = append(user0.R.RemoteBrowsers, remoteBrowsers1...)

	for _, rel := range remoteBrowsers1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachRemoteBrowsers(ctx context.Context, exec bob.Executor, related ...*RemoteBrowser) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	remoteBrowsers1 := RemoteBrowserSlice(related)

	_, err = attachUserRemoteBrowsers0(ctx, exec, len(related), remoteBrowsers1, user0)
	if err != nil {
		return err
	}

	user0.R.RemoteBrowsers = append(user0.R.RemoteBrowsers, remoteBrowsers1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q sqlite.Filterable] struct {
	ID             sqlite.WhereMod[Q, string]
	Username       sqlite.WhereMod[Q, string]
	Password       sqlite.WhereMod[Q, string]
	Active         sqlite.WhereMod[Q, bool]
	Timezone       sqlite.WhereNullMod[Q, string]
	TwofaSecret    sqlite.WhereNullMod[Q, string]
	TwofaStatus    sqlite.WhereMod[Q, bool]
	TwofaLastToken sqlite.WhereNullMod[Q, string]
	CreatedDate    sqlite.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q sqlite.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:             sqlite.Where[Q, string](cols.ID),
		Username:       sqlite.Where[Q, string](cols.Username),
		Password:       sqlite.Where[Q, string](cols.Password),
		Active:         sqlite.Where[Q, bool](cols.Active),
		Timezone:       sqlite.WhereNull[Q, string](cols.Timezone),
		TwofaSecret:    sqlite.WhereNull[Q, string](cols.TwofaSecret),
		TwofaStatus:    sqlite.Where[Q, bool](cols.TwofaStatus),
		TwofaLastToken: sqlite.WhereNull[Q, string](cols.TwofaLastToken),
		CreatedDate:    sqlite.Where[Q, time.Time](cols.CreatedDate),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "APIKeys":
		rels, ok := retrieved.(APIKeySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.APIKeys = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "DockerHosts":
		rels, ok := retrieved.(DockerHostSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.DockerHosts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Maintenances":
		rels, ok := retrieved.(MaintenanceSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Maintenances = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Monitors":
		rels, ok := retrieved.(MonitorSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Monitors = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Notifications":
		rels, ok := retrieved.(NotificationSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Notifications = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Proxies":
		rels, ok := retrieved.(ProxySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Proxies = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "RemoteBrowsers":
		rels, ok := retrieved.(RemoteBrowserSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.RemoteBrowsers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	APIKeys        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	DockerHosts    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Maintenances   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Monitors       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Notifications  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Proxies        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	RemoteBrowsers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type APIKeysLoadInterface interface {
		LoadAPIKeys(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type DockerHostsLoadInterface interface {
		LoadDockerHosts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MaintenancesLoadInterface interface {
		LoadMaintenances(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MonitorsLoadInterface interface {
		LoadMonitors(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type NotificationsLoadInterface interface {
		LoadNotifications(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProxiesLoadInterface interface {
		LoadProxies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RemoteBrowsersLoadInterface interface {
		LoadRemoteBrowsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		APIKeys: thenLoadBuilder[Q](
			"APIKeys",
			func(ctx context.Context, exec bob.Executor, retrieved APIKeysLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAPIKeys(ctx, exec, mods...)
			},
		),
		DockerHosts: thenLoadBuilder[Q](
			"DockerHosts",
			func(ctx context.Context, exec bob.Executor, retrieved DockerHostsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadDockerHosts(ctx, exec, mods...)
			},
		),
		Maintenances: thenLoadBuilder[Q](
			"Maintenances",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenancesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMaintenances(ctx, exec, mods...)
			},
		),
		Monitors: thenLoadBuilder[Q](
			"Monitors",
			func(ctx context.Context, exec bob.Executor, retrieved MonitorsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMonitors(ctx, exec, mods...)
			},
		),
		Notifications: thenLoadBuilder[Q](
			"Notifications",
			func(ctx context.Context, exec bob.Executor, retrieved NotificationsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadNotifications(ctx, exec, mods...)
			},
		),
		Proxies: thenLoadBuilder[Q](
			"Proxies",
			func(ctx context.Context, exec bob.Executor, retrieved ProxiesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProxies(ctx, exec, mods...)
			},
		),
		RemoteBrowsers: thenLoadBuilder[Q](
			"RemoteBrowsers",
			func(ctx context.Context, exec bob.Executor, retrieved RemoteBrowsersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRemoteBrowsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadAPIKeys loads the user's APIKeys into the .R struct
func (o *User) LoadAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.APIKeys = nil

	related, err := o.APIKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.APIKeys = related
	return nil
}

// LoadAPIKeys loads the user's APIKeys into the .R struct
func (os UserSlice) LoadAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	apiKeys, err := os.APIKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.APIKeys = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range apiKeys {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.APIKeys = append(o.R.APIKeys, rel)
		}
	}

	return nil
}

// LoadDockerHosts loads the user's DockerHosts into the .R struct
func (o *User) LoadDockerHosts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.DockerHosts = nil

	related, err := o.DockerHosts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.DockerHosts = related
	return nil
}

// LoadDockerHosts loads the user's DockerHosts into the .R struct
func (os UserSlice) LoadDockerHosts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	dockerHosts, err := os.DockerHosts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.DockerHosts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range dockerHosts {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.DockerHosts = append(o.R.DockerHosts, rel)
		}
	}

	return nil
}

// LoadMaintenances loads the user's Maintenances into the .R struct
func (o *User) LoadMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Maintenances = nil

	related, err := o.Maintenances(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Maintenances = related
	return nil
}

// LoadMaintenances loads the user's Maintenances into the .R struct
func (os UserSlice) LoadMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	maintenances, err := os.Maintenances(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Maintenances = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range maintenances {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Maintenances = append(o.R.Maintenances, rel)
		}
	}

	return nil
}

// LoadMonitors loads the user's Monitors into the .R struct
func (o *User) LoadMonitors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Monitors = nil

	related, err := o.Monitors(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Monitors = related
	return nil
}

// LoadMonitors loads the user's Monitors into the .R struct
func (os UserSlice) LoadMonitors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	monitors, err := os.Monitors(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Monitors = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range monitors {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Monitors = append(o.R.Monitors, rel)
		}
	}

	return nil
}

// LoadNotifications loads the user's Notifications into the .R struct
func (o *User) LoadNotifications(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Notifications = nil

	related, err := o.Notifications(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Notifications = related
	return nil
}

// LoadNotifications loads the user's Notifications into the .R struct
func (os UserSlice) LoadNotifications(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	notifications, err := os.Notifications(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Notifications = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range notifications {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Notifications = append(o.R.Notifications, rel)
		}
	}

	return nil
}

// LoadProxies loads the user's Proxies into the .R struct
func (o *User) LoadProxies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Proxies = nil

	related, err := o.Proxies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Proxies = related
	return nil
}

// LoadProxies loads the user's Proxies into the .R struct
func (os UserSlice) LoadProxies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	proxies, err := os.Proxies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Proxies = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range proxies {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Proxies = append(o.R.Proxies, rel)
		}
	}

	return nil
}

// LoadRemoteBrowsers loads the user's RemoteBrowsers into the .R struct
func (o *User) LoadRemoteBrowsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RemoteBrowsers = nil

	related, err := o.RemoteBrowsers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.RemoteBrowsers = related
	return nil
}

// LoadRemoteBrowsers loads the user's RemoteBrowsers into the .R struct
func (os UserSlice) LoadRemoteBrowsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	remoteBrowsers, err := os.RemoteBrowsers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.RemoteBrowsers = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range remoteBrowsers {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.RemoteBrowsers = append(o.R.RemoteBrowsers, rel)
		}
	}

	return nil
}

// userC is where relationship counts are stored.
type userC struct {
	APIKeys        *int64
	DockerHosts    *int64
	Maintenances   *int64
	Monitors       *int64
	Notifications  *int64
	Proxies        *int64
	RemoteBrowsers *int64
}

// PreloadCount sets a count in the C struct by name
func (o *User) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "APIKeys":
		o.C.APIKeys = &count
	case "DockerHosts":
		o.C.DockerHosts = &count
	case "Maintenances":
		o.C.Maintenances = &count
	case "Monitors":
		o.C.Monitors = &count
	case "Notifications":
		o.C.Notifications = &count
	case "Proxies":
		o.C.Proxies = &count
	case "RemoteBrowsers":
		o.C.RemoteBrowsers = &count
	}
	return nil
}

type userCountPreloader struct {
	APIKeys        func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	DockerHosts    func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	Maintenances   func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	Monitors       func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	Notifications  func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	Proxies        func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
	RemoteBrowsers func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
}

func buildUserCountPreloader() userCountPreloader {
	return userCountPreloader{
		APIKeys: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("APIKeys", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(APIKeys.Name()),
					sm.Where(sqlite.Quote(APIKeys.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		DockerHosts: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("DockerHosts", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(DockerHosts.Name()),
					sm.Where(sqlite.Quote(DockerHosts.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		Maintenances: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("Maintenances", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(Maintenances.Name()),
					sm.Where(sqlite.Quote(Maintenances.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		Monitors: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("Monitors", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(Monitors.Name()),
					sm.Where(sqlite.Quote(Monitors.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		Notifications: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("Notifications", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(Notifications.Name()),
					sm.Where(sqlite.Quote(Notifications.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		Proxies: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("Proxies", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(Proxies.Name()),
					sm.Where(sqlite.Quote(Proxies.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
		RemoteBrowsers: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*User]("RemoteBrowsers", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(RemoteBrowsers.Name()),
					sm.Where(sqlite.Quote(RemoteBrowsers.Alias(), "user_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
	}
}

type userCountThenLoader[Q orm.Loadable] struct {
	APIKeys        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	DockerHosts    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Maintenances   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Monitors       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Notifications  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Proxies        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	RemoteBrowsers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserCountThenLoader[Q orm.Loadable]() userCountThenLoader[Q] {
	type APIKeysCountInterface interface {
		LoadCountAPIKeys(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type DockerHostsCountInterface interface {
		LoadCountDockerHosts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MaintenancesCountInterface interface {
		LoadCountMaintenances(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MonitorsCountInterface interface {
		LoadCountMonitors(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type NotificationsCountInterface interface {
		LoadCountNotifications(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProxiesCountInterface interface {
		LoadCountProxies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RemoteBrowsersCountInterface interface {
		LoadCountRemoteBrowsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userCountThenLoader[Q]{
		APIKeys: countThenLoadBuilder[Q](
			"APIKeys",
			func(ctx context.Context, exec bob.Executor, retrieved APIKeysCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountAPIKeys(ctx, exec, mods...)
			},
		),
		DockerHosts: countThenLoadBuilder[Q](
			"DockerHosts",
			func(ctx context.Context, exec bob.Executor, retrieved DockerHostsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountDockerHosts(ctx, exec, mods...)
			},
		),
		Maintenances: countThenLoadBuilder[Q](
			"Maintenances",
			func(ctx context.Context, exec bob.Executor, retrieved MaintenancesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMaintenances(ctx, exec, mods...)
			},
		),
		Monitors: countThenLoadBuilder[Q](
			"Monitors",
			func(ctx context.Context, exec bob.Executor, retrieved MonitorsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMonitors(ctx, exec, mods...)
			},
		),
		Notifications: countThenLoadBuilder[Q](
			"Notifications",
			func(ctx context.Context, exec bob.Executor, retrieved NotificationsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountNotifications(ctx, exec, mods...)
			},
		),
		Proxies: countThenLoadBuilder[Q](
			"Proxies",
			func(ctx context.Context, exec bob.Executor, retrieved ProxiesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountProxies(ctx, exec, mods...)
			},
		),
		RemoteBrowsers: countThenLoadBuilder[Q](
			"RemoteBrowsers",
			func(ctx context.Context, exec bob.Executor, retrieved RemoteBrowsersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountRemoteBrowsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountAPIKeys loads the count of APIKeys into the C struct
func (o *User) LoadCountAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.APIKeys(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.APIKeys = &count
	return nil
}

// LoadCountAPIKeys loads the count of APIKeys for a slice in a single batch query
func (os UserSlice) LoadCountAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			APIKeys.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(APIKeys.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(APIKeys.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(APIKeys.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.APIKeys = &count
	}

	return nil
}

// LoadCountDockerHosts loads the count of DockerHosts into the C struct
func (o *User) LoadCountDockerHosts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.DockerHosts(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.DockerHosts = &count
	return nil
}

// LoadCountDockerHosts loads the count of DockerHosts for a slice in a single batch query
func (os UserSlice) LoadCountDockerHosts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			DockerHosts.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(DockerHosts.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(DockerHosts.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(DockerHosts.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.DockerHosts = &count
	}

	return nil
}

// LoadCountMaintenances loads the count of Maintenances into the C struct
func (o *User) LoadCountMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Maintenances(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Maintenances = &count
	return nil
}

// LoadCountMaintenances loads the count of Maintenances for a slice in a single batch query
func (os UserSlice) LoadCountMaintenances(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Maintenances.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Maintenances.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Maintenances.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Maintenances.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Maintenances = &count
	}

	return nil
}

// LoadCountMonitors loads the count of Monitors into the C struct
func (o *User) LoadCountMonitors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Monitors(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Monitors = &count
	return nil
}

// LoadCountMonitors loads the count of Monitors for a slice in a single batch query
func (os UserSlice) LoadCountMonitors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Monitors.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Monitors.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Monitors.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Monitors.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Monitors = &count
	}

	return nil
}

// LoadCountNotifications loads the count of Notifications into the C struct
func (o *User) LoadCountNotifications(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Notifications(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Notifications = &count
	return nil
}

// LoadCountNotifications loads the count of Notifications for a slice in a single batch query
func (os UserSlice) LoadCountNotifications(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Notifications.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Notifications.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Notifications.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Notifications.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Notifications = &count
	}

	return nil
}

// LoadCountProxies loads the count of Proxies into the C struct
func (o *User) LoadCountProxies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Proxies(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Proxies = &count
	return nil
}

// LoadCountProxies loads the count of Proxies for a slice in a single batch query
func (os UserSlice) LoadCountProxies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Proxies.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Proxies.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Proxies.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Proxies.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Proxies = &count
	}

	return nil
}

// LoadCountRemoteBrowsers loads the count of RemoteBrowsers into the C struct
func (o *User) LoadCountRemoteBrowsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.RemoteBrowsers(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.RemoteBrowsers = &count
	return nil
}

// LoadCountRemoteBrowsers loads the count of RemoteBrowsers for a slice in a single batch query
func (os UserSlice) LoadCountRemoteBrowsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			RemoteBrowsers.Columns.UserID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(RemoteBrowsers.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(RemoteBrowsers.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(RemoteBrowsers.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.RemoteBrowsers = &count
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ            string
	APIKeys        modAs[Q, apiKeyColumns]
	DockerHosts    modAs[Q, dockerHostColumns]
	Maintenances   modAs[Q, maintenanceColumns]
	Monitors       modAs[Q, monitorColumns]
	Notifications  modAs[Q, notificationColumns]
	Proxies        modAs[Q, proxyColumns]
	RemoteBrowsers modAs[Q, remoteBrowserColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		APIKeys: modAs[Q, apiKeyColumns]{
			c: APIKeys.Columns,
			f: func(to apiKeyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, APIKeys.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		DockerHosts: modAs[Q, dockerHostColumns]{
			c: DockerHosts.Columns,
			f: func(to dockerHostColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, DockerHosts.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Maintenances: modAs[Q, maintenanceColumns]{
			c: Maintenances.Columns,
			f: func(to maintenanceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Maintenances.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Monitors: modAs[Q, monitorColumns]{
			c: Monitors.Columns,
			f: func(to monitorColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Monitors.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Notifications: modAs[Q, notificationColumns]{
			c: Notifications.Columns,
			f: func(to notificationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Notifications.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Proxies: modAs[Q, proxyColumns]{
			c: Proxies.Columns,
			f: func(to proxyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Proxies.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		RemoteBrowsers: modAs[Q, remoteBrowserColumns]{
			c: RemoteBrowsers.Columns,
			f: func(to remoteBrowserColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RemoteBrowsers.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
