// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Incidents = Table[
	incidentColumns,
	incidentIndexes,
	incidentForeignKeys,
	incidentUniques,
	incidentChecks,
]{
	Schema: "",
	Name:   "incident",
	Columns: incidentColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "VARCHAR(200)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Content: column{
			Name:      "content",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Style: column{
			Name:      "style",
			DBType:    "VARCHAR(10)",
			Default:   "'info'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedDate: column{
			Name:      "created_date",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastUpdatedDate: column{
			Name:      "last_updated_date",
			DBType:    "TIMESTAMP",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Pin: column{
			Name:      "pin",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Active: column{
			Name:      "active",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StatusPageID: column{
			Name:      "status_page_id",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: incidentIndexes{
		SqliteAutoindexIncident1: index{
			Type: "pk",
			Name: "sqlite_autoindex_incident_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_incident",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: incidentForeignKeys{
		FKIncident0: foreignKey{
			constraint: constraint{
				Name:    "fk_incident_0",
				Columns: []string{"status_page_id"},
				Comment: "",
			},
			ForeignTable:   "status_page",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type incidentColumns struct {
	ID              column
	Title           column
	Content         column
	Style           column
	CreatedDate     column
	LastUpdatedDate column
	Pin             column
	Active          column
	StatusPageID    column
}

func (c incidentColumns) AsSlice() []column {
	return []column{
		c.ID, c.Title, c.Content, c.Style, c.CreatedDate, c.LastUpdatedDate, c.Pin, c.Active, c.StatusPageID,
	}
}

type incidentIndexes struct {
	SqliteAutoindexIncident1 index
}

func (i incidentIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexIncident1,
	}
}

type incidentForeignKeys struct {
	FKIncident0 foreignKey
}

func (f incidentForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKIncident0,
	}
}

type incidentUniques struct{}

func (u incidentUniques) AsSlice() []constraint {
	return []constraint{}
}

type incidentChecks struct{}

func (c incidentChecks) AsSlice() []check {
	return []check{}
}
