// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var MaintenanceStatusPages = Table[
	maintenanceStatusPageColumns,
	maintenanceStatusPageIndexes,
	maintenanceStatusPageForeignKeys,
	maintenanceStatusPageUniques,
	maintenanceStatusPageChecks,
]{
	Schema: "",
	Name:   "maintenance_status_page",
	Columns: maintenanceStatusPageColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StatusPageID: column{
			Name:      "status_page_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MaintenanceID: column{
			Name:      "maintenance_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: maintenanceStatusPageIndexes{
		SqliteAutoindexMaintenanceStatusPage1: index{
			Type: "pk",
			Name: "sqlite_autoindex_maintenance_status_page_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_maintenance_status_page",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: maintenanceStatusPageForeignKeys{
		FKMaintenanceStatusPage0: foreignKey{
			constraint: constraint{
				Name:    "fk_maintenance_status_page_0",
				Columns: []string{"maintenance_id"},
				Comment: "",
			},
			ForeignTable:   "maintenance",
			ForeignColumns: []string{"id"},
		},
		FKMaintenanceStatusPage1: foreignKey{
			constraint: constraint{
				Name:    "fk_maintenance_status_page_1",
				Columns: []string{"status_page_id"},
				Comment: "",
			},
			ForeignTable:   "status_page",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type maintenanceStatusPageColumns struct {
	ID            column
	StatusPageID  column
	MaintenanceID column
}

func (c maintenanceStatusPageColumns) AsSlice() []column {
	return []column{
		c.ID, c.StatusPageID, c.MaintenanceID,
	}
}

type maintenanceStatusPageIndexes struct {
	SqliteAutoindexMaintenanceStatusPage1 index
}

func (i maintenanceStatusPageIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexMaintenanceStatusPage1,
	}
}

type maintenanceStatusPageForeignKeys struct {
	FKMaintenanceStatusPage0 foreignKey
	FKMaintenanceStatusPage1 foreignKey
}

func (f maintenanceStatusPageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKMaintenanceStatusPage0, f.FKMaintenanceStatusPage1,
	}
}

type maintenanceStatusPageUniques struct{}

func (u maintenanceStatusPageUniques) AsSlice() []constraint {
	return []constraint{}
}

type maintenanceStatusPageChecks struct{}

func (c maintenanceStatusPageChecks) AsSlice() []check {
	return []check{}
}
