// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var MaintenanceTimeslots = Table[
	maintenanceTimeslotColumns,
	maintenanceTimeslotIndexes,
	maintenanceTimeslotForeignKeys,
	maintenanceTimeslotUniques,
	maintenanceTimeslotChecks,
]{
	Schema: "",
	Name:   "maintenance_timeslot",
	Columns: maintenanceTimeslotColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MaintenanceID: column{
			Name:      "maintenance_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartDate: column{
			Name:      "start_date",
			DBType:    "TIMESTAMP",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EndDate: column{
			Name:      "end_date",
			DBType:    "TIMESTAMP",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		GeneratedNext: column{
			Name:      "generated_next",
			DBType:    "BOOLEAN",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: maintenanceTimeslotIndexes{
		IdxMaintenanceTimeslotRange: index{
			Type: "c",
			Name: "idx_maintenance_timeslot_range",
			Columns: []indexColumn{
				{
					Name:         "maintenance_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "start_date",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "end_date",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		IdxMaintenanceTimeslotMaintenance: index{
			Type: "c",
			Name: "idx_maintenance_timeslot_maintenance",
			Columns: []indexColumn{
				{
					Name:         "maintenance_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexMaintenanceTimeslot1: index{
			Type: "pk",
			Name: "sqlite_autoindex_maintenance_timeslot_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_maintenance_timeslot",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: maintenanceTimeslotForeignKeys{
		FKMaintenanceTimeslot0: foreignKey{
			constraint: constraint{
				Name:    "fk_maintenance_timeslot_0",
				Columns: []string{"maintenance_id"},
				Comment: "",
			},
			ForeignTable:   "maintenance",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type maintenanceTimeslotColumns struct {
	ID            column
	MaintenanceID column
	StartDate     column
	EndDate       column
	GeneratedNext column
}

func (c maintenanceTimeslotColumns) AsSlice() []column {
	return []column{
		c.ID, c.MaintenanceID, c.StartDate, c.EndDate, c.GeneratedNext,
	}
}

type maintenanceTimeslotIndexes struct {
	IdxMaintenanceTimeslotRange         index
	IdxMaintenanceTimeslotMaintenance   index
	SqliteAutoindexMaintenanceTimeslot1 index
}

func (i maintenanceTimeslotIndexes) AsSlice() []index {
	return []index{
		i.IdxMaintenanceTimeslotRange, i.IdxMaintenanceTimeslotMaintenance, i.SqliteAutoindexMaintenanceTimeslot1,
	}
}

type maintenanceTimeslotForeignKeys struct {
	FKMaintenanceTimeslot0 foreignKey
}

func (f maintenanceTimeslotForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKMaintenanceTimeslot0,
	}
}

type maintenanceTimeslotUniques struct{}

func (u maintenanceTimeslotUniques) AsSlice() []constraint {
	return []constraint{}
}

type maintenanceTimeslotChecks struct{}

func (c maintenanceTimeslotChecks) AsSlice() []check {
	return []check{}
}
