// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Maintenances = Table[
	maintenanceColumns,
	maintenanceIndexes,
	maintenanceForeignKeys,
	maintenanceUniques,
	maintenanceChecks,
]{
	Schema: "",
	Name:   "maintenance",
	Columns: maintenanceColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "VARCHAR(150)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Active: column{
			Name:      "active",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Strategy: column{
			Name:      "strategy",
			DBType:    "VARCHAR(30)",
			Default:   "'manual'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartDate: column{
			Name:      "start_date",
			DBType:    "TIMESTAMP",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		EndDate: column{
			Name:      "end_date",
			DBType:    "TIMESTAMP",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		StartTime: column{
			Name:      "start_time",
			DBType:    "VARCHAR(5)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		EndTime: column{
			Name:      "end_time",
			DBType:    "VARCHAR(5)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Weekdays: column{
			Name:      "weekdays",
			DBType:    "TEXT",
			Default:   "'[]'",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DaysOfMonth: column{
			Name:      "days_of_month",
			DBType:    "TEXT",
			Default:   "'[]'",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IntervalDay: column{
			Name:      "interval_day",
			DBType:    "INTEGER",
			Default:   "1",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Cron: column{
			Name:      "cron",
			DBType:    "VARCHAR(100)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Timezone: column{
			Name:      "timezone",
			DBType:    "VARCHAR(64)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Duration: column{
			Name:      "duration",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: maintenanceIndexes{
		IdxMaintenanceUserID: index{
			Type: "c",
			Name: "idx_maintenance_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		IdxMaintenanceActive: index{
			Type: "c",
			Name: "idx_maintenance_active",
			Columns: []indexColumn{
				{
					Name:         "active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexMaintenance1: index{
			Type: "pk",
			Name: "sqlite_autoindex_maintenance_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_maintenance",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: maintenanceForeignKeys{
		FKMaintenance0: foreignKey{
			constraint: constraint{
				Name:    "fk_maintenance_0",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "user",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type maintenanceColumns struct {
	ID          column
	Title       column
	Description column
	UserID      column
	Active      column
	Strategy    column
	StartDate   column
	EndDate     column
	StartTime   column
	EndTime     column
	Weekdays    column
	DaysOfMonth column
	IntervalDay column
	Cron        column
	Timezone    column
	Duration    column
}

func (c maintenanceColumns) AsSlice() []column {
	return []column{
		c.ID, c.Title, c.Description, c.UserID, c.Active, c.Strategy, c.StartDate, c.EndDate, c.StartTime, c.EndTime, c.Weekdays, c.DaysOfMonth, c.IntervalDay, c.Cron, c.Timezone, c.Duration,
	}
}

type maintenanceIndexes struct {
	IdxMaintenanceUserID        index
	IdxMaintenanceActive        index
	SqliteAutoindexMaintenance1 index
}

func (i maintenanceIndexes) AsSlice() []index {
	return []index{
		i.IdxMaintenanceUserID, i.IdxMaintenanceActive, i.SqliteAutoindexMaintenance1,
	}
}

type maintenanceForeignKeys struct {
	FKMaintenance0 foreignKey
}

func (f maintenanceForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKMaintenance0,
	}
}

type maintenanceUniques struct{}

func (u maintenanceUniques) AsSlice() []constraint {
	return []constraint{}
}

type maintenanceChecks struct{}

func (c maintenanceChecks) AsSlice() []check {
	return []check{}
}
