// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Proxies = Table[
	proxyColumns,
	proxyIndexes,
	proxyForeignKeys,
	proxyUniques,
	proxyChecks,
]{
	Schema: "",
	Name:   "proxy",
	Columns: proxyColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Protocol: column{
			Name:      "protocol",
			DBType:    "VARCHAR(10)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Host: column{
			Name:      "host",
			DBType:    "VARCHAR(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Port: column{
			Name:      "port",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Auth: column{
			Name:      "auth",
			DBType:    "BOOLEAN",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Username: column{
			Name:      "username",
			DBType:    "VARCHAR(255)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "VARCHAR(255)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Active: column{
			Name:      "active",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Default: column{
			Name:      "default",
			DBType:    "BOOLEAN",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedDate: column{
			Name:      "created_date",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: proxyIndexes{
		SqliteAutoindexProxy1: index{
			Type: "pk",
			Name: "sqlite_autoindex_proxy_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_proxy",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: proxyForeignKeys{
		FKProxy0: foreignKey{
			constraint: constraint{
				Name:    "fk_proxy_0",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "user",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type proxyColumns struct {
	ID          column
	UserID      column
	Protocol    column
	Host        column
	Port        column
	Auth        column
	Username    column
	Password    column
	Active      column
	Default     column
	CreatedDate column
}

func (c proxyColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Protocol, c.Host, c.Port, c.Auth, c.Username, c.Password, c.Active, c.Default, c.CreatedDate,
	}
}

type proxyIndexes struct {
	SqliteAutoindexProxy1 index
}

func (i proxyIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexProxy1,
	}
}

type proxyForeignKeys struct {
	FKProxy0 foreignKey
}

func (f proxyForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKProxy0,
	}
}

type proxyUniques struct{}

func (u proxyUniques) AsSlice() []constraint {
	return []constraint{}
}

type proxyChecks struct{}

func (c proxyChecks) AsSlice() []check {
	return []check{}
}
