// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Sessions = Table[
	sessionColumns,
	sessionIndexes,
	sessionForeignKeys,
	sessionUniques,
	sessionChecks,
]{
	Schema: "",
	Name:   "session",
	Columns: sessionColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Token: column{
			Name:      "token",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiresAt: column{
			Name:      "expires_at",
			DBType:    "TIMESTAMP",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sessionIndexes{
		IdxSessionUserID: index{
			Type: "c",
			Name: "idx_session_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		IdxSessionToken: index{
			Type: "c",
			Name: "idx_session_token",
			Columns: []indexColumn{
				{
					Name:         "token",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSession2: index{
			Type: "u",
			Name: "sqlite_autoindex_session_2",
			Columns: []indexColumn{
				{
					Name:         "token",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSession1: index{
			Type: "pk",
			Name: "sqlite_autoindex_session_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_session",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: sessionUniques{
		SqliteAutoindexSession2: constraint{
			Name:    "sqlite_autoindex_session_2",
			Columns: []string{"token"},
			Comment: "",
		},
	},

	Comment: "",
}

type sessionColumns struct {
	ID        column
	UserID    column
	Token     column
	ExpiresAt column
	CreatedAt column
}

func (c sessionColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Token, c.ExpiresAt, c.CreatedAt,
	}
}

type sessionIndexes struct {
	IdxSessionUserID        index
	IdxSessionToken         index
	SqliteAutoindexSession2 index
	SqliteAutoindexSession1 index
}

func (i sessionIndexes) AsSlice() []index {
	return []index{
		i.IdxSessionUserID, i.IdxSessionToken, i.SqliteAutoindexSession2, i.SqliteAutoindexSession1,
	}
}

type sessionForeignKeys struct{}

func (f sessionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type sessionUniques struct {
	SqliteAutoindexSession2 constraint
}

func (u sessionUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexSession2,
	}
}

type sessionChecks struct{}

func (c sessionChecks) AsSlice() []check {
	return []check{}
}
