// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var StatusPages = Table[
	statusPageColumns,
	statusPageIndexes,
	statusPageForeignKeys,
	statusPageUniques,
	statusPageChecks,
]{
	Schema: "",
	Name:   "status_page",
	Columns: statusPageColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Slug: column{
			Name:      "slug",
			DBType:    "VARCHAR(128)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "VARCHAR(150)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Icon: column{
			Name:      "icon",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Theme: column{
			Name:      "theme",
			DBType:    "VARCHAR(10)",
			Default:   "'auto'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Published: column{
			Name:      "published",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SearchEngineIndex: column{
			Name:      "search_engine_index",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ShowTags: column{
			Name:      "show_tags",
			DBType:    "BOOLEAN",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "VARCHAR(255)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedDate: column{
			Name:      "created_date",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ModifiedDate: column{
			Name:      "modified_date",
			DBType:    "TIMESTAMP",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FooterText: column{
			Name:      "footer_text",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CustomCSS: column{
			Name:      "custom_css",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ShowPoweredBy: column{
			Name:      "show_powered_by",
			DBType:    "BOOLEAN",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ShowCertificateExpiry: column{
			Name:      "show_certificate_expiry",
			DBType:    "BOOLEAN",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GoogleAnalyticsTagID: column{
			Name:      "google_analytics_tag_id",
			DBType:    "VARCHAR(30)",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: statusPageIndexes{
		SqliteAutoindexStatusPage2: index{
			Type: "u",
			Name: "sqlite_autoindex_status_page_2",
			Columns: []indexColumn{
				{
					Name:         "slug",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexStatusPage1: index{
			Type: "pk",
			Name: "sqlite_autoindex_status_page_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_status_page",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: statusPageUniques{
		SqliteAutoindexStatusPage2: constraint{
			Name:    "sqlite_autoindex_status_page_2",
			Columns: []string{"slug"},
			Comment: "",
		},
	},

	Comment: "",
}

type statusPageColumns struct {
	ID                    column
	Slug                  column
	Title                 column
	Description           column
	Icon                  column
	Theme                 column
	Published             column
	SearchEngineIndex     column
	ShowTags              column
	Password              column
	CreatedDate           column
	ModifiedDate          column
	FooterText            column
	CustomCSS             column
	ShowPoweredBy         column
	ShowCertificateExpiry column
	GoogleAnalyticsTagID  column
}

func (c statusPageColumns) AsSlice() []column {
	return []column{
		c.ID, c.Slug, c.Title, c.Description, c.Icon, c.Theme, c.Published, c.SearchEngineIndex, c.ShowTags, c.Password, c.CreatedDate, c.ModifiedDate, c.FooterText, c.CustomCSS, c.ShowPoweredBy, c.ShowCertificateExpiry, c.GoogleAnalyticsTagID,
	}
}

type statusPageIndexes struct {
	SqliteAutoindexStatusPage2 index
	SqliteAutoindexStatusPage1 index
}

func (i statusPageIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexStatusPage2, i.SqliteAutoindexStatusPage1,
	}
}

type statusPageForeignKeys struct{}

func (f statusPageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type statusPageUniques struct {
	SqliteAutoindexStatusPage2 constraint
}

func (u statusPageUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexStatusPage2,
	}
}

type statusPageChecks struct{}

func (c statusPageChecks) AsSlice() []check {
	return []check{}
}
