// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var StatusPageCnames = Table[
	statusPageCnameColumns,
	statusPageCnameIndexes,
	statusPageCnameForeignKeys,
	statusPageCnameUniques,
	statusPageCnameChecks,
]{
	Schema: "",
	Name:   "status_page_cname",
	Columns: statusPageCnameColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StatusPageID: column{
			Name:      "status_page_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Domain: column{
			Name:      "domain",
			DBType:    "VARCHAR(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: statusPageCnameIndexes{
		SqliteAutoindexStatusPageCname1: index{
			Type: "pk",
			Name: "sqlite_autoindex_status_page_cname_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_status_page_cname",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: statusPageCnameForeignKeys{
		FKStatusPageCname0: foreignKey{
			constraint: constraint{
				Name:    "fk_status_page_cname_0",
				Columns: []string{"status_page_id"},
				Comment: "",
			},
			ForeignTable:   "status_page",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type statusPageCnameColumns struct {
	ID           column
	StatusPageID column
	Domain       column
}

func (c statusPageCnameColumns) AsSlice() []column {
	return []column{
		c.ID, c.StatusPageID, c.Domain,
	}
}

type statusPageCnameIndexes struct {
	SqliteAutoindexStatusPageCname1 index
}

func (i statusPageCnameIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexStatusPageCname1,
	}
}

type statusPageCnameForeignKeys struct {
	FKStatusPageCname0 foreignKey
}

func (f statusPageCnameForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKStatusPageCname0,
	}
}

type statusPageCnameUniques struct{}

func (u statusPageCnameUniques) AsSlice() []constraint {
	return []constraint{}
}

type statusPageCnameChecks struct{}

func (c statusPageCnameChecks) AsSlice() []check {
	return []check{}
}
