package monitor

import "time"

type Monitor struct {
	ID                   string    `db:"id"`
	Name                 string    `db:"name"`
	Active               bool      `db:"active"`
	UserID               string    `db:"user_id"`
	Interval             int       `db:"interval"`
	URL                  string    `db:"url"`
	Type                 string    `db:"type"`
	Weight               int       `db:"weight"`
	Hostname             string    `db:"hostname"`
	Port                 *int      `db:"port"`
	CreatedDate          time.Time `db:"created_date"`
	Keyword              string    `db:"keyword"`
	MaxRetries           int       `db:"maxretries"`
	IgnoreTLS            bool      `db:"ignore_tls"`
	UpsideDown           bool      `db:"upside_down"`
	MaxRedirects         int       `db:"maxredirects"`
	AcceptedStatusCodes  string    `db:"accepted_statuscodes_json"`
	DNSResolveType       string    `db:"dns_resolve_type"`
	DNSResolveServer     string    `db:"dns_resolve_server"`
	DNSLastResult        string    `db:"dns_last_result"`
	RetryInterval        int       `db:"retry_interval"`
	PushToken            string    `db:"push_token"`
	Method               string    `db:"method"`
	Body                 string    `db:"body"`
	Headers              string    `db:"headers"`
	BasicAuthUser        string    `db:"basic_auth_user"`
	BasicAuthPass        string    `db:"basic_auth_pass"`
	ProxyID              *string   `db:"proxy_id"`
	Description          string    `db:"description"`
	TLSCert              string    `db:"tls_cert"`
	TLSKey               string    `db:"tls_key"`
	TLSCA                string    `db:"tls_ca"`
	MQTTTopic            string    `db:"mqtt_topic"`
	MQTTSuccessMessage   string    `db:"mqtt_success_message"`
	MQTTUsername         string    `db:"mqtt_username"`
	MQTTPassword         string    `db:"mqtt_password"`
	DatabaseQuery        string    `db:"database_query"`
	AuthMethod           string    `db:"auth_method"`
	AuthWorkstation      string    `db:"auth_workstation"`
	AuthDomain           string    `db:"auth_domain"`
	GRPCUrl              string    `db:"grpc_url"`
	GRPCProtobuf         string    `db:"grpc_protobuf"`
	GRPCServiceName      string    `db:"grpc_service_name"`
	GRPCMethod           string    `db:"grpc_method"`
	GRPCBody             string    `db:"grpc_body"`
	GRPCMetadata         string    `db:"grpc_metadata"`
	GRPCEnableTLS        bool      `db:"grpc_enable_tls"`
	RadiusUsername       string    `db:"radius_username"`
	RadiusPassword       string    `db:"radius_password"`
	RadiusSecret         string    `db:"radius_secret"`
	RadiusCalledStation  string    `db:"radius_called_station_id"`
	RadiusCalling        string    `db:"radius_calling_station_id"`
	GameName             string    `db:"game"`
	HTTPBodyEncoding     string    `db:"http_body_encoding"`
	Timeout              int       `db:"timeout"`
	InvertKeyword        bool      `db:"invert_keyword"`
	JsonPath             string    `db:"json_path"`
	ExpectedValue        string    `db:"expected_value"`
	ExpiryNotification   bool      `db:"expiry_notification"`
	PacketSize           int       `db:"packet_size"`
	ResendInterval       int       `db:"resend_interval"`
	KafkaProducerTopic   string    `db:"kafka_producer_topic"`
	KafkaProducerBrokers string    `db:"kafka_producer_brokers"`
	KafkaProducerSSL     bool      `db:"kafka_producer_ssl"`
	KafkaProducerMessage string    `db:"kafka_producer_message"`
	RemoteBrowser        *string   `db:"remote_browser"`
	GroupTagIDs          string    `db:"group_tag_ids_json"`
}
