// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	"github.com/google/uuid"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	APIKeyHandler
	AuthHandler
	BadgeHandler
	EventHandler
	HeartbeatHandler
	IncidentHandler
	MaintenanceHandler
	MonitorHandler
	NotificationHandler
	ProxyHandler
	PushHandler
	SettingsHandler
	StatusPageHandler
	SystemHandler
	TagHandler
}

// APIKeyHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: APIKey
type APIKeyHandler interface {
	// CreateAPIKey implements createAPIKey operation.
	//
	// Create a new API key.
	//
	// POST /api-keys
	CreateAPIKey(ctx context.Context, req *APIKeyInput) (*CreateAPIKeyCreated, error)
	// DeleteAPIKey implements deleteAPIKey operation.
	//
	// Delete an API key.
	//
	// DELETE /api-keys/{keyId}
	DeleteAPIKey(ctx context.Context, params DeleteAPIKeyParams) error
	// DisableAPIKey implements disableAPIKey operation.
	//
	// Disable an API key.
	//
	// POST /api-keys/{keyId}/disable
	DisableAPIKey(ctx context.Context, params DisableAPIKeyParams) (*MessageResponse, error)
	// EnableAPIKey implements enableAPIKey operation.
	//
	// Enable an API key.
	//
	// POST /api-keys/{keyId}/enable
	EnableAPIKey(ctx context.Context, params EnableAPIKeyParams) (*MessageResponse, error)
	// ListAPIKeys implements listAPIKeys operation.
	//
	// List all API keys.
	//
	// GET /api-keys
	ListAPIKeys(ctx context.Context) ([]APIKey, error)
}

// AuthHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Auth
type AuthHandler interface {
	// ChangePassword implements changePassword operation.
	//
	// Change current user password.
	//
	// PUT /auth/password
	ChangePassword(ctx context.Context, req *ChangePasswordReq) (ChangePasswordRes, error)
	// Disable2FA implements disable2FA operation.
	//
	// Disable 2FA.
	//
	// POST /auth/2fa/disable
	Disable2FA(ctx context.Context, req *Disable2FAReq) (*MessageResponse, error)
	// Enable2FA implements enable2FA operation.
	//
	// Enable 2FA after verifying token.
	//
	// POST /auth/2fa/enable
	Enable2FA(ctx context.Context, req *Enable2FAReq) (*MessageResponse, error)
	// Get2FAStatus implements get2FAStatus operation.
	//
	// Get 2FA status for current user.
	//
	// GET /auth/2fa
	Get2FAStatus(ctx context.Context) (*Get2FAStatusOK, error)
	// Login implements login operation.
	//
	// Authenticate with username and password.
	//
	// POST /auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Invalidate current session.
	//
	// POST /auth/logout
	Logout(ctx context.Context) error
	// NeedSetup implements needSetup operation.
	//
	// Check if initial setup is required.
	//
	// GET /auth/setup
	NeedSetup(ctx context.Context) (*NeedSetupOK, error)
	// Prepare2FA implements prepare2FA operation.
	//
	// Generate 2FA secret and QR URI.
	//
	// POST /auth/2fa/prepare
	Prepare2FA(ctx context.Context, req *Prepare2FAReq) (*Prepare2FAOK, error)
	// RefreshToken implements refreshToken operation.
	//
	// Refresh JWT token.
	//
	// POST /auth/token/refresh
	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (RefreshTokenRes, error)
	// Setup implements setup operation.
	//
	// Create initial admin user.
	//
	// POST /auth/setup
	Setup(ctx context.Context, req *SetupReq) (SetupRes, error)
}

// BadgeHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Badge
type BadgeHandler interface {
	// GetCertExpiryBadge implements getCertExpiryBadge operation.
	//
	// Get certificate expiry badge SVG.
	//
	// GET /badges/{monitorId}/cert-exp
	GetCertExpiryBadge(ctx context.Context, params GetCertExpiryBadgeParams) (SVGBadge, error)
	// GetPingBadge implements getPingBadge operation.
	//
	// Get average ping badge SVG.
	//
	// GET /badges/{monitorId}/ping
	GetPingBadge(ctx context.Context, params GetPingBadgeParams) (SVGBadge, error)
	// GetResponseBadge implements getResponseBadge operation.
	//
	// Get last response time badge SVG.
	//
	// GET /badges/{monitorId}/response
	GetResponseBadge(ctx context.Context, params GetResponseBadgeParams) (SVGBadge, error)
	// GetStatusBadge implements getStatusBadge operation.
	//
	// Get status badge SVG for a monitor.
	//
	// GET /badges/{monitorId}/status
	GetStatusBadge(ctx context.Context, params GetStatusBadgeParams) (SVGBadge, error)
	// GetUptimeBadge implements getUptimeBadge operation.
	//
	// Get uptime percentage badge SVG.
	//
	// GET /badges/{monitorId}/uptime
	GetUptimeBadge(ctx context.Context, params GetUptimeBadgeParams) (SVGBadge, error)
}

// EventHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Event
type EventHandler interface {
	// GetStatusPageEventStream implements getStatusPageEventStream operation.
	//
	// Subscribe to real-time status page events via SSE.
	//
	// GET /status-pages/{slug}/events
	GetStatusPageEventStream(ctx context.Context, params GetStatusPageEventStreamParams) (GetStatusPageEventStreamOK, error)
}

// HeartbeatHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Heartbeat
type HeartbeatHandler interface {
	// ClearEvents implements clearEvents operation.
	//
	// Clear important heartbeats (events) for a monitor.
	//
	// DELETE /monitors/{monitorId}/events
	ClearEvents(ctx context.Context, params ClearEventsParams) error
	// ClearHeartbeats implements clearHeartbeats operation.
	//
	// Clear all heartbeats for a monitor.
	//
	// DELETE /monitors/{monitorId}/heartbeats
	ClearHeartbeats(ctx context.Context, params ClearHeartbeatsParams) error
	// GetChartData implements getChartData operation.
	//
	// Get aggregated chart data for a monitor.
	//
	// GET /monitors/{monitorId}/heartbeats/chart
	GetChartData(ctx context.Context, params GetChartDataParams) ([]ChartPoint, error)
	// GetHeartbeats implements getHeartbeats operation.
	//
	// Returns heartbeat history. Use either `hours` to get all heartbeats within a time window,
	// or `count` to get the N most recent heartbeats. If both are provided, `count` takes precedence.
	//
	// GET /monitors/{monitorId}/heartbeats
	GetHeartbeats(ctx context.Context, params GetHeartbeatsParams) ([]Heartbeat, error)
	// GetImportantHeartbeats implements getImportantHeartbeats operation.
	//
	// Get important heartbeats (status changes).
	//
	// GET /monitors/{monitorId}/events
	GetImportantHeartbeats(ctx context.Context, params GetImportantHeartbeatsParams) (*GetImportantHeartbeatsOK, error)
}

// IncidentHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Incident
type IncidentHandler interface {
	// CreateIncident implements createIncident operation.
	//
	// Create an incident on a status page.
	//
	// POST /status-pages/{slug}/incidents
	CreateIncident(ctx context.Context, req *IncidentInput, params CreateIncidentParams) (*Incident, error)
	// DeleteIncident implements deleteIncident operation.
	//
	// Delete an incident.
	//
	// DELETE /status-pages/{slug}/incidents/{incidentId}
	DeleteIncident(ctx context.Context, params DeleteIncidentParams) error
	// ListIncidents implements listIncidents operation.
	//
	// Get incident history for a status page.
	//
	// GET /status-pages/{slug}/incidents
	ListIncidents(ctx context.Context, params ListIncidentsParams) (*ListIncidentsOK, error)
	// ResolveIncident implements resolveIncident operation.
	//
	// Mark an incident as resolved.
	//
	// POST /status-pages/{slug}/incidents/{incidentId}/resolve
	ResolveIncident(ctx context.Context, params ResolveIncidentParams) (*Incident, error)
	// UnpinIncident implements unpinIncident operation.
	//
	// Unpin an incident from the status page.
	//
	// POST /status-pages/{slug}/incidents/{incidentId}/unpin
	UnpinIncident(ctx context.Context, params UnpinIncidentParams) (*MessageResponse, error)
	// UpdateIncident implements updateIncident operation.
	//
	// Update an incident.
	//
	// PUT /status-pages/{slug}/incidents/{incidentId}
	UpdateIncident(ctx context.Context, req *IncidentInput, params UpdateIncidentParams) (*Incident, error)
}

// MaintenanceHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Maintenance
type MaintenanceHandler interface {
	// CreateMaintenance implements createMaintenance operation.
	//
	// Create a maintenance window.
	//
	// POST /maintenance
	CreateMaintenance(ctx context.Context, req *MaintenanceInput) (*CreateMaintenanceCreated, error)
	// DeleteMaintenance implements deleteMaintenance operation.
	//
	// Delete a maintenance window.
	//
	// DELETE /maintenance/{maintenanceId}
	DeleteMaintenance(ctx context.Context, params DeleteMaintenanceParams) error
	// GetMaintenance implements getMaintenance operation.
	//
	// Get a maintenance window.
	//
	// GET /maintenance/{maintenanceId}
	GetMaintenance(ctx context.Context, params GetMaintenanceParams) (*Maintenance, error)
	// GetMaintenanceMonitors implements getMaintenanceMonitors operation.
	//
	// Get monitors for a maintenance window.
	//
	// GET /maintenance/{maintenanceId}/monitors
	GetMaintenanceMonitors(ctx context.Context, params GetMaintenanceMonitorsParams) ([]uuid.UUID, error)
	// GetMaintenanceStatusPages implements getMaintenanceStatusPages operation.
	//
	// Get status pages for a maintenance window.
	//
	// GET /maintenance/{maintenanceId}/status-pages
	GetMaintenanceStatusPages(ctx context.Context, params GetMaintenanceStatusPagesParams) ([]uuid.UUID, error)
	// ListMaintenance implements listMaintenance operation.
	//
	// List all maintenance windows.
	//
	// GET /maintenance
	ListMaintenance(ctx context.Context) ([]Maintenance, error)
	// PauseMaintenance implements pauseMaintenance operation.
	//
	// Pause a maintenance window.
	//
	// POST /maintenance/{maintenanceId}/pause
	PauseMaintenance(ctx context.Context, params PauseMaintenanceParams) (*MessageResponse, error)
	// ResumeMaintenance implements resumeMaintenance operation.
	//
	// Resume a maintenance window.
	//
	// POST /maintenance/{maintenanceId}/resume
	ResumeMaintenance(ctx context.Context, params ResumeMaintenanceParams) (*MessageResponse, error)
	// SetMaintenanceMonitors implements setMaintenanceMonitors operation.
	//
	// Set monitors for a maintenance window.
	//
	// PUT /maintenance/{maintenanceId}/monitors
	SetMaintenanceMonitors(ctx context.Context, req *SetMaintenanceMonitorsReq, params SetMaintenanceMonitorsParams) error
	// SetMaintenanceStatusPages implements setMaintenanceStatusPages operation.
	//
	// Set status pages for a maintenance window.
	//
	// PUT /maintenance/{maintenanceId}/status-pages
	SetMaintenanceStatusPages(ctx context.Context, req *SetMaintenanceStatusPagesReq, params SetMaintenanceStatusPagesParams) error
	// UpdateMaintenance implements updateMaintenance operation.
	//
	// Update a maintenance window.
	//
	// PUT /maintenance/{maintenanceId}
	UpdateMaintenance(ctx context.Context, req *MaintenanceInput, params UpdateMaintenanceParams) (*Maintenance, error)
}

// MonitorHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Monitor
type MonitorHandler interface {
	// CheckDomain implements checkDomain operation.
	//
	// Check domain/TLD information.
	//
	// GET /monitors/{monitorId}/domain
	CheckDomain(ctx context.Context, params CheckDomainParams) (*CheckDomainOK, error)
	// CreateMonitor implements createMonitor operation.
	//
	// Create a new monitor.
	//
	// POST /monitors
	CreateMonitor(ctx context.Context, req *MonitorInput) (*CreateMonitorCreated, error)
	// DeleteMonitor implements deleteMonitor operation.
	//
	// Delete a monitor.
	//
	// DELETE /monitors/{monitorId}
	DeleteMonitor(ctx context.Context, params DeleteMonitorParams) (DeleteMonitorRes, error)
	// GetMonitor implements getMonitor operation.
	//
	// Get a monitor by ID.
	//
	// GET /monitors/{monitorId}
	GetMonitor(ctx context.Context, params GetMonitorParams) (GetMonitorRes, error)
	// GetMonitorUptimes implements getMonitorUptimes operation.
	//
	// Get 24-hour uptime percentages for all active monitors.
	//
	// GET /monitors/uptimes
	GetMonitorUptimes(ctx context.Context) (GetMonitorUptimesOK, error)
	// ListMonitors implements listMonitors operation.
	//
	// List all monitors for the current user.
	//
	// GET /monitors
	ListMonitors(ctx context.Context) ([]Monitor, error)
	// PauseMonitor implements pauseMonitor operation.
	//
	// Pause a monitor.
	//
	// POST /monitors/{monitorId}/pause
	PauseMonitor(ctx context.Context, params PauseMonitorParams) (*MessageResponse, error)
	// ResumeMonitor implements resumeMonitor operation.
	//
	// Resume a paused monitor.
	//
	// POST /monitors/{monitorId}/resume
	ResumeMonitor(ctx context.Context, params ResumeMonitorParams) (*MessageResponse, error)
	// UpdateMonitor implements updateMonitor operation.
	//
	// Update a monitor.
	//
	// PUT /monitors/{monitorId}
	UpdateMonitor(ctx context.Context, req *MonitorInput, params UpdateMonitorParams) (UpdateMonitorRes, error)
}

// NotificationHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Notification
type NotificationHandler interface {
	// CreateNotification implements createNotification operation.
	//
	// Create a notification provider.
	//
	// POST /notifications
	CreateNotification(ctx context.Context, req *NotificationInput) (*CreateNotificationCreated, error)
	// DeleteNotification implements deleteNotification operation.
	//
	// Delete a notification provider.
	//
	// DELETE /notifications/{notificationId}
	DeleteNotification(ctx context.Context, params DeleteNotificationParams) error
	// ListNotifications implements listNotifications operation.
	//
	// List all notification providers.
	//
	// GET /notifications
	ListNotifications(ctx context.Context) ([]Notification, error)
	// TestNotification implements testNotification operation.
	//
	// Send a test notification.
	//
	// POST /notifications/{notificationId}/test
	TestNotification(ctx context.Context, params TestNotificationParams) (*MessageResponse, error)
	// UpdateNotification implements updateNotification operation.
	//
	// Update a notification provider.
	//
	// PUT /notifications/{notificationId}
	UpdateNotification(ctx context.Context, req *NotificationInput, params UpdateNotificationParams) (*Notification, error)
}

// ProxyHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Proxy
type ProxyHandler interface {
	// CreateProxy implements createProxy operation.
	//
	// Add a proxy.
	//
	// POST /proxies
	CreateProxy(ctx context.Context, req *ProxyInput) (*CreateProxyCreated, error)
	// DeleteProxy implements deleteProxy operation.
	//
	// Delete a proxy.
	//
	// DELETE /proxies/{proxyId}
	DeleteProxy(ctx context.Context, params DeleteProxyParams) error
	// ListProxies implements listProxies operation.
	//
	// List proxies.
	//
	// GET /proxies
	ListProxies(ctx context.Context) ([]Proxy, error)
	// UpdateProxy implements updateProxy operation.
	//
	// Update a proxy.
	//
	// PUT /proxies/{proxyId}
	UpdateProxy(ctx context.Context, req *ProxyInput, params UpdateProxyParams) error
}

// PushHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Push
type PushHandler interface {
	// PushHeartbeat implements pushHeartbeat operation.
	//
	// Report status for a push monitor.
	//
	// GET /push/{pushToken}
	PushHeartbeat(ctx context.Context, params PushHeartbeatParams) (PushHeartbeatRes, error)
}

// SettingsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Settings
type SettingsHandler interface {
	// GetSettings implements getSettings operation.
	//
	// Get all application settings.
	//
	// GET /settings
	GetSettings(ctx context.Context) (*Settings, error)
	// UpdateSettings implements updateSettings operation.
	//
	// Update application settings.
	//
	// PATCH /settings
	UpdateSettings(ctx context.Context, req *Settings) (*MessageResponse, error)
}

// StatusPageHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: StatusPage
type StatusPageHandler interface {
	// CreateStatusPage implements createStatusPage operation.
	//
	// Create a status page.
	//
	// POST /status-pages
	CreateStatusPage(ctx context.Context, req *StatusPageInput) (*CreateStatusPageCreated, error)
	// DeleteStatusPage implements deleteStatusPage operation.
	//
	// Delete a status page.
	//
	// DELETE /status-pages/{slug}
	DeleteStatusPage(ctx context.Context, params DeleteStatusPageParams) error
	// GetStatusPage implements getStatusPage operation.
	//
	// Get public status page data.
	//
	// GET /status-pages/{slug}
	GetStatusPage(ctx context.Context, params GetStatusPageParams) (GetStatusPageRes, error)
	// GetStatusPageBadge implements getStatusPageBadge operation.
	//
	// Get overall status badge for a status page.
	//
	// GET /status-pages/{slug}/badge
	GetStatusPageBadge(ctx context.Context, params GetStatusPageBadgeParams) (GetStatusPageBadgeOK, error)
	// GetStatusPageHeartbeats implements getStatusPageHeartbeats operation.
	//
	// Get current heartbeats for a public status page.
	//
	// GET /status-pages/{slug}/heartbeats
	GetStatusPageHeartbeats(ctx context.Context, params GetStatusPageHeartbeatsParams) (*GetStatusPageHeartbeatsOK, error)
	// ListStatusPages implements listStatusPages operation.
	//
	// List all status pages.
	//
	// GET /status-pages
	ListStatusPages(ctx context.Context) ([]StatusPage, error)
	// UpdateStatusPage implements updateStatusPage operation.
	//
	// Update a status page.
	//
	// PUT /status-pages/{slug}
	UpdateStatusPage(ctx context.Context, req *StatusPageInput, params UpdateStatusPageParams) (*StatusPage, error)
}

// SystemHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: System
type SystemHandler interface {
	// ClearStatistics implements clearStatistics operation.
	//
	// Clear all statistics data.
	//
	// DELETE /statistics
	ClearStatistics(ctx context.Context) error
	// GetDatabaseSize implements getDatabaseSize operation.
	//
	// Get database size.
	//
	// GET /database/size
	GetDatabaseSize(ctx context.Context) (*GetDatabaseSizeOK, error)
	// GetInfo implements getInfo operation.
	//
	// Get server info (version, timezone).
	//
	// GET /info
	GetInfo(ctx context.Context) (*GetInfoOK, error)
	// HealthCheck implements healthCheck operation.
	//
	// Health check endpoint.
	//
	// GET /health
	HealthCheck(ctx context.Context) (*HealthCheckOK, error)
	// ShrinkDatabase implements shrinkDatabase operation.
	//
	// Shrink database (vacuum).
	//
	// POST /database/shrink
	ShrinkDatabase(ctx context.Context) (*MessageResponse, error)
}

// TagHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Tag
type TagHandler interface {
	// AddMonitorTag implements addMonitorTag operation.
	//
	// Add a tag to a monitor.
	//
	// POST /monitors/{monitorId}/tags
	AddMonitorTag(ctx context.Context, req *AddMonitorTagReq, params AddMonitorTagParams) error
	// CreateTag implements createTag operation.
	//
	// Create a tag.
	//
	// POST /tags
	CreateTag(ctx context.Context, req *TagInput) (*Tag, error)
	// DeleteMonitorTag implements deleteMonitorTag operation.
	//
	// Remove a tag from a monitor.
	//
	// DELETE /monitors/{monitorId}/tags/{tagId}
	DeleteMonitorTag(ctx context.Context, params DeleteMonitorTagParams) error
	// DeleteTag implements deleteTag operation.
	//
	// Delete a tag.
	//
	// DELETE /tags/{tagId}
	DeleteTag(ctx context.Context, params DeleteTagParams) error
	// ListTags implements listTags operation.
	//
	// List all tags.
	//
	// GET /tags
	ListTags(ctx context.Context) ([]Tag, error)
	// UpdateMonitorTag implements updateMonitorTag operation.
	//
	// Update a monitor tag value.
	//
	// PUT /monitors/{monitorId}/tags/{tagId}
	UpdateMonitorTag(ctx context.Context, req *UpdateMonitorTagReq, params UpdateMonitorTagParams) error
	// UpdateTag implements updateTag operation.
	//
	// Update a tag.
	//
	// PUT /tags/{tagId}
	UpdateTag(ctx context.Context, req *TagInput, params UpdateTagParams) (*Tag, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
