// Code generated by ogen, DO NOT EDIT.
package oas

type ChangePasswordRes interface {
	changePasswordRes()
}

type DeleteMonitorRes interface {
	deleteMonitorRes()
}

type GetMonitorRes interface {
	getMonitorRes()
}

type GetStatusPageRes interface {
	getStatusPageRes()
}

type LoginRes interface {
	loginRes()
}

type PushHeartbeatRes interface {
	pushHeartbeatRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type SetupRes interface {
	setupRes()
}

type UpdateMonitorRes interface {
	updateMonitorRes()
}
